In [2]:
from pymatgen.core import Lattice, Structure
import pandas as pd
import numpy as np
import plotly as pt
import seaborn as sns
#!pip install pymatgen
#!pip install mp_api
import requests
import json
import matplotlib.pyplot as plt

In [77]:
root_folder = ""
data_folder = "Data/" #"/content/drive/MyDrive/University/Artificial intelligence in chemistry/Perovskite project/Perovskite-liked-oxides-bandgap-prediction/Data/"
cif_folder = "Data/CIF/"
input_dataset_path = "checkpoint_cif_embeddings.xlsx"
extend_mattergen_dataset = True

In [78]:
df = pd.read_excel(input_dataset_path)

In [79]:
df

,Unnamed: 0,Perovskite,Hill formula,Interlayer space composition,Class,"Bandgap, eV",Materials Project ID,COD_ID,Springer_ID,Z,...,Valence Electrons Density_manual,Oxygen_count,Oxygen_concentration_manual,Oxygen_concentration_MP,Oxygen_concentration_COD,Oxygen_concentration_Springer,MP_packing_fraction,COD_packing_fraction,Springer_packing_fraction,Manual_packing_fraction
0,0,K4Nb6O17,K4 Nb6 O17,NaN,K4Nb6O17,3.50,mp-560692,1001842,-1,4.0,...,0.077010,17.0,0.038505,0.038482,0.040481,NaN,0.482644,0.507705,NaN,0.482925
1,1,KLaNb2O7,K1 La1 Nb2 O7,NaN,HLaNb2O7,3.20,mp-1223501,1545643,-1,8.0,...,0.086868,7.0,0.043434,0.040335,0.021337,NaN,0.484504,0.256300,NaN,0.521726
2,2,RbLaNb2O7,Rb1 La1 Nb2 O7,NaN,HLaNb2O7,3.35,mp-553965,-1,-1,1.0,...,0.084409,7.0,0.042204,0.040114,NaN,NaN,0.507344,NaN,NaN,0.533788
3,3,CsLaNb2O7,Cs1 La1 Nb2 O7,NaN,HLaNb2O7,3.30,mp-553248,2004917,-1,1.0,...,0.082082,7.0,0.041041,0.038958,0.041070,NaN,0.524329,0.552752,NaN,0.552364
4,4,KCa2Nb3O10,K1 Ca2 Nb3 O10,NaN,KCa2Nb3O10,3.35,mp-557195,1521061,-1,8.0,...,0.090945,10.0,0.045472,0.043255,0.045288,NaN,0.505552,0.529316,NaN,0.531466
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,1084,TiO2,Ti1 O2,NaN,oxide,3.20,mp-1245098,1010942,-1,NaN,...,NaN,2.0,NaN,0.050730,0.061367,NaN,0.469004,0.567346,NaN,NaN
732,1085,TiO2,Ti1 O2,NaN,oxide,3.20,mp-1245098,1010942,-1,NaN,...,NaN,2.0,NaN,0.050730,0.061367,NaN,0.469004,0.567346,NaN,NaN
733,1086,TiO2,Ti1 O2,NaN,oxide,3.20,mp-1245098,1010942,-1,NaN,...,NaN,2.0,NaN,0.050730,0.061367,NaN,0.469004,0.567346,NaN,NaN
734,1087,TiO2,Ti1 O2,NaN,oxide,3.20,mp-1245098,1010942,-1,NaN,...,NaN,2.0,NaN,0.050730,0.061367,NaN,0.469004,0.567346,NaN,NaN
735,1088,TiO2,Ti1 O2,NaN,oxide,3.20,mp-1245098,1010942,-1,NaN,...,NaN,2.0,NaN,0.050730,0.061367,NaN,0.469004,0.567346,NaN,NaN

# Clean my dataset from non-MP entries

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Data columns (total 84 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Unnamed: 0                          736 non-null    int64
 1   Perovskite                          736 non-null    object
 2   Hill formula                        736 non-null    object
 3   Interlayer space composition        4 non-null      object
 4   Class                               606 non-null    object
 5   Bandgap, eV                         715 non-null    float64
 6   Materials Project ID                736 non-null    object
 7   COD_ID                              736 non-null    int64
 8   Springer_ID                         736 non-null    object
 9   Z                                   469 non-null    float64
 10  a, A                                484 non-null    float64
 11  b, A                                483 non-null    float64
 12  c, A                                483 non-null    float64
 13  Symmetry group                      334 non-null    object
 14  d,A                                 560 non-null    float64
 15  Number of octahedrons on a layer    98 non-null     float64
 16  Prep Method                         736 non-null    object
 17  CalcT(K)                            716 non-null    float64
 18  Calc time (h)                       689 non-null    float64
 19  Nitrogen                            736 non-null    bool
 20  Promotion method                    736 non-null    object
 21  Promoter                            736 non-null    object
 22  Promoter, w%                        736 non-null    float64
 23  Surface area, m2/g                  412 non-null    float64
 24  CatW, g/L                           736 non-null    float64
 25  Alcohol, %                          730 non-null    float64
 26  Sac Agent 1                         0 non-null      float64
 27  Sac agent 2                         0 non-null      float64
 28  Light type                          736 non-null    object
 29  Power, W                            733 non-null    float64
 30  Wave length min, nm                 489 non-null    float64
 31  Cell material                       736 non-null    object
 32  Temperature, K                      409 non-null    float64
 33  Rate, umol/(g*h)                    736 non-null    float64
 34  MP_CIF_modifier                     375 non-null    object
 35  COD_CIF_modifier                    139 non-null    object
 36  Springer_CIF_modifier               70 non-null     object
 37  Materials Project verification      736 non-null    bool
 38  COD verification                    736 non-null    bool
 39  Springer verification               736 non-null    bool
 40  General verification                736 non-null    bool
 41  MP_CIF_modified                     722 non-null    object
 42  COD_CIF_modified                    625 non-null    object
 43  Springer_CIF_modified               161 non-null    object
 44  Log_rate                            736 non-null    float64
 45  avg s valence electrons             736 non-null    float64
 46  avg p valence electrons             736 non-null    float64
 47  avg d valence electrons             736 non-null    float64
 48  avg f valence electrons             736 non-null    float64
 49  frac s valence electrons            736 non-null    float64
 50  frac p valence electrons            736 non-null    float64
 51  frac d valence electrons            736 non-null    float64
 52  frac f valence electrons            736 non-null    float64
 53  Average Mulliken electronegativity  736 non-null    float64
 54  Valence electrons                   736 non-null    float64
 55  Volume_MP                           736 non-null    float64
 56  Z_MP                                736 non-null    int64
 57  Valence Electrons Density_MP        673 non-null    float64
 58  a_MP                                736 non-null    float64
 59  b_MP                                696 non-null    float64
 60  c_MP                                696 non-null    float64
 61  Volume_COD                          736 non-null    float64
 62  Z_COD                               736 non-null    int64
 63  Valence Electrons Density_COD       399 non-null    float64
 64  a_COD                               736 non-null    float64
 65  b_COD                               510 non-null    float64
 66  c_COD                               510 non-null    float64
 67  Volume_Springer                     736 non-null    float64
 68  Z_Springer                          736 non-null    int64
 69  Valence Electrons Density_Springer  93 non-null     float64
 70  a_Springer                          736 non-null    float64
 71  b_Springer                          736 non-null    float64
 72  c_Springer                          736 non-null    float64
 73  Volume_manual                       483 non-null    float64
 74  Valence Electrons Density_manual    467 non-null    float64
 75  Oxygen_count                        736 non-null    float64
 76  Oxygen_concentration_manual         467 non-null    float64
 77  Oxygen_concentration_MP             673 non-null    float64
 78  Oxygen_concentration_COD            399 non-null    float64
 79  Oxygen_concentration_Springer       93 non-null     float64
 80  MP_packing_fraction                 673 non-null    float64
 81  COD_packing_fraction                399 non-null    float64
 82  Springer_packing_fraction           93 non-null     float64
 83  Manual_packing_fraction             467 non-null    float64
dtypes: bool(5), float64(56), int64(5), object(18)
memory usage: 458.0+ KB

In [81]:
#df_nan = df[df["MP_CIF_modifier"].isna()]

In [82]:
import os
from pymatgen.io.cif import CifWriter
from mp_api.client import MPRester
API_KEY = "GFsoU5OV3dEngGT860TOtWcn35bE4y6l"

In [83]:
def get_cif_string_from_id(MP_ID):
  
  file_path=cif_folder + str(MP_ID)+".cif"
  #print("Path: ",file_path)
  if os.path.exists(file_path):
    try:
      structure = Structure.from_file(file_path)
    except:
      print('ERROR: Invalid structure for ',MP_ID)
      return None
  else:
    return None

  if(structure == None):
    return None
  writer = CifWriter(structure)
  cif_string = str(writer)
  #print("CIF string: ",cif_string)
  return cif_string

In [84]:
def get_CIF_string_from_IDs(MP_ID, COD_ID, Springer_ID):
    #print("func")
    MP_CIF = get_cif_string_from_id(MP_ID)
    COD_CIF = get_cif_string_from_id(COD_ID)
    Springer_CIF = get_cif_string_from_id(Springer_ID)
    if MP_CIF:
        return MP_CIF
    if COD_CIF:
        return COD_CIF
    if Springer_CIF:
        return Springer_CIF
    return ""

In [85]:
get_CIF_string_from_IDs("mp-31760","","")

"# generated using pymatgen\ndata_Sr2TaFeO6\n_symmetry_space_group_name_H-M   'P 1'\n_cell_length_a   5.66717500\n_cell_length_b   9.81577371\n_cell_length_c   9.81532669\n_cell_angle_alpha   70.70136550\n_cell_angle_beta   90.00000000\n_cell_angle_gamma   90.00000000\n_symmetry_Int_Tables_number   1\n_chemical_formula_structural   Sr2TaFeO6\n_chemical_formula_sum   'Sr8 Ta4 Fe4 O24'\n_cell_volume   515.32350959\n_cell_formula_units_Z   4\nloop_\n _symmetry_equiv_pos_site_id\n _symmetry_equiv_pos_as_xyz\n  1  'x, y, z'\nloop_\n _atom_site_type_symbol\n _atom_site_label\n _atom_site_symmetry_multiplicity\n _atom_site_fract_x\n _atom_site_fract_y\n _atom_site_fract_z\n _atom_site_occupancy\n  Sr  Sr0  1  0.48739800  0.12345700  0.62621200  1.0\n  Sr  Sr1  1  0.48739800  0.62345700  0.12621200  1.0\n  Sr  Sr2  1  0.98739800  0.87654300  0.87378800  1.0\n  Sr  Sr3  1  0.98739800  0.37654300  0.37378800  1.0\n  Sr  Sr4  1  0.01260200  0.12345700  0.12621200  1.0\n  Sr  Sr5  1  0.01260200  0.62345700  0.62621200  1.0\n  Sr  Sr6  1  0.51260200  0.87654300  0.37378800  1.0\n  Sr  Sr7  1  0.51260200  0.37654300  0.87378800  1.0\n  Ta  Ta8  1  0.00000000  0.75000000  0.25000000  1.0\n  Ta  Ta9  1  0.00000000  0.25000000  0.75000000  1.0\n  Ta  Ta10  1  0.50000000  0.25000000  0.25000000  1.0\n  Ta  Ta11  1  0.50000000  0.75000000  0.75000000  1.0\n  Fe  Fe12  1  0.00000000  0.50000000  0.00000000  1.0\n  Fe  Fe13  1  0.50000000  0.50000000  0.50000000  1.0\n  Fe  Fe14  1  0.00000000  0.00000000  0.50000000  1.0\n  Fe  Fe15  1  0.50000000  0.00000000  0.00000000  1.0\n  O  O16  1  0.49492600  0.65131100  0.60123900  1.0\n  O  O17  1  0.49492600  0.15131100  0.10123900  1.0\n  O  O18  1  0.99492600  0.84868900  0.39876100  1.0\n  O  O19  1  0.99492600  0.34868900  0.89876100  1.0\n  O  O20  1  0.50507400  0.34868900  0.39876100  1.0\n  O  O21  1  0.50507400  0.84868900  0.89876100  1.0\n  O  O22  1  0.00507400  0.15131100  0.60123900  1.0\n  O  O23  1  0.00507400  0.65131100  0.10123900  1.0\n  O  O24  1  0.23382700  0.87752900  0.64861300  1.0\n  O  O25  1  0.23382700  0.37752900  0.14861300  1.0\n  O  O26  1  0.73382700  0.12247100  0.85138700  1.0\n  O  O27  1  0.73382700  0.62247100  0.35138700  1.0\n  O  O28  1  0.76617300  0.12247100  0.35138700  1.0\n  O  O29  1  0.76617300  0.62247100  0.85138700  1.0\n  O  O30  1  0.26617300  0.87752900  0.14861300  1.0\n  O  O31  1  0.26617300  0.37752900  0.64861300  1.0\n  O  O32  1  0.77069600  0.89569100  0.13010500  1.0\n  O  O33  1  0.77069600  0.39569100  0.63010500  1.0\n  O  O34  1  0.27069600  0.10430900  0.36989500  1.0\n  O  O35  1  0.27069600  0.60430900  0.86989500  1.0\n  O  O36  1  0.22930400  0.10430900  0.86989500  1.0\n  O  O37  1  0.22930400  0.60430900  0.36989500  1.0\n  O  O38  1  0.72930400  0.89569100  0.63010500  1.0\n  O  O39  1  0.72930400  0.39569100  0.13010500  1.0\n"

In [86]:
df['cif'] = df.apply(lambda row: get_CIF_string_from_IDs(row['MP_CIF_modified'], row['COD_CIF_modified'], row['Springer_CIF_modified']), axis=1)

C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['K1', 'K1', 'K1', 'K1', 'K2', 'K2', 'K2', 'K2', 'K3', 'K3', 'K3', 'K3', 'K4', 'K4', 'K4', 'K4', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'Nb5', 'Nb5', 'Nb5', 'Nb5', 'Nb6', 'Nb6', 'Nb6', 'Nb6', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O4', 'O4', 'O4', 'O4', 'O5', 'O5', 'O5', 'O5', 'O6', 'O6', 'O6', 'O6', 'O7', 'O7', 'O7', 'O7', 'O8', 'O8', 'O8', 'O8', 'O9', 'O9', 'O9', 'O9', 'O10', 'O10', 'O10', 'O10', 'O11', 'O11', 'O11', 'O11', 'O12', 'O12', 'O12', 'O12', 'O13', 'O13', 'O13', 'O13', 'O14', 'O14', 'O14', 'O14', 'O15', 'O15', 'O15', 'O15', 'O16', 'O16', 'O16', 'O16', 'O17', 'O17', 'O17', 'O17']`.
  writer = CifWriter(structure)
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\io\cif.py:1342: UserWarning: Incorrect stoichiometry:
  CIF={'K': 1.0, 'La': 1.0, 'Nb': 2.0, 'O': 7.0}
  PMG={'K': 2.188, 'La': 1.936, 'Nb': 4.0, 'O': 14.0}
  ratios={'O': 2.0, 'K': 2.188, 'La': 1.936, 'Nb': 2.0}
  if struct := self._get_structure(data, primitive, symmetrized, check_occu=check_occu):
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['K', 'K', 'K', 'K', 'La', 'La', 'Nb6', 'Nb7', 'Nb8', 'Nb9', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O4', 'O4', 'O4', 'O4']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Cs0', 'La1', 'Nb2', 'Nb3', 'O(1)', 'O(1)', 'O(1)', 'O(1)', 'O(2)', 'O(2)', 'O(3)']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['K1', 'K1', 'K1', 'K1', 'Ca2', 'Ca2', 'Ca2', 'Ca2', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'O6', 'O6', 'O6', 'O6', 'O5', 'O5', 'O5', 'O5', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Rb1', 'Ca1', 'Ca1', 'Nb1', 'Nb2', 'Nb2', 'O1', 'O1', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O4', 'O4']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Cs1', 'Cs1', 'Cs1', 'Cs1', 'Cs2', 'Cs2', 'Cs2', 'Cs2', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca2', 'Ca2', 'Ca2', 'Ca2', 'Ca3', 'Ca3', 'Ca3', 'Ca3', 'Ca4', 'Ca4', 'Ca4', 'Ca4', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O6', 'O6', 'O6', 'O6', 'O6', 'O6', 'O6', 'O6', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O8', 'O8', 'O8', 'O8', 'O9', 'O9', 'O9', 'O9', 'O10', 'O10', 'O10', 'O10', 'O11', 'O11', 'O11', 'O11', 'O12', 'O12', 'O12', 'O12', 'O13', 'O13', 'O13', 'O13']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ti1', 'Ti1', 'Ti1', 'Ti1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ca1', 'Ca1', 'Ta1', 'Ta2', 'Ta2', 'Cs1', 'O3', 'O3', 'O3', 'O3', 'O2', 'O2', 'O4', 'O4', 'O1', 'O1']`.
  writer = CifWriter(structure)
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\io\cif.py:285: UserWarning: Possible issue in CIF file at line: No transformation from published to standardized cell parameters necessary.
  block = CifBlock.from_str(f"data_{block_str}")
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\io\cif.py:285: UserWarning: Possible issue in CIF file at line: ?
  block = CifBlock.from_str(f"data_{block_str}")
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\io\cif.py:1057: UserWarning: No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
  self.symmetry_operations = self.get_symops(data)  # type:ignore[assignment]
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: No structure parsed for section 1 in CIF.
'_atom_site_label'
  struct = parser.parse_structures(primitive=primitive)[0]
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\io\cif.py:1072: UserWarning: t parsed as T
  symbol = self._parse_symbol(label)
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: No structure parsed for section 3 in CIF.
could not convert string to float: 't'
  struct = parser.parse_structures(primitive=primitive)[0]
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: No structure parsed for section 4 in CIF.
could not convert string to float: 't'
  struct = parser.parse_structures(primitive=primitive)[0]
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
No structure parsed for section 1 in CIF.
'_atom_site_label'
No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
t parsed as T
No structure parsed for section 3 in CIF.
could not convert string to float: 't'
No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
t parsed as T
No structure parsed for section 4 in CIF.
could not convert string to float: 't'
  struct = parser.parse_structures(primitive=primitive)[0]
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\io\cif.py:1057: UserWarning: No _symmetry_equiv_pos_as_xyz type key found. Spacegroup from _symmetry_space_group_name_H-M used.
  self.symmetry_operations = self.get_symops(data)  # type:ignore[assignment]
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\io\cif.py:1342: UserWarning: Cannot determine chemical composition from CIF! 'NoneType' object is not iterable
  if struct := self._get_structure(data, primitive, symmetrized, check_occu=check_occu):
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: No structure parsed for section 1 in CIF.
'_atom_site_label'
No _symmetry_equiv_pos_as_xyz type key found. Spacegroup from _symmetry_space_group_name_H-M used.
No _symmetry_equiv_pos_as_xyz type key found. Spacegroup from _symmetry_space_group_name_H-M used.
No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
  struct = parser.parse_structures(primitive=primitive)[0]

ERROR: Invalid structure for  sd_1614775
ERROR: Invalid structure for  sd_1614775
ERROR: Invalid structure for  sd_1614775

C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Rb1', 'Pr1', 'Ta1', 'Ta1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O3']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Sr1', 'Sr1', 'Sr1', 'Sr1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'O1', 'O1', 'O1', 'O1', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ba1', 'Ba1', 'Ba1', 'Ba1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O3', 'O3', 'O3', 'O3']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Sr1', 'Sr1', 'Sr1', 'Sr1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O1', 'O1', 'O1', 'O1']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ba1', 'Ba1', 'Ba1', 'Ba1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'O3', 'O3', 'O3', 'O3', 'O2', 'O2', 'O2', 'O2', 'O1', 'O1', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Nb0', 'Nb0', 'Nb1', 'Nb1', 'Bi2', 'Bi3', 'Pb4', 'O5', 'O6', 'O7', 'O8', 'O9', 'O10', 'O11', 'O12', 'O13']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Bi2', 'Bi2', 'Bi1', 'Bi1', 'Bi3', 'Bi3', 'Bi3', 'Bi3', 'Pb2', 'Pb1', 'Pb3', 'Pb3', 'O9', 'O9', 'O9', 'O9', 'O9', 'O9', 'O9', 'O9', 'O8', 'O8', 'O8', 'O8', 'O8', 'O8', 'O8', 'O8', 'O2', 'O2', 'O4', 'O4', 'O1', 'O5', 'O5', 'O3', 'O6', 'O6', 'O6', 'O6', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb2', 'Nb2', 'Nb1', 'Nb1', 'Bi2', 'Bi2', 'Bi1', 'Bi1', 'Bi3', 'Bi3', 'Bi3', 'Bi3', 'Pb2', 'Pb1', 'Pb3', 'Pb3', 'O9', 'O9', 'O9', 'O9', 'O9', 'O9', 'O9', 'O9', 'O8', 'O8', 'O8', 'O8', 'O8', 'O8', 'O8', 'O8', 'O2', 'O2', 'O4', 'O4', 'O1', 'O5', 'O5', 'O3', 'O6', 'O6', 'O6', 'O6', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb3', 'Nb3', 'Nb4', 'Nb4', 'Nb5', 'Nb5', 'Nb6', 'Nb6', 'Nb7', 'Nb7', 'Nb8', 'Nb8', 'Nb9', 'Nb9', 'Nb10', 'Nb10', 'Nb11', 'Nb11', 'Nb12', 'Nb12', 'Nb13', 'Nb13', 'Nb15', 'Nb14', 'Nb14', 'O1', 'O1', 'O2', 'O2', 'O3', 'O3', 'O4', 'O4', 'O5', 'O5', 'O6', 'O6', 'O7', 'O7', 'O8', 'O8', 'O9', 'O9', 'O10', 'O10', 'O11', 'O11', 'O12', 'O12', 'O13', 'O13', 'O14', 'O14', 'O15', 'O15', 'O16', 'O16', 'O17', 'O17', 'O18', 'O18', 'O19', 'O19', 'O20', 'O20', 'O21', 'O21', 'O22', 'O22', 'O23', 'O23', 'O24', 'O24', 'O25', 'O25', 'O26', 'O26', 'O27', 'O27', 'O28', 'O28', 'O29', 'O29', 'O30', 'O30', 'O31', 'O31', 'O32', 'O32', 'O33', 'O33', 'O34', 'O34', 'O35', 'O36']`.
  writer = CifWriter(structure)
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: Pauling file corrections applied.
No structure parsed for section 1 in CIF.
'_atom_site_label'
No _symmetry_equiv_pos_as_xyz type key found. Spacegroup from _symmetry_space_group_name_H-M used.
No _symmetry_equiv_pos_as_xyz type key found. Spacegroup from _symmetry_space_group_name_H-M used.
No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
  struct = parser.parse_structures(primitive=primitive)[0]
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Pb_fix1', 'Pb_fix1', 'Pb_fix1', 'Pb_fix1', 'Pb_fix1', 'Pb_fix1', 'Pb_fix1', 'Pb_fix1', 'Pb_fix1', 'Pb_fix1', 'Pb_fix1', 'Pb_fix1', 'Pb_fix1', 'Pb_fix1', 'Pb_fix1', 'Pb_fix1', 'Pb_fix3', 'Pb_fix3', 'Pb_fix3', 'Pb_fix3', 'Pb_fix3', 'Pb_fix3', 'Pb_fix3', 'Pb_fix3', 'Pb_fix3', 'Pb_fix3', 'Pb_fix3', 'Pb_fix3', 'Pb_fix3', 'Pb_fix3', 'Pb_fix3', 'Pb_fix3', 'Pb_fix5', 'Pb_fix5', 'Pb_fix5', 'Pb_fix5', 'Pb_fix5', 'Pb_fix5', 'Pb_fix5', 'Pb_fix5', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O6', 'O6', 'O6', 'O6', 'O6', 'O6', 'O6', 'O6', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O8', 'O8', 'O8', 'O8']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['La1', 'La1', 'La1', 'La1', 'La1', 'La1', 'La2', 'La2', 'La2', 'La2', 'La2', 'La2', 'Ti2', 'Ti2', 'Ti2', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1']`.
  writer = CifWriter(structure)
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: Pauling file corrections applied.
10 fractional coordinates rounded to ideal values to avoid issues with finite precision.
No structure parsed for section 1 in CIF.
'_atom_site_label'
No _symmetry_equiv_pos_as_xyz type key found. Spacegroup from _symmetry_space_group_name_H-M used.
No _symmetry_equiv_pos_as_xyz type key found. Spacegroup from _symmetry_space_group_name_H-M used.
No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
  struct = parser.parse_structures(primitive=primitive)[0]
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ca_fix1', 'Ca_fix1', 'Ca_fix1', 'Ca_fix1', 'Ca_fix3', 'Ca_fix3', 'Ca_fix3', 'Ca_fix3', 'Ca_fix5', 'Ca_fix5', 'Ti1', 'Ti1', 'Ti2', 'Ti2', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Sr_fix1', 'Sr_fix1', 'Sr_fix1', 'Sr_fix1', 'Sr_fix3', 'Sr_fix3', 'Sr_fix3', 'Sr_fix3', 'Sr_fix5', 'Sr_fix5', 'Ti1', 'Ti1', 'Ti2', 'Ti2', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3']`.
  writer = CifWriter(structure)
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: 24 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  struct = parser.parse_structures(primitive=primitive)[0]
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: 8 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  struct = parser.parse_structures(primitive=primitive)[0]
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ba1', 'Ba1', 'Ba1', 'Ba1', 'Ba1', 'Ba1', 'Ba1', 'Ba1', 'La3', 'La3', 'La2', 'La2', 'La2', 'La2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: 3 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  struct = parser.parse_structures(primitive=primitive)[0]
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Sr1', 'Sr1', 'Sr3', 'Sr3', 'Sr3', 'Sr3', 'Sr5', 'Sr5', 'Sr5', 'Sr5', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3']`.
  writer = CifWriter(structure)
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: 12 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  struct = parser.parse_structures(primitive=primitive)[0]
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: 6 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  struct = parser.parse_structures(primitive=primitive)[0]
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ba1', 'Ba2', 'Ba2', 'Ba3', 'Ba3', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Sr1', 'Sr1', 'Sr1', 'Sr1', 'Sr2', 'Sr2', 'Sr2', 'Sr2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'O4', 'O4', 'O4', 'O4', 'O2', 'O2', 'O2', 'O2', 'O5', 'O5', 'O5', 'O5', 'O7', 'O7', 'O7', 'O7', 'O1', 'O1', 'O1', 'O1', 'O6', 'O6', 'O6', 'O6', 'O3', 'O3', 'O3', 'O3']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Sr1', 'Sr1', 'Sr1', 'Sr1', 'Sr2', 'Sr2', 'Sr2', 'Sr2', 'Sr3', 'Sr3', 'Sr3', 'Sr3', 'Sr4', 'Sr4', 'Sr4', 'Sr4', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O4', 'O4', 'O4', 'O4', 'O5', 'O5', 'O5', 'O5', 'O6', 'O6', 'O6', 'O6', 'O7', 'O7', 'O7', 'O7', 'O8', 'O8', 'O8', 'O8', 'O9', 'O9', 'O9', 'O9', 'O10', 'O10', 'O10', 'O10', 'O11', 'O11', 'O11', 'O11', 'O12', 'O12', 'O12', 'O12', 'O13', 'O13', 'O13', 'O13', 'O14', 'O14', 'O14', 'O14']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Rb1', 'Rb1', 'Rb1', 'Rb1', 'Rb2', 'Rb2', 'Rb2', 'Rb2', 'Rb3', 'Rb3', 'Rb3', 'Rb3', 'Rb4', 'Rb4', 'Rb4', 'Rb4', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O6', 'O6', 'O6', 'O6', 'O7', 'O7', 'O7', 'O7', 'O8', 'O8', 'O8', 'O8', 'O9', 'O9', 'O9', 'O9', 'O10', 'O10', 'O10', 'O10', 'O11', 'O11', 'O11', 'O11', 'O12', 'O12', 'O12', 'O12']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['K0', 'K1', 'K2', 'K3', 'K4', 'K5', 'K6', 'K7', 'K8', 'K9', 'K10', 'K11', 'K12', 'K13', 'K14', 'K15', 'Nb16', 'Nb16', 'Nb17', 'Nb17', 'Nb18', 'Nb18', 'Nb19', 'Nb19', 'Nb20', 'Nb20', 'Nb21', 'Nb21', 'Nb22', 'Nb22', 'Nb23', 'Nb23', 'Nb24', 'Nb24', 'Nb25', 'Nb25', 'Nb26', 'Nb26', 'Nb27', 'Nb27', 'Nb28', 'Nb28', 'Nb29', 'Nb29', 'Nb30', 'Nb30', 'Nb31', 'Nb31', 'Nb32', 'Nb32', 'Nb33', 'Nb33', 'Nb34', 'Nb34', 'Nb35', 'Nb35', 'Nb36', 'Nb36', 'Nb37', 'Nb37', 'Nb38', 'Nb38', 'Nb39', 'Nb39', 'O40', 'O41', 'O42', 'O43', 'O44', 'O45', 'O46', 'O47', 'O48', 'O49', 'O50', 'O51', 'O52', 'O53', 'O54', 'O55', 'O56', 'O57', 'O58', 'O59', 'O60', 'O61', 'O62', 'O63', 'O64', 'O65', 'O66', 'O67', 'O68', 'O69', 'O70', 'O71', 'O72', 'O73', 'O74', 'O75', 'O76', 'O77', 'O78', 'O79', 'O80', 'O81', 'O82', 'O83', 'O84', 'O85', 'O86', 'O87', 'O88', 'O89', 'O90', 'O91', 'O92', 'O93', 'O94', 'O95', 'O96', 'O97', 'O98', 'O99', 'O100', 'O101', 'O102', 'O103', 'O104', 'O105', 'O106', 'O107']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['K1', 'K1', 'K1', 'K1', 'K2', 'K2', 'K2', 'K2', 'K3', 'K3', 'K3', 'K3', 'K4', 'K4', 'K4', 'K4', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'Nb5', 'Nb5', 'Nb5', 'Nb5', 'Nb5', 'Nb5', 'Nb5', 'Nb5', 'Nb6', 'Nb6', 'Nb6', 'Nb6', 'Nb6', 'Nb6', 'Nb6', 'Nb6', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O4', 'O4', 'O4', 'O4', 'O5', 'O5', 'O5', 'O5', 'O6', 'O6', 'O6', 'O6', 'O7', 'O7', 'O7', 'O7', 'O8', 'O8', 'O8', 'O8', 'O9', 'O9', 'O9', 'O9', 'O10', 'O10', 'O10', 'O10', 'O11', 'O11', 'O11', 'O11', 'O12', 'O12', 'O12', 'O12', 'O13', 'O13', 'O13', 'O13', 'O14', 'O14', 'O14', 'O14', 'O15', 'O15', 'O15', 'O15', 'O16', 'O16', 'O16', 'O16', 'O17', 'O17', 'O17', 'O17']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Rb1', 'Rb1', 'Rb1', 'Rb1', 'Rb2', 'Rb2', 'Rb2', 'Rb2', 'Rb3', 'Rb3', 'Rb3', 'Rb3', 'Rb4', 'Rb4', 'Rb4', 'Rb4', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb3', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'Nb4', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O6', 'O6', 'O6', 'O6', 'O7', 'O7', 'O7', 'O7', 'O8', 'O8', 'O8', 'O8', 'O9', 'O9', 'O9', 'O9', 'O10', 'O10', 'O10', 'O10', 'O11', 'O11', 'O11', 'O11', 'O12', 'O12', 'O12', 'O12']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['K1', 'K1', 'K1', 'K1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O4', 'O4', 'O4', 'O4', 'O5', 'O5', 'O5', 'O5']`.
  writer = CifWriter(structure)

ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1925412

C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ti0', 'Ti0', 'Ti1', 'Ti1', 'Ti2', 'Ti2', 'Bi3', 'Bi4', 'Bi5', 'Bi6', 'O7', 'O8', 'O9', 'O10', 'O11', 'O12', 'O13', 'O14', 'O15', 'O16', 'O17', 'O18']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O6', 'O6', 'O6', 'O6', 'O6', 'O6', 'O6', 'O6', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ta1', 'Ta2', 'Ta2', 'Cs1', 'Ca1', 'Ca1', 'O3', 'O3', 'O3', 'O3', 'O2', 'O2', 'O4', 'O4', 'O1', 'O1']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ba3', 'Ba3', 'Ba1', 'Ba2', 'Ba2', 'Ta1', 'Ta1', 'Ta2', 'Ta2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O1', 'O1', 'O1']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Sr1', 'Sr1', 'Sr1', 'Sr1', 'Sr2', 'Sr2', 'Sr2', 'Sr2', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O4', 'O4', 'O4', 'O4', 'O5', 'O5', 'O5', 'O5', 'O6', 'O6', 'O6', 'O6', 'O7', 'O7', 'O7', 'O7']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Sr1', 'Sr1', 'Sr1', 'Sr1', 'Sr2', 'Sr2', 'Sr2', 'Sr2', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O4', 'O4', 'O4', 'O4', 'O5', 'O5', 'O5', 'O5']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['La1', 'La1', 'La1', 'La1', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Sr1', 'Sr1', 'Sr1', 'Sr1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O4', 'O4', 'O4', 'O4']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ca1', 'Ca2', 'Ta3', 'Ta4', 'Ta5', 'Cs0', 'O6', 'O6', 'O7', 'O7', 'O8', 'O8', 'O9', 'O9', 'O10', 'O10', 'O11', 'O11', 'O12', 'O12', 'O13', 'O13', 'O14', 'O14', 'O15', 'O15']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ca1', 'Ca1', 'Ta1', 'Ta2', 'Ta2', 'Cs1', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O2', 'O2', 'O2', 'O2', 'O4', 'O4', 'O4', 'O4', 'O1', 'O1', 'O1', 'O1']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Cs0', 'Ca1', 'Ca2', 'Ta3', 'Ta4', 'Ta5', 'O6', 'O6', 'O7', 'O7', 'O8', 'O8', 'O9', 'O9', 'O10', 'O10', 'O11', 'O11', 'O12', 'O12', 'O13', 'O13', 'O14', 'O14', 'O15', 'O15']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Cs1', 'Ca1', 'Ca1', 'Ta1', 'Ta2', 'Ta2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O2', 'O2', 'O2', 'O2', 'O4', 'O4', 'O4', 'O4', 'O1', 'O1', 'O1', 'O1']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ca2', 'Ca2', 'Ca2', 'Ca2', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'K1', 'K1', 'K1', 'K1', 'O6', 'O6', 'O6', 'O6', 'O5', 'O5', 'O5', 'O5', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Cs0', 'Sr', 'Sr', 'Sr', 'Sr', 'Ta2', 'Ta2', 'Ta1', 'O3', 'O3', 'O3', 'O3', 'O2', 'O2', 'O4', 'O4', 'O1', 'O1']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Sr', 'Sr', 'Sr', 'Sr', 'Ta2', 'Ta2', 'Ta1', 'Cs', 'O3', 'O3', 'O3', 'O3', 'O2', 'O2', 'O4', 'O4', 'O1', 'O1']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['K0', 'K1', 'K2', 'K3', 'Ca4', 'Ca5', 'Ca6', 'Ca7', 'Ca8', 'Ca9', 'Ca10', 'Ca11', 'Nb12', 'Nb12', 'Nb13', 'Nb13', 'Nb14', 'Nb14', 'Nb15', 'Nb15', 'Nb16', 'Nb16', 'Nb17', 'Nb17', 'Nb18', 'Nb18', 'Nb19', 'Nb19', 'Nb20', 'Nb20', 'Nb21', 'Nb21', 'Nb22', 'Nb22', 'Nb23', 'Nb23', 'O24', 'O25', 'O26', 'O27', 'O28', 'O29', 'O30', 'O31', 'O32', 'O33', 'O34', 'O35', 'O36', 'O37', 'O38', 'O39', 'O40', 'O41', 'O42', 'O43', 'O44', 'O45', 'O46', 'O47', 'O48', 'O49', 'O50', 'O51', 'O52', 'O53', 'O54', 'O55', 'O56', 'O57', 'O58', 'O59', 'O60', 'O61', 'O62', 'O63']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['K1', 'K1', 'K1', 'K1', 'Ca2', 'Ca2', 'Ca2', 'Ca2', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'O6', 'O6', 'O6', 'O6', 'O5', 'O5', 'O5', 'O5', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ca4', 'Ca5', 'Ca6', 'Ca7', 'Ca8', 'Ca9', 'Ca10', 'Ca11', 'Nb12', 'Nb12', 'Nb13', 'Nb13', 'Nb14', 'Nb14', 'Nb15', 'Nb15', 'Nb16', 'Nb16', 'Nb17', 'Nb17', 'Nb18', 'Nb18', 'Nb19', 'Nb19', 'Nb20', 'Nb20', 'Nb21', 'Nb21', 'Nb22', 'Nb22', 'Nb23', 'Nb23', 'K0', 'K1', 'K2', 'K3', 'O24', 'O25', 'O26', 'O27', 'O28', 'O29', 'O30', 'O31', 'O32', 'O33', 'O34', 'O35', 'O36', 'O37', 'O38', 'O39', 'O40', 'O41', 'O42', 'O43', 'O44', 'O45', 'O46', 'O47', 'O48', 'O49', 'O50', 'O51', 'O52', 'O53', 'O54', 'O55', 'O56', 'O57', 'O58', 'O59', 'O60', 'O61', 'O62', 'O63']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ca2', 'Ca2', 'Ca2', 'Ca2', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'K1', 'K1', 'K1', 'K1', 'O6', 'O6', 'O6', 'O6', 'O5', 'O5', 'O5', 'O5', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Cs1', 'Ba1', 'Ba1', 'Nb2', 'Nb2', 'Nb1', 'O4', 'O4', 'O3', 'O3', 'O3', 'O3', 'O2', 'O2', 'O1', 'O1']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Na0', 'Na1', 'Na2', 'Na3', 'La4', 'La5', 'La6', 'La7', 'Ti1', 'Ti1', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3']`.
  writer = CifWriter(structure)
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: No structure parsed for section 1 in CIF.
'_atom_site_label'
No _symmetry_equiv_pos_as_xyz type key found. Spacegroup from _symmetry_space_group_name_H-M used.
No _symmetry_equiv_pos_as_xyz type key found. Spacegroup from _symmetry_space_group_name_H-M used.
t parsed as T
No structure parsed for section 3 in CIF.
could not convert string to float: 't'
No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
t parsed as T
No structure parsed for section 4 in CIF.
could not convert string to float: 't'
  struct = parser.parse_structures(primitive=primitive)[0]
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['K1', 'K1', 'K1', 'K1', 'Nd1', 'Nd1', 'Nd1', 'Nd1', 'Ti1', 'Ti1', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O4', 'O4', 'O4', 'O4', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1']`.
  writer = CifWriter(structure)

ERROR: Invalid structure for  sd_1210175
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1614775

C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ca4', 'Ca4', 'Ca5', 'Ca5', 'Ca6', 'Ca6', 'Ca7', 'Ca7', 'Ca8', 'Ca8', 'Ca9', 'Ca9', 'Ca10', 'Ca10', 'Ca11', 'Ca11', 'Nb12', 'Nb13', 'Nb14', 'Nb15', 'Nb16', 'Nb17', 'Nb18', 'Nb19', 'Nb20', 'Nb21', 'Nb22', 'Nb23', 'K0', 'K1', 'K2', 'K3', 'O24', 'O25', 'O26', 'O27', 'O28', 'O29', 'O30', 'O31', 'O32', 'O33', 'O34', 'O35', 'O36', 'O37', 'O38', 'O39', 'O40', 'O41', 'O42', 'O43', 'O44', 'O45', 'O46', 'O47', 'O48', 'O49', 'O50', 'O51', 'O52', 'O53', 'O54', 'O55', 'O56', 'O57', 'O58', 'O59', 'O60', 'O61', 'O62', 'O63']`.
  writer = CifWriter(structure)
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\io\cif.py:1342: UserWarning: Missing elements K from PMG structure composition
  if struct := self._get_structure(data, primitive, symmetrized, check_occu=check_occu):

ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1925412

C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['La2', 'La3', 'K0', 'K0', 'K1', 'K1', 'Ti4', 'Ti5', 'Ti6', 'O7', 'O8', 'O9', 'O10', 'O11', 'O12', 'O13', 'O14', 'O15', 'O16']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['La2', 'La3', 'Ti4', 'Ti5', 'Ti6', 'K0', 'K0', 'K1', 'K1', 'O7', 'O8', 'O9', 'O10', 'O11', 'O12', 'O13', 'O14', 'O15', 'O16']`.
  writer = CifWriter(structure)
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: No structure parsed for section 1 in CIF.
'_atom_site_label'
No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
t parsed as T
No structure parsed for section 3 in CIF.
could not convert string to float: 't'
No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
t parsed as T
No structure parsed for section 4 in CIF.
could not convert string to float: 't'
  struct = parser.parse_structures(primitive=primitive)[0]
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Nd1', 'Nd1', 'Nd1', 'Nd1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Li1', 'Li1', 'Li1', 'Li1', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O4', 'O4', 'O4', 'O4']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Li1', 'Li1', 'Li1', 'Li1', 'Nd1', 'Nd1', 'Nd1', 'Nd1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O4', 'O4', 'O4', 'O4']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Na1', 'Na1', 'Na1', 'Na1', 'Nd1', 'Nd1', 'Nd1', 'Nd1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O1', 'O1', 'O1', 'O1', 'O3', 'O3', 'O3', 'O3', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['K1', 'K1', 'K1', 'K1', 'Nd1', 'Nd1', 'Nd2', 'Nd2', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Rb1', 'Nd1', 'Ta1', 'Ta1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O3']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['A25', 'A26', 'A27', 'A28', 'A13', 'A14', 'A15', 'A16', 'A33', 'A34', 'A35', 'A36', 'A37', 'A40', 'A41', 'A42', 'A64', 'A65', 'A66', 'A69', 'A70', 'A71', 'A35', 'A36', 'A37', 'A40', 'A41', 'A42', 'A122', 'A123', 'A124', 'A127', 'A128', 'A129', 'A39', 'A68', 'A39', 'A126', 'A38', 'A67', 'A38', 'A125', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A17', 'A18', 'A19', 'A20', 'A29', 'A30', 'A31', 'A32']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['A25', 'A26', 'A27', 'A28', 'A13', 'A14', 'A15', 'A16', 'A33', 'A34', 'A35', 'A36', 'A40', 'A41', 'A42', 'A64', 'A65', 'A69', 'A70', 'A71', 'A35', 'A36', 'A40', 'A41', 'A42', 'A122', 'A123', 'A127', 'A128', 'A129', 'A39', 'A68', 'A39', 'A126', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A17', 'A18', 'A19', 'A20', 'A29', 'A30', 'A31', 'A32', 'A38', 'A67', 'A38', 'A125']`.
  writer = CifWriter(structure)

ERROR: Invalid structure for  sd_1241787
ERROR: Invalid structure for  sd_1210175
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1241787
ERROR: Invalid structure for  sd_1210175
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1241787
ERROR: Invalid structure for  sd_1210175
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1241787
ERROR: Invalid structure for  sd_1210175
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1241787
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1925412
ERROR: Invalid structure for  sd_1241787

C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['La2', 'La3', 'Ti4', 'Ti5', 'Ti6', 'Na0', 'Na0', 'Na1', 'Na1', 'O7', 'O8', 'O9', 'O10', 'O11', 'O12', 'O13', 'O14', 'O15', 'O16']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['La2', 'La3', 'Ti4', 'Ti4', 'Ti5', 'Ti5', 'Ti6', 'Ti6', 'Na0', 'Na0', 'Na1', 'Na1', 'O7', 'O8', 'O9', 'O10', 'O11', 'O12', 'O13', 'O14', 'O15', 'O16']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['La8', 'La9', 'La10', 'La11', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Na', 'Na', 'Na', 'Na', 'Na', 'Na', 'Na', 'Na', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3']`.
  writer = CifWriter(structure)

ERROR: Invalid structure for  sd_1210175
ERROR: Invalid structure for  sd_1210175

e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: 4 fractional coordinates rounded to ideal values to avoid issues with finite precision.
No structure parsed for section 1 in CIF.
'_atom_site_label'
No _symmetry_equiv_pos_as_xyz type key found. Spacegroup from _symmetry_space_group_name_H-M used.
No _symmetry_equiv_pos_as_xyz type key found. Spacegroup from _symmetry_space_group_name_H-M used.
No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
  struct = parser.parse_structures(primitive=primitive)[0]
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Cd1', 'Cd1', 'S1', 'S1']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Zr1', 'Zr1', 'Zr1', 'Zr1', 'Zr1', 'Zr1', 'Zr1', 'Zr1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2656037478.py:16: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Nd1', 'Ta1', 'Ta1', 'Cs1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O3']`.
  writer = CifWriter(structure)

ERROR: Invalid structure for  sd_1925412

In [88]:
df.to_csv("dataset_cif_strings_generated.csv")

In [89]:
df= df[df["Promoter"] == "No promoter"]
df

,Unnamed: 0,Perovskite,Hill formula,Interlayer space composition,Class,"Bandgap, eV",Materials Project ID,COD_ID,Springer_ID,Z,...,Oxygen_count,Oxygen_concentration_manual,Oxygen_concentration_MP,Oxygen_concentration_COD,Oxygen_concentration_Springer,MP_packing_fraction,COD_packing_fraction,Springer_packing_fraction,Manual_packing_fraction,cif
0,0,K4Nb6O17,K4 Nb6 O17,NaN,K4Nb6O17,3.50,mp-560692,1001842,-1,4.0,...,17.0,0.038505,0.038482,0.040481,NaN,0.482644,0.507705,NaN,0.482925,# generated using pymatgen\ndata_K4Nb6O17\n_sy...
1,1,KLaNb2O7,K1 La1 Nb2 O7,NaN,HLaNb2O7,3.20,mp-1223501,1545643,-1,8.0,...,7.0,0.043434,0.040335,0.021337,NaN,0.484504,0.256300,NaN,0.521726,# generated using pymatgen\ndata_KLaNb2O7\n_sy...
2,2,RbLaNb2O7,Rb1 La1 Nb2 O7,NaN,HLaNb2O7,3.35,mp-553965,-1,-1,1.0,...,7.0,0.042204,0.040114,NaN,NaN,0.507344,NaN,NaN,0.533788,# generated using pymatgen\ndata_RbLaNb2O7\n_s...
3,3,CsLaNb2O7,Cs1 La1 Nb2 O7,NaN,HLaNb2O7,3.30,mp-553248,2004917,-1,1.0,...,7.0,0.041041,0.038958,0.041070,NaN,0.524329,0.552752,NaN,0.552364,# generated using pymatgen\ndata_CsLaNb2O7\n_s...
4,4,KCa2Nb3O10,K1 Ca2 Nb3 O10,NaN,KCa2Nb3O10,3.35,mp-557195,1521061,-1,8.0,...,10.0,0.045472,0.043255,0.045288,NaN,0.505552,0.529316,NaN,0.531466,# generated using pymatgen\ndata_KCa2Nb3O10\n_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,1067,LiNdNb2O7,Li1 Nd1 Nb2 O7,NaN,HLaNb2O7,3.58,-1,-1,sd_1150217,1.0,...,7.0,0.045922,NaN,NaN,0.040702,NaN,NaN,0.416415,0.469821,# generated using pymatgen\ndata_LiNdNb2O7\n_s...
715,1068,NaNdNb2O7,Na1 Nd1 Nb2 O7,NaN,HLaNb2O7,3.57,-1,-1,sd_1150217,1.0,...,7.0,0.045041,NaN,NaN,0.040702,NaN,NaN,0.436677,0.483225,# generated using pymatgen\ndata_NaNdNb2O7\n_s...
716,1069,RbNdNb2O7,Rb1 Nd1 Nb2 O7,NaN,HLaNb2O7,3.55,-1,-1,sd_1150217,1.0,...,7.0,0.042939,NaN,NaN,0.040702,NaN,NaN,0.510072,0.538106,# generated using pymatgen\ndata_RbNdNb2O7\n_s...
717,1070,CsNdNb2O7,Cs1 Nd1 Nb2 O7,NaN,HLaNb2O7,3.62,-1,-1,sd_1150217,1.0,...,7.0,0.042320,NaN,NaN,0.040702,NaN,NaN,0.543085,0.564668,# generated using pymatgen\ndata_CsNdNb2O7\n_s...
718,1071,TiO2,Ti1 O2,NaN,oxide,3.20,mp-1245098,1010942,-1,NaN,...,2.0,NaN,0.050730,0.061367,NaN,0.469004,0.567346,NaN,NaN,# generated using pymatgen\ndata_TiO2\n_symmet...

In [90]:
#df = df[df["Materials Project ID"].str.contains(r"^mp-",na=False)]

In [91]:
#df.to_excel("checkpoint_only_MP.xlsx", index=False)

# Clean my dataset from duplicates

In [92]:
df

,Unnamed: 0,Perovskite,Hill formula,Interlayer space composition,Class,"Bandgap, eV",Materials Project ID,COD_ID,Springer_ID,Z,...,Oxygen_count,Oxygen_concentration_manual,Oxygen_concentration_MP,Oxygen_concentration_COD,Oxygen_concentration_Springer,MP_packing_fraction,COD_packing_fraction,Springer_packing_fraction,Manual_packing_fraction,cif
0,0,K4Nb6O17,K4 Nb6 O17,NaN,K4Nb6O17,3.50,mp-560692,1001842,-1,4.0,...,17.0,0.038505,0.038482,0.040481,NaN,0.482644,0.507705,NaN,0.482925,# generated using pymatgen\ndata_K4Nb6O17\n_sy...
1,1,KLaNb2O7,K1 La1 Nb2 O7,NaN,HLaNb2O7,3.20,mp-1223501,1545643,-1,8.0,...,7.0,0.043434,0.040335,0.021337,NaN,0.484504,0.256300,NaN,0.521726,# generated using pymatgen\ndata_KLaNb2O7\n_sy...
2,2,RbLaNb2O7,Rb1 La1 Nb2 O7,NaN,HLaNb2O7,3.35,mp-553965,-1,-1,1.0,...,7.0,0.042204,0.040114,NaN,NaN,0.507344,NaN,NaN,0.533788,# generated using pymatgen\ndata_RbLaNb2O7\n_s...
3,3,CsLaNb2O7,Cs1 La1 Nb2 O7,NaN,HLaNb2O7,3.30,mp-553248,2004917,-1,1.0,...,7.0,0.041041,0.038958,0.041070,NaN,0.524329,0.552752,NaN,0.552364,# generated using pymatgen\ndata_CsLaNb2O7\n_s...
4,4,KCa2Nb3O10,K1 Ca2 Nb3 O10,NaN,KCa2Nb3O10,3.35,mp-557195,1521061,-1,8.0,...,10.0,0.045472,0.043255,0.045288,NaN,0.505552,0.529316,NaN,0.531466,# generated using pymatgen\ndata_KCa2Nb3O10\n_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,1067,LiNdNb2O7,Li1 Nd1 Nb2 O7,NaN,HLaNb2O7,3.58,-1,-1,sd_1150217,1.0,...,7.0,0.045922,NaN,NaN,0.040702,NaN,NaN,0.416415,0.469821,# generated using pymatgen\ndata_LiNdNb2O7\n_s...
715,1068,NaNdNb2O7,Na1 Nd1 Nb2 O7,NaN,HLaNb2O7,3.57,-1,-1,sd_1150217,1.0,...,7.0,0.045041,NaN,NaN,0.040702,NaN,NaN,0.436677,0.483225,# generated using pymatgen\ndata_NaNdNb2O7\n_s...
716,1069,RbNdNb2O7,Rb1 Nd1 Nb2 O7,NaN,HLaNb2O7,3.55,-1,-1,sd_1150217,1.0,...,7.0,0.042939,NaN,NaN,0.040702,NaN,NaN,0.510072,0.538106,# generated using pymatgen\ndata_RbNdNb2O7\n_s...
717,1070,CsNdNb2O7,Cs1 Nd1 Nb2 O7,NaN,HLaNb2O7,3.62,-1,-1,sd_1150217,1.0,...,7.0,0.042320,NaN,NaN,0.040702,NaN,NaN,0.543085,0.564668,# generated using pymatgen\ndata_CsNdNb2O7\n_s...
718,1071,TiO2,Ti1 O2,NaN,oxide,3.20,mp-1245098,1010942,-1,NaN,...,2.0,NaN,0.050730,0.061367,NaN,0.469004,0.567346,NaN,NaN,# generated using pymatgen\ndata_TiO2\n_symmet...

In [93]:
df['Alcohol_nonzero'] = df['Alcohol, %'].replace(0, np.nan)

C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2565595144.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Alcohol_nonzero'] = df['Alcohol, %'].replace(0, np.nan)

In [94]:
df = df[df['Alcohol_nonzero'].notna()]

In [95]:
idx = df.groupby('Materials Project ID')['Alcohol_nonzero'].idxmin()
idx

Materials Project ID
-1                   525
HCa2Ta3O10_BuNH2     601
HCa2Ta3O10_MeNH2     600
HCa2Ta3O10_OcNH2     602
HLaTiO4_BuNH2        448
HLaTiO4_BuOH         453
HLaTiO4_EtNH2        446
HLaTiO4_EtOH         451
HLaTiO4_HxNH2        449
HLaTiO4_HxOH         454
HLaTiO4_MeNH2        445
HLaTiO4_MeOH         450
HLaTiO4_PrNH2        447
HLaTiO4_PrOH         452
K2La2Ti3O10_BuNH2    535
K2La2Ti3O10_BuOH     541
K2La2Ti3O10_EtNH2    533
K2La2Ti3O10_EtOH     539
K2La2Ti3O10_HxNH2    536
K2La2Ti3O10_HxOH     542
K2La2Ti3O10_MeNH2    532
K2La2Ti3O10_MeOH     538
K2La2Ti3O10_OcNH2    629
K2La2Ti3O10_PrNH2    534
K2La2Ti3O10_PrOH     540
mp-10347             488
mp-1104930           694
mp-1179025           289
mp-1205881           275
mp-1222828           229
mp-1223501             1
mp-1223520           213
mp-1223975           430
mp-1245098           703
mp-20396               5
mp-23611              52
mp-23614              54
mp-27998              34
mp-4423              696
mp-505814            421
mp-541600             45
mp-553248              3
mp-553965              2
mp-554675             51
mp-555616             53
mp-555785            697
mp-555867             55
mp-556848             50
mp-557195            412
mp-560692             37
mp-581330              6
mp-6000              232
mp-6119              429
mp-6144              426
mp-6548              700
mp-775909            704
mp-9406              425
Name: Alcohol_nonzero, dtype: int64

In [96]:
df = df.loc[idx].copy()
df

,Unnamed: 0,Perovskite,Hill formula,Interlayer space composition,Class,"Bandgap, eV",Materials Project ID,COD_ID,Springer_ID,Z,...,Oxygen_concentration_manual,Oxygen_concentration_MP,Oxygen_concentration_COD,Oxygen_concentration_Springer,MP_packing_fraction,COD_packing_fraction,Springer_packing_fraction,Manual_packing_fraction,cif,Alcohol_nonzero
525,777,HNdTa2O7,H1 Nd1 Ta2 O7,NaN,HLaNb2O7,4.360000,-1,-1,sd_1955780,1.0,...,0.044141,NaN,NaN,0.046391,NaN,NaN,0.454380,0.432338,# generated using pymatgen\ndata_NdTa2HO7\n_sy...,0.10
601,903,HCa2Nb3O10*2C4H9NH2,H23 Ca2 Nb3 O10 C8 N2,NaN,KCa2Nb3O10,3.580000,HCa2Ta3O10_BuNH2,-1,-1,1.0,...,0.026527,0.021705,NaN,NaN,0.265534,NaN,NaN,0.324529,# generated using pymatgen\ndata_Ca2Nb3H24C8(N...,1.00
600,902,HCa2Nb3O10*2CH3NH2,H11 Ca2 Nb3 O10 C2 N2,NaN,KCa2Nb3O10,3.520000,HCa2Ta3O10_MeNH2,-1,-1,1.0,...,0.041423,0.030833,NaN,NaN,0.375123,NaN,NaN,0.503960,# generated using pymatgen\ndata_Ca2Nb3H12C2(N...,1.00
602,904,HCa2Nb3O10*2C8H17NH2,H39 Ca2 Nb3 O10 C16 N2,NaN,KCa2Nb3O10,3.520000,HCa2Ta3O10_OcNH2,-1,-1,1.0,...,0.019341,0.018411,NaN,NaN,0.226913,NaN,NaN,0.238370,# generated using pymatgen\ndata_Ca2Nb3H40C16(...,1.00
448,692,HLaTiO4*C4H9NH2,H12 La1 Ti1 O4 C4 N1,NaN,HLaTiO4,3.610000,HLaTiO4_BuNH2,-1,-1,4.0,...,0.023676,0.022345,NaN,NaN,0.290927,NaN,NaN,0.308260,# generated using pymatgen\ndata_LaTiH12C4NO4\...,1.00
453,698,HLaTiO4*C4H9OH,H11 La1 Ti1 O5 C4,NaN,HLaTiO4,3.450000,HLaTiO4_BuOH,-1,-1,4.0,...,0.031524,0.027931,NaN,NaN,0.283917,NaN,NaN,0.320439,# generated using pymatgen\ndata_LaTiH11C4O5\n...,1.00
446,690,HLaTiO4*C2H5NH2,H8 La1 Ti1 O4 C2 N1,NaN,HLaTiO4,3.480000,HLaTiO4_EtNH2,-1,-1,4.0,...,0.030503,0.028635,NaN,NaN,0.371203,NaN,NaN,0.395420,# generated using pymatgen\ndata_LaTiH8C2NO4\n...,1.00
451,696,HLaTiO4*C2H5OH,H7 La1 Ti1 O5 C2,NaN,HLaTiO4,3.470000,HLaTiO4_EtOH,-1,-1,4.0,...,0.039488,0.035794,NaN,NaN,0.362219,NaN,NaN,0.399597,# generated using pymatgen\ndata_LaTiH7C2O5\n_...,1.00
449,693,HLaTiO4*C6H13NH2,H16 La1 Ti1 O4 C6 N1,NaN,HLaTiO4,3.470000,HLaTiO4_HxNH2,-1,-1,4.0,...,0.020614,0.019455,NaN,NaN,0.254403,NaN,NaN,0.269561,# generated using pymatgen\ndata_LaTiH16C6NO4\...,1.00
454,699,HLaTiO4*C6H13OH,H15 La1 Ti1 O5 C6,NaN,HLaTiO4,3.460000,HLaTiO4_HxOH,-1,-1,4.0,...,0.025809,0.024319,NaN,NaN,0.248300,NaN,NaN,0.263514,# generated using pymatgen\ndata_LaTiH15C6O5\n...,1.00
445,689,HLaTiO4*CH3NH2,H6 La1 Ti1 O4 C1 N1,NaN,HLaTiO4,3.580000,HLaTiO4_MeNH2,-1,-1,4.0,...,0.033806,0.032075,NaN,NaN,0.414885,NaN,NaN,0.437274,# generated using pymatgen\ndata_LaTiH6CNO4\n_...,1.00
450,695,HLaTiO4*CH3OH,H5 La1 Ti1 O5 C1,NaN,HLaTiO4,3.470000,HLaTiO4_MeOH,-1,-1,4.0,...,0.044745,0.040094,NaN,NaN,0.404822,NaN,NaN,0.451782,# generated using pymatgen\ndata_LaTiH5CO5\n_s...,1.00
447,691,HLaTiO4*C3H8NH2,H11 La1 Ti1 O4 C3 N1,NaN,HLaTiO4,3.500000,HLaTiO4_PrNH2,-1,-1,4.0,...,0.027469,0.025925,NaN,NaN,0.336799,NaN,NaN,0.356865,# generated using pymatgen\ndata_LaTiH10C3NO4\...,1.00
452,697,HLaTiO4*C3H8OH,H10 La1 Ti1 O5 C3,NaN,HLaTiO4,3.450000,HLaTiO4_PrOH,-1,-1,4.0,...,0.034556,0.032406,NaN,NaN,0.328665,NaN,NaN,0.350468,# generated using pymatgen\ndata_LaTiH9C3O5\n_...,1.00
535,800,H2La2Ti3O10*2C4H9NH2,H24 La2 Ti3 O10 C8 N2,NaN,A2Ln2M3O10,3.420000,K2La2Ti3O10_BuNH2,-1,-1,1.0,...,0.027890,0.027271,NaN,NaN,0.334476,NaN,NaN,0.342069,# generated using pymatgen\ndata_La2Ti3H24C8(N...,1.00
541,806,H2La2Ti3O10*2C4H9OH,H22 La2 Ti3 O12 C8,NaN,A2Ln2M3O10,3.400000,K2La2Ti3O10_BuOH,-1,-1,2.0,...,0.033911,0.032725,NaN,NaN,0.327632,NaN,NaN,0.339502,# generated using pymatgen\ndata_La2Ti3H22(C2O...,1.00
533,798,H2La2Ti3O10*2C2H5NH2,H16 La2 Ti3 O10 C4 N2,NaN,A2Ln2M3O10,3.390000,K2La2Ti3O10_EtNH2,-1,-1,1.0,...,0.033925,0.033347,NaN,NaN,0.407479,NaN,NaN,0.414550,# generated using pymatgen\ndata_La2Ti3H16C4(N...,1.00
539,804,H2La2Ti3O10*2C2H5OH,H14 La2 Ti3 O12 C4,NaN,A2Ln2M3O10,3.410000,K2La2Ti3O10_EtOH,-1,-1,2.0,...,0.041421,0.040016,NaN,NaN,0.399109,NaN,NaN,0.413120,# generated using pymatgen\ndata_La2Ti3H14(CO3...,1.00
536,801,H2La2Ti3O10*2C6H13NH2,H32 La2 Ti3 O10 C12 N2,NaN,A2Ln2M3O10,3.410000,K2La2Ti3O10_HxNH2,-1,-1,1.0,...,0.022711,0.022912,NaN,NaN,0.282043,NaN,NaN,0.279570,# generated using pymatgen\ndata_La2Ti3H32C12(...,1.00
542,807,H2La2Ti3O10*2C6H13OH,H30 La2 Ti3 O12 C12,NaN,A2Ln2M3O10,3.400000,K2La2Ti3O10_HxOH,-1,-1,1.0,...,0.028163,0.027494,NaN,NaN,0.276292,NaN,NaN,0.283012,# generated using pymatgen\ndata_La2Ti3H30(CO)...,1.00
532,797,H2La2Ti3O10*2CH3NH2,H12 La2 Ti3 O10 C2 N2,NaN,A2Ln2M3O10,3.340000,K2La2Ti3O10_MeNH2,-1,-1,2.0,...,0.037151,0.045238,NaN,NaN,0.551768,NaN,NaN,0.453123,# generated using pymatgen\ndata_La2Ti3H12C2(N...,1.00
538,803,H2La2Ti3O10*2CH3OH,H10 La2 Ti3 O12 C2,NaN,A2Ln2M3O10,3.330000,K2La2Ti3O10_MeOH,-1,-1,2.0,...,0.047104,0.054286,NaN,NaN,0.540414,NaN,NaN,0.468913,# generated using pymatgen\ndata_La2Ti3H10(CO6...,1.00
629,938,H2La2Ti3O10*2C8H17NH2,H40 La2 Ti3 O10 C16 N2,NaN,A2Ln2M3O10,3.400000,K2La2Ti3O10_OcNH2,-1,-1,2.0,...,0.039497,0.019696,NaN,NaN,0.243349,NaN,NaN,0.487996,# generated using pymatgen\ndata_La2Ti3H40C16(...,0.10
534,799,H2La2Ti3O10*2C3H8NH2,H22 La2 Ti3 O10 C6 N2,NaN,A2Ln2M3O10,3.400000,K2La2Ti3O10_PrNH2,-1,-1,1.0,...,0.031580,0.015521,NaN,NaN,0.190007,NaN,NaN,0.386609,# generated using pymatgen\ndata_La4Ti6H39C12(...,1.00
540,805,H2La2Ti3O10*2C3H8OH,H20 La2 Ti3 O12 C6,NaN,A2Ln2M3O10,3.380000,K2La2Ti3O10_PrOH,-1,-1,2.0,...,0.037016,0.018625,NaN,NaN,0.186112,NaN,NaN,0.369890,# generated using pymatgen\ndata_La4Ti6H35(CO2...,1.00
488,740,HSr2Nb3O10,H1 Sr2 Nb3 O10,NaN,KCa2Nb3O10,3.260000,mp-10347,1522043,-1,1.0,...,0.040296,0.041300,0.043865,NaN,0.450271,0.478233,NaN,0.439315,# generated using pymatgen\ndata_Sr2Nb3HO10\n_...,1.00
694,1047,HLaTiO4,H1 La1 Ti1 O4,NaN,HLaTiO4,3.433333,mp-1104930,-1,sd_0304039,2.0,...,0.047038,0.039254,NaN,0.079909,0.412091,NaN,0.838885,0.493808,# generated using pymatgen\ndata_LaTiHO4\n_sym...,0.10
289,411,Bi4Ti3O12,Bi4 Ti3 O12,NaN,NaN,3.080000,mp-1179025,1528445,-1,NaN,...,NaN,0.047807,0.049597,NaN,0.528189,0.547970,NaN,NaN,# generated using pymatgen\ndata_Ti3(BiO3)4\n_...,4.76
275,395,HLaNb2O7,H1 La1 Nb2 O7,NaN,HLaNb2O7,3.360000,mp-1205881,-1,-1,1.0,...,0.043945,0.042253,NaN,NaN,0.418749,NaN,NaN,0.435514,# generated using pymatgen\ndata_LaNb2HO7\n_sy...,10.00
229,316,AgLaNb2O7,Ag1 La1 Nb2 O7,NaN,HLaNb2O7,2.960000,mp-1222828,1509430,-1,2.0,...,0.042413,0.041242,0.042449,NaN,0.461705,0.475218,NaN,0.474812,# generated using pymatgen\ndata_LaNb2AgO7\n_s...,20.00
1,1,KLaNb2O7,K1 La1 Nb2 O7,NaN,HLaNb2O7,3.200000,mp-1223501,1545643,-1,8.0,...,0.043434,0.040335,0.021337,NaN,0.484504,0.256300,NaN,0.521726,# generated using pymatgen\ndata_KLaNb2O7\n_sy...,14.30
213,298,HCa2Nb3O10,H1 Ca2 Nb3 O10,NaN,KCa2Nb3O10,3.750000,mp-1223520,1522039,-1,2.0,...,0.046455,0.042510,0.045106,NaN,0.434307,0.460834,NaN,0.474617,# generated using pymatgen\ndata_Ca2Nb3HO10\n_...,10.00
430,632,K2Nd2Ti3O10,K2 Nd2 Ti3 O10,NaN,A2Ln2M3O10,3.300000,mp-1223975,2007573,-1,NaN,...,NaN,0.043899,0.045291,NaN,0.571888,0.590018,NaN,NaN,# generated using pymatgen\ndata_K2Nd2Ti3O10\n...,1.00
703,1056,TiO2,Ti1 O2,NaN,oxide,3.200000,mp-1245098,1010942,-1,NaN,...,NaN,0.050730,0.061367,NaN,0.469004,0.567346,NaN,NaN,# generated using pymatgen\ndata_TiO2\n_symmet...,0.10
5,5,RbCa2Nb3O10,Rb1 Ca2 Nb3 O10,NaN,KCa2Nb3O10,3.500000,mp-20396,2238958,-1,4.0,...,0.044959,0.041596,0.045043,NaN,0.504677,0.546497,NaN,0.545473,# generated using pymatgen\ndata_RbCa2Nb3O10\n...,14.30
52,60,BaBi2Ta2O9,Ba1 Bi2 Ta2 O9,NaN,NaN,3.520000,mp-23611,1525921,-1,NaN,...,NaN,0.045235,0.022727,NaN,0.536095,0.269341,NaN,NaN,# generated using pymatgen\ndata_BaTa2Bi2O9\n_...,12.50
54,62,SrBi2Nb2O9,Sr1 Bi2 Nb2 O9,NaN,NaN,3.430000,mp-23614,1531753,-1,4.0,...,0.047545,0.044109,0.047500,NaN,0.502056,0.540650,NaN,0.541172,# generated using pymatgen\ndata_SrNb2Bi2O9\n_...,12.50
34,39,K2Nb6O16,K1 Nb3 O8,NaN,NaN,NaN,mp-27998,-1,-1,NaN,...,NaN,0.043280,NaN,NaN,0.474496,NaN,NaN,NaN,# generated using pymatgen\ndata_KNb3O8\n_symm...,20.00
696,1049,La2Ti2O7*0.76H2O,La2 Ti2 O7.76 H1.52,NaN,La2Ti2O7,3.780000,mp-4423,1001022,-1,2.0,...,0.045325,0.053826,0.055776,NaN,0.568597,0.589191,NaN,0.478791,# generated using pymatgen\ndata_La2Ti2O7\n_sy...,0.10
421,610,CsBa2Nb3O10,Cs1 Ba2 Nb3 O10,NaN,KCa2Nb3O10,2.800000,mp-505814,1526807,-1,1.0,...,0.040776,0.038334,0.040591,NaN,0.545511,0.577636,NaN,0.580273,# generated using pymatgen\ndata_CsBa2Nb3O10\n...,1.00
45,50,RbLaTa2O7,Rb1 La1 Ta2 O7,NaN,HLaNb2O7,3.900000,mp-541600,-1,sd_1050391,1.0,...,0.041707,0.040460,NaN,0.042542,0.511722,NaN,0.538063,0.527499,# generated using pymatgen\ndata_RbLaTa2O7\n_s...,16.00
3,3,CsLaNb2O7,Cs1 La1 Nb2 O7,NaN,HLaNb2O7,3.300000,mp-553248,2004917,-1,1.0,...,0.041041,0.038958,0.041070,NaN,0.524329,0.552752,NaN,0.552364,# generated using pymatgen\ndata_CsLaNb2O7\n_s...,14.30
2,2,RbLaNb2O7,Rb1 La1 Nb2 O7,NaN,HLaNb2O7,3.350000,mp-553965,-1,-1,1.0,...,0.042204,0.040114,NaN,NaN,0.507344,NaN,NaN,0.533788,# generated using pymatgen\ndata_RbLaNb2O7\n_s...,14.30
51,59,SrBi2Ta2O9,Sr1 Bi2 Ta2 O9,NaN,NaN,3.640000,mp-554675,1521923,-1,4.0,...,0.047545,0.046146,0.047154,NaN,0.525246,0.536716,NaN,0.541172,# generated using pymatgen\ndata_SrTa2Bi2O9\n_...,12.50
53,61,CaBi2Nb2O9,Ca1 Bi2 Nb2 O9,NaN,NaN,3.460000,mp-555616,-1,-1,NaN,...,NaN,0.043215,NaN,NaN,0.475416,NaN,NaN,NaN,# generated using pymatgen\ndata_CaNb2Bi2O9\n_...,12.50
697,1050,Nd2Ti2O7*0.71H2O,Nd2 Ti2 O7.71 H1.42,NaN,La2Ti2O7,3.650000,mp-555785,2002197,-1,2.0,...,0.046971,0.056392,0.057223,NaN,0.584640,0.593252,NaN,0.486966,# generated using pymatgen\ndata_Nd2Ti2O7\n_sy...,0.10
55,63,BaBi2Nb2O9,Ba1 Bi2 Nb2 O9,NaN,NaN,3.300000,mp-555867,7221049,-1,NaN,...,NaN,0.042869,0.045253,NaN,0.508060,0.536303,NaN,NaN,# generated using pymatgen\ndata_BaNb2Bi2O9\n_...,12.50
50,58,CaBi2Ta2O9,Ca1 Bi2 Ta2 O9,NaN,NaN,3.670000,mp-556848,1525923,-1,2.0,...,0.024335,0.047563,0.048576,NaN,0.523257,0.534395,NaN,0.267712,# generated using pymatgen\ndata_CaTa2Bi2O9\n_...,12.50
412,601,KCa2Nb2.97Rh0.03O10,K1 Ca2 Nb2.97 Rh0.03 O10,NaN,KCa2Nb3O10,NaN,mp-557195,1521061,-1,NaN,...,NaN,0.010814,0.011322,NaN,0.126394,0.132336,NaN,NaN,# generated using pymatgen\ndata_K4Ca8Nb11.88R...,10.00
37,42,K4Nb6O17,K4 Nb6 O17,NaN,K4Nb6O17,3.300000,mp-560692,1001842,-1,4.0,...,0.038505,0.038482,0.040481,NaN,0.482644,0.507705,NaN,0.482925,# generated using pymatgen\ndata_K4Nb6O17\n_sy...,3.00
6,6,CsCa2Nb3O10,Cs1 Ca2 Nb3 O10,NaN,KCa2Nb3O10,3.500000,mp-581330,1518045,-1,2.0,...,0.011101,0.042051,0.044206,NaN,0.534073,0.561438,NaN,0.140983,# generated using pymatgen\ndata_CsCa2Nb3O10\n...,14.30
232,322,Ag2La2Ti3O10,Ag2 La2 Ti3 O10,NaN,A2Ln2M3O10,2.650000,mp-6000,1509663,-1,2.0,...,0.047190,0.045781,0.047325,NaN,0.551467,0.570064,NaN,0.568439,# generated using pymatgen\ndata_La2Ti3(AgO5)2...,20.00
429,631,Na2Nd2Ti3O10,Na2 Nd2 Ti3 O10,NaN,A2Ln2M3O10,3.400000,mp-6119,-1,-1,NaN,...,NaN,0.046873,NaN,NaN,0.534019,NaN,NaN,NaN,# generated using pymatgen\ndata_Na2Nd2Ti3O10\...,1.00
426,628,Na2La2Ti3O10,Na2 La2 Ti3 O10,NaN,A2Ln2M3O10,3.300000,mp-6144,1544433,sd_1210175,2.0,...,0.048598,0.046209,0.047585,NaN,0.533951,0.549847,NaN,0.561553,# generated using pymatgen\ndata_Na2La2Ti3O10\...,1.00
700,1053,HRbNd2Ti3O10,H1 Rb1 Nd2 Ti3 O10,NaN,A2Ln2M3O10,3.540000,mp-6548,-1,-1,2.0,...,0.051461,0.043497,NaN,NaN,0.522018,NaN,NaN,0.617599,# generated using pymatgen\ndata_RbNd2Ti3HO10\...,0.10
704,1057,ZrO2,Zr1 O2,NaN,oxide,5.100000,mp-775909,-1,sd_0560284,NaN,...,NaN,NaN,NaN,0.063025,NaN,NaN,0.612060,NaN,# generated using pymatgen\ndata_ZrO2\n_symmet...,0.10
425,627,Li2La2Ti3O10,Li2 La2 Ti3 O10,NaN,A2Ln2M3O10,3.500000,mp-9406,-1,-1,NaN,...,NaN,0.049729,NaN,NaN,0.539970,NaN,NaN,NaN,# generated using pymatgen\ndata_Li2La2Ti3O10\...,1.00

In [97]:
idx

Materials Project ID
-1                   525
HCa2Ta3O10_BuNH2     601
HCa2Ta3O10_MeNH2     600
HCa2Ta3O10_OcNH2     602
HLaTiO4_BuNH2        448
HLaTiO4_BuOH         453
HLaTiO4_EtNH2        446
HLaTiO4_EtOH         451
HLaTiO4_HxNH2        449
HLaTiO4_HxOH         454
HLaTiO4_MeNH2        445
HLaTiO4_MeOH         450
HLaTiO4_PrNH2        447
HLaTiO4_PrOH         452
K2La2Ti3O10_BuNH2    535
K2La2Ti3O10_BuOH     541
K2La2Ti3O10_EtNH2    533
K2La2Ti3O10_EtOH     539
K2La2Ti3O10_HxNH2    536
K2La2Ti3O10_HxOH     542
K2La2Ti3O10_MeNH2    532
K2La2Ti3O10_MeOH     538
K2La2Ti3O10_OcNH2    629
K2La2Ti3O10_PrNH2    534
K2La2Ti3O10_PrOH     540
mp-10347             488
mp-1104930           694
mp-1179025           289
mp-1205881           275
mp-1222828           229
mp-1223501             1
mp-1223520           213
mp-1223975           430
mp-1245098           703
mp-20396               5
mp-23611              52
mp-23614              54
mp-27998              34
mp-4423              696
mp-505814            421
mp-541600             45
mp-553248              3
mp-553965              2
mp-554675             51
mp-555616             53
mp-555785            697
mp-555867             55
mp-556848             50
mp-557195            412
mp-560692             37
mp-581330              6
mp-6000              232
mp-6119              429
mp-6144              426
mp-6548              700
mp-775909            704
mp-9406              425
Name: Alcohol_nonzero, dtype: int64

In [98]:
df['Rate_standardized'] = df['Rate, umol/(g*h)'] / (df['Alcohol, %']*df['CatW, g/L']*df["Power, W"])

In [99]:
df["Log_rate_standardized"] = np.log(df['Rate_standardized'])

In [100]:
df.to_excel("pre_dataset_for_fine_tuning.xlsx", index=False)

In [101]:
df.shape[0]

57

# Changing mattergen datasets

In [102]:
/0

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\1350904145.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  0()

TypeError: 'int' object is not callable

In [103]:
def add_value_to_dataset_MP(MP_ID):
    row = df[df['Materials Project ID'] == MP_ID]
    if row.empty:
        return np.nan
    else:
        return row['Log_rate_standardized'].values[0]

In [104]:
if not extend_mattergen_dataset:
    names = ["train.csv"]
    for name in names:
        df_mattergen_set = pd.read_csv("Data/Mattergen_dataset/init/"+name)
        print(name + ": " + str(df_mattergen_set.shape[0]))
        df_mattergen_set["Log_rate"] = df_mattergen_set["material_id"].apply(add_value_to_dataset)
        #df_mattergen_set = df_mattergen_set[df_mattergen_set["Log_rate"].notna()]
        print(name + ": " + str(df_mattergen_set.shape[0]))
        df_mattergen_set.to_csv("Data/Mattergen_dataset/processed/"+name, index=False)

In [105]:
print(get_cif_string_from_id("mp-6144"))

# generated using pymatgen
data_Na2La2Ti3O10
_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   14.69641334
_cell_length_b   14.69641334
_cell_length_c   14.69641334
_cell_angle_alpha   164.86303529
_cell_angle_beta   164.86303529
_cell_angle_gamma   21.47009583
_symmetry_Int_Tables_number   1
_chemical_formula_structural   Na2La2Ti3O10
_chemical_formula_sum   'Na2 La2 Ti3 O10'
_cell_volume   216.40687731
_cell_formula_units_Z   1
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  Na  Na0  1  0.71177800  0.71177800  0.00000000  1.0
  Na  Na1  1  0.28822200  0.28822200  0.00000000  1.0
  La  La2  1  0.57527700  0.57527700  0.00000000  1.0
  La  La3  1  0.42472300  0.42472300  0.00000000  1.0
  Ti  Ti4  1  0.85219600  0.85219600  0.00000000  1.0
  Ti  Ti5  1  0.14780400  0.14780400  0.00000000  1.0
  Ti  Ti6  1  0.00000000  0.00000000  0.00000000  1.0
  O  O7  1  0.36674700  0.86674700  0.50000000  1.0
  O  O8  1  0.86674700  0.36674700  0.50000000  1.0
  O  O9  1  0.63325300  0.13325300  0.50000000  1.0
  O  O10  1  0.13325300  0.63325300  0.50000000  1.0
  O  O11  1  0.79138100  0.79138100  0.00000000  1.0
  O  O12  1  0.20861900  0.20861900  0.00000000  1.0
  O  O13  1  0.50000000  0.00000000  0.50000000  1.0
  O  O14  1  0.06734300  0.06734300  0.00000000  1.0
  O  O15  1  0.93265700  0.93265700  0.00000000  1.0
  O  O16  1  0.00000000  0.50000000  0.50000000  1.0

In [106]:
def get_material_data_from_id(MP_ID):
    output = {}
    with MPRester(API_KEY) as mpr:
        data = mpr.summary.get_data_by_id(MP_ID)
        #print(f"Formula: {data.formula_pretty}")
        #print(f"Formation Energy: {data.formation_energy_per_atom} eV/atom")
        #print(f"Band Gap: {data.band_gap}")
        #print(f"Formula: {data.formula_pretty}")
        #try:
        #    #print(f"e_above_hull: {data.e_above_hull}")
        #except:
            #print("e_above_hull data not available") 
        elements = data.elements
        element_labels = [el.symbol for el in elements]
        #print(f"Elements: {element_labels}")
        #print(f"Space Group: {data.symmetry.number}")
        #************************
        #************************
        output["pretty_formula"] = data.formula_pretty
        output["formation_energy_per_atom"] = data.formation_energy_per_atom
        output["dft_band_gap"] = data.band_gap
        output["e_above_hull"] = data.e_above_hull if hasattr(data, 'e_above_hull') else None
        output["elements"] = element_labels
        output["spacegroup_number"] = data.symmetry.number
    return output

In [107]:
get_material_data_from_id("mp-6144")

C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2937985821.py:4: DeprecationWarning: Accessing summary data through MPRester.summary is deprecated. Please use MPRester.materials.summary instead.
  data = mpr.summary.get_data_by_id(MP_ID)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_21016\2937985821.py:4: DeprecationWarning: get_data_by_id is deprecated and will be removed soon. Please use the search method instead.
  data = mpr.summary.get_data_by_id(MP_ID)
Retrieving SummaryDoc documents: 100%|██████████| 1/1 [00:00<00:00, 10082.46it/s]

{'pretty_formula': 'Na2La2Ti3O10',
 'formation_energy_per_atom': -3.412753374868154,
 'dft_band_gap': 1.7671000000000001,
 'e_above_hull': None,
 'elements': ['La', 'Na', 'O', 'Ti'],
 'spacegroup_number': 139}

In [ ]:
added = 0
replaced = 0

In [ ]:
def add_extend_value_to_mattergen_dataset(mattergen_dataset, MP_ID, Log_rate):
    global added, replaced
    #print(my_row)
    #MP_ID = my_row['Materials Project ID']
    #Log_rate =  my_row['Log_rate']
    #print("MP_ID: ",MP_ID)
    #print("Log_rate: ",Log_rate)
    is_present = MP_ID in mattergen_dataset['material_id'].values
    #print("MP_ID is in dataset: ",is_present)
    if(is_present):
        with open("dataset_extension_log.txt", "a") as file:
            file.write(f"MP_ID: {MP_ID}, Action: replaced\n")
        mattergen_dataset.loc[mattergen_dataset['material_id'] == MP_ID, 'Log_rate'] = Log_rate
        mattergen_dataset.loc[mattergen_dataset['material_id'] == MP_ID, 'Action'] = "replaced"
        replaced = replaced + 1
    else:
        with open("dataset_extension_log.txt", "a") as file:
            file.write("MP_ID: ", MP_ID , ", Action: added\n")
        new_row = {'material_id': MP_ID, 'Log_rate': Log_rate, 'Action':"added"}
        additional_info = get_material_data_from_id(MP_ID)
        new_row.update(additional_info)
        #mattergen_dataset.loc[len(mattergen_dataset)] = new_row
        new_row_df = pd.DataFrame([new_row])
        print(mattergen_dataset.shape[0])
        print(new_row_df.shape[0])
        mattergen_dataset = pd.concat([mattergen_dataset, new_row_df], ignore_index=True)
        print(mattergen_dataset.shape[0])
        added = added + 1
    return mattergen_dataset

In [ ]:
if (extend_mattergen_dataset):
    names = ["train.csv"]
    #names = ["val.csv"]
    with open("dataset_extension_log.txt", "w") as file:
            file.write("***********************************************\n")
    for name in names:
        with open("dataset_extension_log.txt", "a") as file:
            file.write("***********************************************\n")
        df_mattergen_set = pd.read_csv("Data/Mattergen_dataset/init/"+name)

        #print(name + ": " + str(df_mattergen_set.shape[0]))

        my_count = 0
        for row in df.to_dict('records'):
            mp_id = row['Materials Project ID']
            log_rate = row['Log_rate']
            df_mattergen_set = add_extend_value_to_mattergen_dataset(df_mattergen_set, mp_id, log_rate)
            my_count += 1
        #print(name + ": " + str(df_mattergen_set.shape[0]))
        df_mattergen_set = df_mattergen_set.dropna(subset=['Log_rate'])
        #print(name + ": " + str(df_mattergen_set.shape[0]))
        df_mattergen_set["cif"]=df_mattergen_set["material_id"].apply(get_cif_string_from_id)
        df_mattergen_set.to_csv("Data/Mattergen_dataset/processed/"+name, index=False)
        print(f"File: {name}, Added: {added}, Replaced: {replaced}, My count: {my_count}")
        added = 0
        replaced = 0

    #for row in df.itertuples():
    #    MP_ID = getattr(row, 'Materials_Project_ID') 
    #    Log_rate = getattr(row, 'Log_rate') 
    #    print("MP_ID: ", MP_ID)
    #    print("Log_rate: ", Log_rate)
    #    add_extend_value_to_mattergen_dataset(df_mattergen_set,MP_ID,Log_rate)

TypeError: TextIOWrapper.write() takes exactly one argument (3 given)

In [ ]:
name = "train"
df_ = pd.read_csv(f"Data/Mattergen_dataset/processed/{name}.csv")
df_

,Unnamed: 0,material_id,formation_energy_per_atom,dft_band_gap,pretty_formula,e_above_hull,elements,cif,spacegroup_number,azure_bulk_modulus,larsen_score_2d,Si_100_mismatch,azure_band_gap,dft_bulk_modulus,dft_poisson_ratio,dft_mag_density,Log_rate
0,0.0,mp-6144,-3.415012,2.0830,Na2La2Ti3O10,0.012505,"['La', 'Na', 'O', 'Ti']",# generated using pymatgen\ndata_Na2La2Ti3O10\...,139.0,119.400684,7.515893e-03,0.003792,2.113394,NaN,NaN,1.280000e-05,4.605170
1,1.0,mp-1222828,-2.894919,1.2000,LaNb2AgO7,0.064722,"['Ag', 'La', 'Nb', 'O']",# generated using pymatgen\ndata_LaNb2AgO7\n_s...,119.0,140.181002,7.770000e-16,0.004277,1.123539,NaN,NaN,6.380000e-06,5.337538
2,2.0,mp-541600,-3.383709,2.3257,RbLaTa2O7,0.021469,"['La', 'O', 'Rb', 'Ta']",# generated using pymatgen\ndata_RbLaTa2O7\n_s...,123.0,97.102628,3.430501e-01,0.008662,2.345044,NaN,NaN,4.330000e-07,2.740840
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_ = df_.iloc[:3, :]
df_

,Unnamed: 0,material_id,formation_energy_per_atom,dft_band_gap,pretty_formula,e_above_hull,elements,cif,spacegroup_number,azure_bulk_modulus,larsen_score_2d,Si_100_mismatch,azure_band_gap,dft_bulk_modulus,dft_poisson_ratio,dft_mag_density,Log_rate
0,0.0,mp-6144,-3.415012,2.0830,Na2La2Ti3O10,0.012505,"['La', 'Na', 'O', 'Ti']",# generated using pymatgen\ndata_Na2La2Ti3O10\...,139.0,119.400684,7.515893e-03,0.003792,2.113394,NaN,NaN,1.280000e-05,4.605170
1,1.0,mp-1222828,-2.894919,1.2000,LaNb2AgO7,0.064722,"['Ag', 'La', 'Nb', 'O']",# generated using pymatgen\ndata_LaNb2AgO7\n_s...,119.0,140.181002,7.770000e-16,0.004277,1.123539,NaN,NaN,6.380000e-06,5.337538
2,2.0,mp-541600,-3.383709,2.3257,RbLaTa2O7,0.021469,"['La', 'O', 'Rb', 'Ta']",# generated using pymatgen\ndata_RbLaTa2O7\n_s...,123.0,97.102628,3.430501e-01,0.008662,2.345044,NaN,NaN,4.330000e-07,2.740840

In [ ]:
df_.to_csv(f"Data/Mattergen_dataset/processed/{name}.csv")