In [1]:
from pymatgen.core import Lattice, Structure
import pandas as pd
import numpy as np
import plotly as pt
import seaborn as sns
#!pip install pymatgen
#!pip install mp_api
import requests
import json
import matplotlib.pyplot as plt

In [2]:
root_folder = ""
#data_folder = "Data/" #"/content/drive/MyDrive/University/Artificial intelligence in chemistry/Perovskite project/Perovskite-liked-oxides-bandgap-prediction/Data/"
cif_folder = "Data/CIF/"
#input_dataset_path = "checkpoint_cif_embeddings_split.xlsx"
#input_dataset_path = "checkpoint_cif_embeddings_split_merged.xlsx"
#input_dataset_path = "Data/Perovskite dataset export.xlsx"
#input_dataset_path = "Mattergen dataset generation IO/dataset_1.xlsx"
input_dataset_path = "Mattergen dataset generation IO/dataset_merged.xlsx"
extend_mattergen_dataset = True
No_promoter = True

In [3]:
df = pd.read_excel(input_dataset_path)
#df = pd.read_excel(input_dataset_path, sheet_name='Photocatalytic dataset')

In [4]:
df

,Unnamed: 0,Perovskite,Hill formula,Interlayer space composition,Class,"Bandgap, eV",Materials Project ID,COD_ID,Springer_ID,Z,...,Valence Electrons Density_manual,Oxygen_count,Oxygen_concentration_manual,Oxygen_concentration_MP,Oxygen_concentration_COD,Oxygen_concentration_Springer,MP_packing_fraction,COD_packing_fraction,Springer_packing_fraction,Manual_packing_fraction
0,0,K4Nb6O17,K4 Nb6 O17,NaN,K4Nb6O17,3.50,mp-560692,1001842,-1,4.0,...,0.077010,17,0.038505,0.038482,0.040481,NaN,0.482644,0.507705,NaN,0.482925
1,1,KLaNb2O7,K1 La1 Nb2 O7,NaN,HLaNb2O7,3.20,mp-1223501,1545643,-1,8.0,...,0.086868,7,0.043434,0.040335,0.021337,NaN,0.484504,0.256300,NaN,0.521726
2,2,RbLaNb2O7,Rb1 La1 Nb2 O7,NaN,HLaNb2O7,3.35,mp-553965,-1,-1,1.0,...,0.084409,7,0.042204,0.040114,NaN,NaN,0.507344,NaN,NaN,0.533788
3,3,CsLaNb2O7,Cs1 La1 Nb2 O7,NaN,HLaNb2O7,3.30,mp-553248,2004917,-1,1.0,...,0.082082,7,0.041041,0.038958,0.041070,NaN,0.524329,0.552752,NaN,0.552364
4,4,KCa2Nb3O10,K1 Ca2 Nb3 O10,NaN,KCa2Nb3O10,3.35,mp-557195,1521061,-1,8.0,...,0.090945,10,0.045472,0.043255,0.045288,NaN,0.505552,0.529316,NaN,0.531466
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,1268,Na2ZrTi5O13,Na2 Zr1 Ti5 O13,NaN,NaN,3.61,mp-5449,4000748,-1,NaN,...,NaN,13,NaN,0.050630,0.050746,NaN,0.519266,0.520454,NaN,NaN
964,1269,LaFeO3,La1 Fe1 O3,NaN,NaN,2.20,mp-1078634,1526450,-1,NaN,...,NaN,3,NaN,0.051970,0.049538,NaN,0.608789,0.580299,NaN,NaN
965,1270,LaFe0.85Ti0.15O3,La1 Fe0.85 Ti0.15 O3,NaN,NaN,2.10,mp-1078634,1526450,-1,NaN,...,NaN,3,NaN,0.025985,0.012385,NaN,0.302407,0.144128,NaN,NaN
966,1271,La0.85Sr0.15FeO3,La0.85 Sr0.15 Fe1 O3,NaN,NaN,1.50,mp-1078634,1526450,-1,NaN,...,NaN,3,NaN,0.025985,0.012385,NaN,0.308150,0.146865,NaN,NaN
967,1272,SrTiO3,Sr1 Ti1 O3,NaN,NaN,3.40,mp-4651,1512124,-1,NaN,...,NaN,3,NaN,0.050157,0.050613,NaN,0.610300,0.615851,NaN,NaN

In [5]:
df['Perovskite'].nunique()

337

In [6]:
df = df.dropna(subset=['Log_rate'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 968 entries, 0 to 967
Data columns (total 84 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Unnamed: 0                          968 non-null    int64
 1   Perovskite                          968 non-null    object
 2   Hill formula                        968 non-null    object
 3   Interlayer space composition        4 non-null      object
 4   Class                               510 non-null    object
 5   Bandgap, eV                         885 non-null    float64
 6   Materials Project ID                968 non-null    object
 7   COD_ID                              968 non-null    int64
 8   Springer_ID                         968 non-null    object
 9   Z                                   407 non-null    float64
 10  a, A                                415 non-null    float64
 11  b, A                                414 non-null    float64
 12  c, A                                414 non-null    float64
 13  Symmetry group                      290 non-null    object
 14  d,A                                 502 non-null    float64
 15  Number of octahedrons on a layer    96 non-null     float64
 16  Prep Method                         968 non-null    object
 17  CalcT(K)                            897 non-null    float64
 18  Calc time (h)                       847 non-null    float64
 19  Nitrogen                            968 non-null    int64
 20  Promotion method                    968 non-null    object
 21  Promoter                            968 non-null    object
 22  Promoter, w%                        968 non-null    float64
 23  Surface area, m2/g                  583 non-null    float64
 24  CatW, g/L                           967 non-null    float64
 25  Alcohol, %                          962 non-null    float64
 26  Sac Agent 1                         0 non-null      float64
 27  Sac agent 2                         0 non-null      float64
 28  Light type                          968 non-null    object
 29  Power, W                            962 non-null    float64
 30  Wave length min, nm                 706 non-null    float64
 31  Cell material                       968 non-null    object
 32  Temperature, K                      334 non-null    float64
 33  Rate, umol/(g*h)                    968 non-null    float64
 34  MP_CIF_modifier                     442 non-null    object
 35  COD_CIF_modifier                    232 non-null    object
 36  Springer_CIF_modifier               85 non-null     object
 37  Materials Project verification      968 non-null    bool
 38  COD verification                    968 non-null    bool
 39  Springer verification               968 non-null    bool
 40  General verification                968 non-null    bool
 41  MP_CIF_modified                     954 non-null    object
 42  COD_CIF_modified                    871 non-null    object
 43  Springer_CIF_modified               162 non-null    object
 44  Log_rate                            968 non-null    float64
 45  avg s valence electrons             968 non-null    float64
 46  avg p valence electrons             968 non-null    float64
 47  avg d valence electrons             968 non-null    float64
 48  avg f valence electrons             968 non-null    float64
 49  frac s valence electrons            968 non-null    float64
 50  frac p valence electrons            968 non-null    float64
 51  frac d valence electrons            968 non-null    float64
 52  frac f valence electrons            968 non-null    float64
 53  Average Mulliken electronegativity  968 non-null    float64
 54  Valence electrons                   968 non-null    int64
 55  Volume_MP                           968 non-null    float64
 56  Z_MP                                968 non-null    int64
 57  Valence Electrons Density_MP        894 non-null    float64
 58  a_MP                                968 non-null    float64
 59  b_MP                                934 non-null    float64
 60  c_MP                                934 non-null    float64
 61  Volume_COD                          968 non-null    float64
 62  Z_COD                               968 non-null    int64
 63  Valence Electrons Density_COD       655 non-null    float64
 64  a_COD                               968 non-null    float64
 65  b_COD                               753 non-null    float64
 66  c_COD                               753 non-null    float64
 67  Volume_Springer                     968 non-null    float64
 68  Z_Springer                          968 non-null    int64
 69  Valence Electrons Density_Springer  103 non-null    float64
 70  a_Springer                          968 non-null    float64
 71  b_Springer                          968 non-null    float64
 72  c_Springer                          968 non-null    float64
 73  Volume_manual                       414 non-null    float64
 74  Valence Electrons Density_manual    405 non-null    float64
 75  Oxygen_count                        968 non-null    int64
 76  Oxygen_concentration_manual         405 non-null    float64
 77  Oxygen_concentration_MP             894 non-null    float64
 78  Oxygen_concentration_COD            655 non-null    float64
 79  Oxygen_concentration_Springer       103 non-null    float64
 80  MP_packing_fraction                 894 non-null    float64
 81  COD_packing_fraction                655 non-null    float64
 82  Springer_packing_fraction           103 non-null    float64
 83  Manual_packing_fraction             405 non-null    float64
dtypes: bool(4), float64(54), int64(8), object(18)
memory usage: 608.9+ KB

# Filters

In [8]:
print(df.shape[0])
if(No_promoter):
    print("No promoter")
    #df = df[df['Promoter'] == '-']
    df = df[(df['Promoter, w%'] == 0)]
    #df= df[df["Promoter"] == "No promoter"]
else:
    print("Pt")
    df= df[df["Promoter"] == "Pt"]
print(df.shape[0])

968
No promoter
399

In [9]:
print(df.shape[0])
df= df[df["Nitrogen"] == False]
print(df.shape[0])

399
399

In [281]:
#df = df[df["Materials Project ID"].str.contains(r"^mp-",na=False)]

In [282]:
#df_nan = df[df["MP_CIF_modifier"].isna()]

In [10]:
print(df.shape[0])
df['Alcohol_nonzero'] = df['Alcohol, %'].replace(0, np.nan)
df = df[df['Alcohol_nonzero'].notna()]
print(df.shape[0])

399
256

# Hydrogen rate standartization

In [11]:
if(No_promoter):
    df['Rate_standardized'] = df['Rate, umol/(g*h)'] / (df['Alcohol, %']*df['CatW, g/L']*df["Power, W"])
else:
    df['Rate_standardized'] = df['Rate, umol/(g*h)'] / (df['Alcohol, %']*df['CatW, g/L']*df["Power, W"]*df["Promoter, w%"])

In [12]:
df["Log_rate_standardized"] = np.log(df['Rate_standardized'])
df["Log_rate"]=df["Log_rate_standardized"]

# Remove duplicates

In [13]:
df = df.groupby('Perovskite').agg({
    'Rate_standardized': 'mean',
    'MP_CIF_modified': 'first',
    'COD_CIF_modified': 'first',
    'Springer_CIF_modified': 'first'
}).reset_index()
df

,Perovskite,Rate_standardized,MP_CIF_modified,COD_CIF_modified,Springer_CIF_modified
0,Ag2La2Ti3O10,0.006886,mp-6000,1509663,None
1,AgCa2Nb3O10,0.060778,M_MP98,M_COD45,None
2,AgLaNb2O7,0.006228,mp-1222828,1509430,None
3,AgSr2Nb3O10,0.037605,M_MP99,M_COD46,None
4,Ba5Nb4O15,0.284337,N_MP44,-1,N_Springer14
...,...,...,...,...,...
143,Zn0.83Ti0.17S,NaN,N_MP19,N_COD19,None
144,Zn0.85Ti0.15S,NaN,N_MP18,N_COD18,None
145,Zn0.9Ti0.1S,NaN,N_MP20,N_COD20,None
146,ZnGa2O4,0.008660,mp-5794,4001767,None
147,ZrO2,60.960000,mp-775909,None,sd_0560284

In [14]:
df.to_excel("checkpoint_groupby.xlsx")

# Get materials info

In [ ]:
import os
from pymatgen.io.cif import CifWriter
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from mp_api.client import MPRester
API_KEY = ""

In [16]:
def get_material_info_from_id(MP_ID):
  output =  {"cif":"","elements":[],"pretty_formula":"","spacegroup_number":np.nan}
  file_path=cif_folder + str(MP_ID)+".cif"
  #print("Path: ",file_path)
  if os.path.exists(file_path):
    try:
      structure = Structure.from_file(file_path)
    except:
      print('ERROR: Invalid structure for ',MP_ID)
      return output
  else:
    return output

  if(structure == None):
    return output
  
  writer = CifWriter(structure)
  cif_string = str(writer)
  if not structure.is_ordered:
    print("Structure is unordered (disordered).")
    cif_string=""
  else:
    print("Structure is perfectly ordered.")


  formula_string = structure.composition.reduced_composition
  formula = str(formula_string).replace(" ","")
  print(formula)

  elements = structure.elements
  element_labels = [el.symbol for el in elements]
  print(element_labels)

  sga = SpacegroupAnalyzer(structure)
  sg_number = sga.get_space_group_number()

  for site in structure:
    if not site.is_ordered:
        print(f"Partial occupancy detected at {site.frac_coords}: {site.species}")
        return output

  #print(f"Space Group Number: {sg_number}")
  #print("CIF string: ",cif_string)
  return {"cif":cif_string,"elements":element_labels,"pretty_formula":formula,"spacegroup_number":sg_number}

In [17]:
print(get_material_info_from_id("mp-4423"))
#print(get_material_info_from_id("mp-31760"))

Structure is perfectly ordered.
La2Ti2O7
['La', 'Ti', 'O']
{'cif': "# generated using pymatgen\ndata_La2Ti2O7\n_symmetry_space_group_name_H-M   'P 1'\n_cell_length_a   7.41544296\n_cell_length_b   7.41544296\n_cell_length_c   7.41544296\n_cell_angle_alpha   60.00000000\n_cell_angle_beta   60.00000000\n_cell_angle_gamma   60.00000000\n_symmetry_Int_Tables_number   1\n_chemical_formula_structural   La2Ti2O7\n_chemical_formula_sum   'La4 Ti4 O14'\n_cell_volume   288.33429290\n_cell_formula_units_Z   2\nloop_\n _symmetry_equiv_pos_site_id\n _symmetry_equiv_pos_as_xyz\n  1  'x, y, z'\nloop_\n _atom_site_type_symbol\n _atom_site_label\n _atom_site_symmetry_multiplicity\n _atom_site_fract_x\n _atom_site_fract_y\n _atom_site_fract_z\n _atom_site_occupancy\n  La  La0  1  0.12500000  0.12500000  0.62500000  1.0\n  La  La1  1  0.12500000  0.62500000  0.12500000  1.0\n  La  La2  1  0.62500000  0.12500000  0.12500000  1.0\n  La  La3  1  0.12500000  0.12500000  0.12500000  1.0\n  Ti  Ti4  1  0.62500000  0.62500000  0.12500000  1.0\n  Ti  Ti5  1  0.62500000  0.12500000  0.62500000  1.0\n  Ti  Ti6  1  0.12500000  0.62500000  0.62500000  1.0\n  Ti  Ti7  1  0.62500000  0.62500000  0.62500000  1.0\n  O  O8  1  0.25000000  0.25000000  0.25000000  1.0\n  O  O9  1  0.00000000  0.00000000  0.00000000  1.0\n  O  O10  1  0.55216100  0.94783900  0.55216100  1.0\n  O  O11  1  0.30216100  0.69783900  0.30216100  1.0\n  O  O12  1  0.55216100  0.55216100  0.94783900  1.0\n  O  O13  1  0.94783900  0.55216100  0.55216100  1.0\n  O  O14  1  0.55216100  0.94783900  0.94783900  1.0\n  O  O15  1  0.94783900  0.94783900  0.55216100  1.0\n  O  O16  1  0.94783900  0.55216100  0.94783900  1.0\n  O  O17  1  0.69783900  0.30216100  0.30216100  1.0\n  O  O18  1  0.30216100  0.69783900  0.69783900  1.0\n  O  O19  1  0.69783900  0.30216100  0.69783900  1.0\n  O  O20  1  0.30216100  0.30216100  0.69783900  1.0\n  O  O21  1  0.69783900  0.69783900  0.30216100  1.0\n", 'elements': ['La', 'Ti', 'O'], 'pretty_formula': 'La2Ti2O7', 'spacegroup_number': 227}

In [18]:
def get_material_info_IDs(MP_ID, COD_ID, Springer_ID):
    #print("func")
    MP_info = get_material_info_from_id(MP_ID)
    if(MP_info["cif"]):
        return MP_info
    COD_info = get_material_info_from_id(COD_ID)
    if(COD_info["cif"]):
        return COD_info
    Springer_info = get_material_info_from_id(Springer_ID)
    if(Springer_info["cif"]):
        return Springer_info
    return None

In [19]:
get_material_info_IDs("mp-31760","","")

Structure is perfectly ordered.
Sr2Ta1Fe1O6
['Sr', 'Ta', 'Fe', 'O']

{'cif': "# generated using pymatgen\ndata_Sr2TaFeO6\n_symmetry_space_group_name_H-M   'P 1'\n_cell_length_a   5.66717500\n_cell_length_b   9.81577371\n_cell_length_c   9.81532669\n_cell_angle_alpha   70.70136550\n_cell_angle_beta   90.00000000\n_cell_angle_gamma   90.00000000\n_symmetry_Int_Tables_number   1\n_chemical_formula_structural   Sr2TaFeO6\n_chemical_formula_sum   'Sr8 Ta4 Fe4 O24'\n_cell_volume   515.32350959\n_cell_formula_units_Z   4\nloop_\n _symmetry_equiv_pos_site_id\n _symmetry_equiv_pos_as_xyz\n  1  'x, y, z'\nloop_\n _atom_site_type_symbol\n _atom_site_label\n _atom_site_symmetry_multiplicity\n _atom_site_fract_x\n _atom_site_fract_y\n _atom_site_fract_z\n _atom_site_occupancy\n  Sr  Sr0  1  0.48739800  0.12345700  0.62621200  1.0\n  Sr  Sr1  1  0.48739800  0.62345700  0.12621200  1.0\n  Sr  Sr2  1  0.98739800  0.87654300  0.87378800  1.0\n  Sr  Sr3  1  0.98739800  0.37654300  0.37378800  1.0\n  Sr  Sr4  1  0.01260200  0.12345700  0.12621200  1.0\n  Sr  Sr5  1  0.01260200  0.62345700  0.62621200  1.0\n  Sr  Sr6  1  0.51260200  0.87654300  0.37378800  1.0\n  Sr  Sr7  1  0.51260200  0.37654300  0.87378800  1.0\n  Ta  Ta8  1  0.00000000  0.75000000  0.25000000  1.0\n  Ta  Ta9  1  0.00000000  0.25000000  0.75000000  1.0\n  Ta  Ta10  1  0.50000000  0.25000000  0.25000000  1.0\n  Ta  Ta11  1  0.50000000  0.75000000  0.75000000  1.0\n  Fe  Fe12  1  0.00000000  0.50000000  0.00000000  1.0\n  Fe  Fe13  1  0.50000000  0.50000000  0.50000000  1.0\n  Fe  Fe14  1  0.00000000  0.00000000  0.50000000  1.0\n  Fe  Fe15  1  0.50000000  0.00000000  0.00000000  1.0\n  O  O16  1  0.49492600  0.65131100  0.60123900  1.0\n  O  O17  1  0.49492600  0.15131100  0.10123900  1.0\n  O  O18  1  0.99492600  0.84868900  0.39876100  1.0\n  O  O19  1  0.99492600  0.34868900  0.89876100  1.0\n  O  O20  1  0.50507400  0.34868900  0.39876100  1.0\n  O  O21  1  0.50507400  0.84868900  0.89876100  1.0\n  O  O22  1  0.00507400  0.15131100  0.60123900  1.0\n  O  O23  1  0.00507400  0.65131100  0.10123900  1.0\n  O  O24  1  0.23382700  0.87752900  0.64861300  1.0\n  O  O25  1  0.23382700  0.37752900  0.14861300  1.0\n  O  O26  1  0.73382700  0.12247100  0.85138700  1.0\n  O  O27  1  0.73382700  0.62247100  0.35138700  1.0\n  O  O28  1  0.76617300  0.12247100  0.35138700  1.0\n  O  O29  1  0.76617300  0.62247100  0.85138700  1.0\n  O  O30  1  0.26617300  0.87752900  0.14861300  1.0\n  O  O31  1  0.26617300  0.37752900  0.64861300  1.0\n  O  O32  1  0.77069600  0.89569100  0.13010500  1.0\n  O  O33  1  0.77069600  0.39569100  0.63010500  1.0\n  O  O34  1  0.27069600  0.10430900  0.36989500  1.0\n  O  O35  1  0.27069600  0.60430900  0.86989500  1.0\n  O  O36  1  0.22930400  0.10430900  0.86989500  1.0\n  O  O37  1  0.22930400  0.60430900  0.36989500  1.0\n  O  O38  1  0.72930400  0.89569100  0.63010500  1.0\n  O  O39  1  0.72930400  0.39569100  0.13010500  1.0\n",
 'elements': ['Sr', 'Ta', 'Fe', 'O'],
 'pretty_formula': 'Sr2Ta1Fe1O6',
 'spacegroup_number': 14}

In [20]:
output_columns = [
    'material_id',	
    'formation_energy_per_atom',
    'dft_band_gap',
    'pretty_formula',
    'e_above_hull',
    'elements',
    'cif',
    'spacegroup_number',
    'azure_bulk_modulus',
    'larsen_score_2d',
    'Si_100_mismatch',
    'azure_band_gap',
    'dft_bulk_modulus',
    'dft_poisson_ratio',
    'dft_mag_density',
]
for c in output_columns:
    df[c]=None

In [21]:
df.columns

Index(['Perovskite', 'Rate_standardized', 'MP_CIF_modified',
       'COD_CIF_modified', 'Springer_CIF_modified', 'material_id',
       'formation_energy_per_atom', 'dft_band_gap', 'pretty_formula',
       'e_above_hull', 'elements', 'cif', 'spacegroup_number',
       'azure_bulk_modulus', 'larsen_score_2d', 'Si_100_mismatch',
       'azure_band_gap', 'dft_bulk_modulus', 'dft_poisson_ratio',
       'dft_mag_density'],
      dtype='object')

In [22]:
print(df.shape[0])

148

In [23]:
results=[]
for row in df.to_dict('records'):
    MP_ID = row['MP_CIF_modified']
    COD_ID = row['COD_CIF_modified']
    Springer_ID = row['Springer_CIF_modified']
    #log_rate = row['Log_rate']
    info = get_material_info_IDs(MP_ID,COD_ID,Springer_ID)
    if(info is None):
        continue
    row['cif']=info["cif"]
    row['elements']=info["elements"]
    row['pretty_formula']=info["pretty_formula"]
    row['spacegroup_number']=info["spacegroup_number"]
    results.append(row)
df = pd.DataFrame(results)

Structure is perfectly ordered.
La2Ti3Ag2O10
['La', 'Ti', 'Ag', 'O']
Structure is perfectly ordered.
Ca2Nb3Ag1O10
['Ca', 'Nb', 'Ag', 'O']
Structure is perfectly ordered.
La1Nb2Ag1O7
['La', 'Nb', 'Ag', 'O']
Structure is perfectly ordered.
Sr2Nb3Ag1O10
['Sr', 'Nb', 'Ag', 'O']
Structure is perfectly ordered.
Ba5Nb4O15
['Ba', 'Nb', 'O']
Structure is unordered (disordered).
Ba5Ta2Nb2O15
['Ba', 'Ta', 'Nb', 'O']
Partial occupancy detected at [0.66666667 0.33333333 0.89621845]: Ta0.5 Nb0.5
Structure is unordered (disordered).
Ba5Ta2Nb2O15
['Ba', 'Ta', 'Nb', 'O']
Partial occupancy detected at [0.33333333 0.66666667 0.1035    ]: Ta0.5 Nb0.5
Structure is perfectly ordered.
Ba5Ta4O15
['Ba', 'Ta', 'O']
Structure is perfectly ordered.
Ba1Nb2Bi2O9
['Ba', 'Nb', 'Bi', 'O']
Structure is perfectly ordered.
Ba1Ta2Bi2O9
['Ba', 'Ta', 'Bi', 'O']
Structure is unordered (disordered).
Ti2.5Cr0.5Bi4O12
['Ti', 'Cr', 'Bi', 'O']
Partial occupancy detected at [0.364722 0.364722 0.257035]: Ti0.83333333 Cr0.16666667
Structure is unordered (disordered).
Ti5Cr1Bi8O24
['Ti', 'Cr', 'Bi', 'O']
Partial occupancy detected at [0.3714 0.999  0.0533]: Ti0.83333333 Cr0.16666667
Structure is unordered (disordered).
Ti2.6Cr0.4Bi4O12
['Ti', 'Cr', 'Bi', 'O']
Partial occupancy detected at [0.364722 0.364722 0.257035]: Ti0.86666667 Cr0.13333333
Structure is unordered (disordered).
Ti10.4Cr1.6Bi16O48
['Ti', 'Cr', 'Bi', 'O']
Partial occupancy detected at [0.3714 0.999  0.0533]: Ti0.86666667 Cr0.13333333

e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: 12 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  struct = parser.parse_structures(primitive=primitive)[0]
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: 16 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  struct = parser.parse_structures(primitive=primitive)[0]
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ba0', 'Ba1', 'Ba2', 'Ba3', 'Ba4', 'Ta5', 'Ta5', 'Ta6', 'Ta6', 'Ta7', 'Ta7', 'Ta8', 'Ta8', 'O9', 'O10', 'O11', 'O12', 'O13', 'O14', 'O15', 'O16', 'O17', 'O18', 'O19', 'O20', 'O21', 'O22', 'O23']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ba1', 'Ba1', 'Ba2', 'Ba2', 'Ba3', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ti0', 'Ti0', 'Ti1', 'Ti1', 'Ti2', 'Ti2', 'Bi3', 'Bi4', 'Bi5', 'Bi6', 'O7', 'O8', 'O9', 'O10', 'O11', 'O12', 'O13', 'O14', 'O15', 'O16', 'O17', 'O18']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti2', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Ti1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi1', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'Bi2', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O6', 'O6', 'O6', 'O6', 'O6', 'O6', 'O6', 'O6', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5']`.
  writer = CifWriter(structure)

Structure is unordered (disordered).
Ti2.7Cr0.3Bi4O12
['Ti', 'Cr', 'Bi', 'O']
Partial occupancy detected at [0.364722 0.364722 0.257035]: Ti0.9 Cr0.1
Structure is unordered (disordered).
Ti10.8Cr1.2Bi16O48
['Ti', 'Cr', 'Bi', 'O']
Partial occupancy detected at [0.3714 0.999  0.0533]: Ti0.9 Cr0.1
Structure is unordered (disordered).
Ti2.85Cr0.15Bi4O12
['Ti', 'Cr', 'Bi', 'O']
Partial occupancy detected at [0.364722 0.364722 0.257035]: Ti0.95 Cr0.05
Structure is unordered (disordered).
Ti11.4Cr0.6Bi16O48
['Ti', 'Cr', 'Bi', 'O']
Partial occupancy detected at [0.3714 0.999  0.0533]: Ti0.95 Cr0.05
Structure is unordered (disordered).
Ti2.94Cr0.06Bi4O12
['Ti', 'Cr', 'Bi', 'O']
Partial occupancy detected at [0.364722 0.364722 0.257035]: Ti0.98 Cr0.02
Structure is unordered (disordered).
Ti11.76Cr0.24Bi16O48
['Ti', 'Cr', 'Bi', 'O']
Partial occupancy detected at [0.3714 0.999  0.0533]: Ti0.98 Cr0.02
Structure is perfectly ordered.
Ti3Bi4O12
['Ti', 'Bi', 'O']
Structure is perfectly ordered.
Ca1Nb2Bi2O9
['Ca', 'Nb', 'Bi', 'O']
Structure is perfectly ordered.
Ca1Ta2Bi2O9
['Ca', 'Ta', 'Bi', 'O']
Structure is perfectly ordered.
Ca1In2S4
['Ca', 'In', 'S']
Structure is perfectly ordered.
Cs1Ba2Nb3O10
['Cs', 'Ba', 'Nb', 'O']
Structure is perfectly ordered.
Cs1Ca2Nb3O10
['Cs', 'Ca', 'Nb', 'O']
Structure is perfectly ordered.
Cs1La1Nb2O7
['Cs', 'La', 'Nb', 'O']
Structure is perfectly ordered.
Cs1Nd1Nb2O7
['Cs', 'Nd', 'Nb', 'O']

C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Cs1', 'Nd1', 'Ta1', 'Ta1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O3']`.
  writer = CifWriter(structure)
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: No structure parsed for section 1 in CIF.
'_atom_site_label'
  struct = parser.parse_structures(primitive=primitive)[0]
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\io\cif.py:1057: UserWarning: No _symmetry_equiv_pos_as_xyz type key found. Spacegroup from _symmetry_space_group_name_H-M used.
  self.symmetry_operations = self.get_symops(data)  # type:ignore[assignment]
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\io\cif.py:1342: UserWarning: Cannot determine chemical composition from CIF! 'NoneType' object is not iterable
  if struct := self._get_structure(data, primitive, symmetrized, check_occu=check_occu):
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\io\cif.py:1057: UserWarning: No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
  self.symmetry_operations = self.get_symops(data)  # type:ignore[assignment]
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\core\structure.py:3112: UserWarning: Issues encountered while parsing CIF: No structure parsed for section 1 in CIF.
'_atom_site_label'
No _symmetry_equiv_pos_as_xyz type key found. Spacegroup from _symmetry_space_group_name_H-M used.
No _symmetry_equiv_pos_as_xyz type key found. Spacegroup from _symmetry_space_group_name_H-M used.
No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
  struct = parser.parse_structures(primitive=primitive)[0]
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['La2', 'La3', 'Ti4', 'Ti5', 'Ti6', 'K0', 'K0', 'K1', 'K1', 'O7', 'O8', 'O9', 'O10', 'O11', 'O12', 'O13', 'O14', 'O15', 'O16']`.
  writer = CifWriter(structure)

Structure is perfectly ordered.
Cs1Nd1Ta2O7
['Cs', 'Nd', 'Ta', 'O']
Structure is unordered (disordered).
Nd2Ti3Rb0.5H1.5O10
['Nd', 'Ti', 'Rb', 'H', 'O']
Partial occupancy detected at [0.292256 0.292256 0.      ]: Rb0.25 H0.75
Structure is perfectly ordered.
La2Ti3H2O10
['La', 'Ti', 'H', 'O']
Structure is perfectly ordered.
La2Ti3H16C4N2O10
['La', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
La2Ti3H14C4O12
['La', 'Ti', 'H', 'C', 'O']
Structure is perfectly ordered.
La2Ti3H24C8N2O10
['La', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
La2Ti3H22C8O12
['La', 'Ti', 'H', 'C', 'O']
Structure is perfectly ordered.
La2Ti3H32C12N2O10
['La', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
La2Ti3H30C12O12
['La', 'Ti', 'H', 'C', 'O']
Structure is perfectly ordered.
La2Ti3H40C16N2O10
['La', 'Ti', 'H', 'C', 'N', 'O']

C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['A25', 'A26', 'A27', 'A28', 'A13', 'A14', 'A15', 'A16', 'A33', 'A34', 'A35', 'A36', 'A37', 'A40', 'A41', 'A42', 'A64', 'A65', 'A66', 'A69', 'A70', 'A71', 'A35', 'A36', 'A37', 'A40', 'A41', 'A42', 'A122', 'A123', 'A124', 'A127', 'A128', 'A129', 'A39', 'A68', 'A39', 'A126', 'A38', 'A67', 'A38', 'A125', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A17', 'A18', 'A19', 'A20', 'A29', 'A30', 'A31', 'A32']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['A25', 'A26', 'A27', 'A28', 'A13', 'A14', 'A15', 'A16', 'A33', 'A34', 'A35', 'A36', 'A40', 'A41', 'A42', 'A64', 'A65', 'A69', 'A70', 'A71', 'A35', 'A36', 'A40', 'A41', 'A42', 'A122', 'A123', 'A127', 'A128', 'A129', 'A39', 'A68', 'A39', 'A126', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A17', 'A18', 'A19', 'A20', 'A29', 'A30', 'A31', 'A32', 'A38', 'A67', 'A38', 'A125']`.
  writer = CifWriter(structure)

Structure is perfectly ordered.
La2Ti3H12C2N2O10
['La', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
La2Ti3H10C2O12
['La', 'Ti', 'H', 'C', 'O']
Structure is perfectly ordered.
Nd2Ti3H2O10
['Nd', 'Ti', 'H', 'O']
Structure is perfectly ordered.
Nd2Ti3H16C4N2O10
['Nd', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
Nd2Ti3H14C4O12
['Nd', 'Ti', 'H', 'C', 'O']
Structure is perfectly ordered.
Nd2Ti3H24C8N2O10
['Nd', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
Nd2Ti3H22C8O12
['Nd', 'Ti', 'H', 'C', 'O']
Structure is perfectly ordered.
Nd2Ti3H32C12N2O10
['Nd', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
Nd2Ti3H30C12O12
['Nd', 'Ti', 'H', 'C', 'O']
Structure is perfectly ordered.
Nd2Ti3H40C16N2O10
['Nd', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
Nd2Ti3H12C2N2O10
['Nd', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
Nd2Ti3H10C2O12
['Nd', 'Ti', 'H', 'C', 'O']
Structure is perfectly ordered.
Nb6H4O17
['Nb', 'H', 'O']
Structure is unordered (disordered).
Ca8Nb11.4Rh0.6H4O40
['Ca', 'Nb', 'Rh', 'H', 'O']
Partial occupancy detected at [0.505216 0.932331 0.285881]: Nb0.95 Rh0.05
Structure is unordered (disordered).
Ca8Nb11.4Rh0.6H4O40
['Ca', 'Nb', 'Rh', 'H', 'O']
Partial occupancy detected at [0.  0.  0.5]: Nb0.95 Rh0.05
Structure is unordered (disordered).
Ca8Nb11.88Rh0.12H4O40
['Ca', 'Nb', 'Rh', 'H', 'O']
Partial occupancy detected at [0.505216 0.932331 0.285881]: Nb0.99 Rh0.01
Structure is unordered (disordered).
Ca8Nb11.88Rh0.12H4O40
['Ca', 'Nb', 'Rh', 'H', 'O']
Partial occupancy detected at [0.  0.  0.5]: Nb0.99 Rh0.01
Structure is unordered (disordered).
Ca8Nb11.996Rh0.004H4O40
['Ca', 'Nb', 'Rh', 'H', 'O']
Partial occupancy detected at [0.505216 0.932331 0.285881]: Nb0.99966667 Rh0.00033333
Structure is unordered (disordered).
Ca8Nb11.996Rh0.004H4O40
['Ca', 'Nb', 'Rh', 'H', 'O']
Partial occupancy detected at [0.  0.  0.5]: Nb0.99966667 Rh0.00033333

C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ca4', 'Ca5', 'Ca6', 'Ca7', 'Ca8', 'Ca9', 'Ca10', 'Ca11', 'Nb12', 'Nb12', 'Nb13', 'Nb13', 'Nb14', 'Nb14', 'Nb15', 'Nb15', 'Nb16', 'Nb16', 'Nb17', 'Nb17', 'Nb18', 'Nb18', 'Nb19', 'Nb19', 'Nb20', 'Nb20', 'Nb21', 'Nb21', 'Nb22', 'Nb22', 'Nb23', 'Nb23', 'K0', 'K1', 'K2', 'K3', 'O24', 'O25', 'O26', 'O27', 'O28', 'O29', 'O30', 'O31', 'O32', 'O33', 'O34', 'O35', 'O36', 'O37', 'O38', 'O39', 'O40', 'O41', 'O42', 'O43', 'O44', 'O45', 'O46', 'O47', 'O48', 'O49', 'O50', 'O51', 'O52', 'O53', 'O54', 'O55', 'O56', 'O57', 'O58', 'O59', 'O60', 'O61', 'O62', 'O63']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ca2', 'Ca2', 'Ca2', 'Ca2', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'K1', 'K1', 'K1', 'K1', 'O6', 'O6', 'O6', 'O6', 'O5', 'O5', 'O5', 'O5', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)

Structure is unordered (disordered).
Ca8Nb11.96Rh0.04H4O40
['Ca', 'Nb', 'Rh', 'H', 'O']
Partial occupancy detected at [0.505216 0.932331 0.285881]: Nb0.99666667 Rh0.00333333
Structure is unordered (disordered).
Ca8Nb11.96Rh0.04H4O40
['Ca', 'Nb', 'Rh', 'H', 'O']
Partial occupancy detected at [0.  0.  0.5]: Nb0.99666667 Rh0.00333333
Structure is unordered (disordered).
Ca8Nb11.6Rh0.4H4O40
['Ca', 'Nb', 'Rh', 'H', 'O']
Partial occupancy detected at [0.505216 0.932331 0.285881]: Nb0.96666667 Rh0.03333333
Structure is unordered (disordered).
Ca8Nb11.6Rh0.4H4O40
['Ca', 'Nb', 'Rh', 'H', 'O']
Partial occupancy detected at [0.  0.  0.5]: Nb0.96666667 Rh0.03333333
Structure is perfectly ordered.
Ca2Nb3H1O10
['Ca', 'Nb', 'H', 'O']
Structure is unordered (disordered).
Ca2Ta1.5Nb1.5H1O10
['Ca', 'Ta', 'Nb', 'H', 'O']
Partial occupancy detected at [0.5      0.641569 0.716862]: Ta0.5 Nb0.5
Structure is unordered (disordered).
K1Ca2Ta3O10
['K', 'Ca', 'Ta', 'O']
Partial occupancy detected at [0.     0.2439 0.    ]: K0.5
Structure is unordered (disordered).
Ca2Ta2Nb1H1O10
['Ca', 'Ta', 'Nb', 'H', 'O']
Partial occupancy detected at [0.5      0.641569 0.716862]: Ta0.66666667 Nb0.33333333
Structure is unordered (disordered).
K1Ca2Ta3O10
['K', 'Ca', 'Ta', 'O']
Partial occupancy detected at [0.     0.2439 0.    ]: K0.5
Structure is perfectly ordered.
Ca2Ta3H1O10
['Ca', 'Ta', 'H', 'O']
Structure is unordered (disordered).
Ca2Ta1Nb2H1O10
['Ca', 'Ta', 'Nb', 'H', 'O']
Partial occupancy detected at [0.5      0.641569 0.716862]: Ta0.33333333 Nb0.66666667
Structure is unordered (disordered).
K1Ca2Ta3O10
['K', 'Ca', 'Ta', 'O']
Partial occupancy detected at [0.     0.2439 0.    ]: K0.5
Structure is perfectly ordered.
La1Nb2H1O7
['La', 'Nb', 'H', 'O']
Structure is unordered (disordered).
La1Ta0.67Nb1.33H1O7
['La', 'Ta', 'Nb', 'H', 'O']
Partial occupancy detected at [0.       0.       0.218607]: Ta0.335 Nb0.665
Structure is unordered (disordered).
La1Ta1.33Nb0.67H1O7
['La', 'Ta', 'Nb', 'H', 'O']
Partial occupancy detected at [0.       0.       0.218607]: Ta0.665 Nb0.335

C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ca1', 'Ca2', 'Ta3', 'Ta3', 'Ta4', 'Ta4', 'Ta5', 'Ta5', 'K0', 'O6', 'O7', 'O8', 'O9', 'O10', 'O11', 'O12', 'O13', 'O14', 'O15']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['K1', 'K1', 'K1', 'K1', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Ta1', 'Ta1', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'O6', 'O6', 'O1', 'O1', 'O5', 'O5', 'O5', 'O5', 'O4', 'O4', 'O4', 'O4', 'O3', 'O3', 'O3', 'O3', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['La0', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'H3', 'O4', 'O5', 'O6', 'O7', 'O8', 'O9', 'O10']`.
  writer = CifWriter(structure)
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\pymatgen\io\cif.py:1342: UserWarning: Missing elements K from PMG structure composition
  if struct := self._get_structure(data, primitive, symmetrized, check_occu=check_occu):

Structure is perfectly ordered.
La1Ta2H1O7
['La', 'Ta', 'H', 'O']
Structure is unordered (disordered).
La1Ta1Nb1H1O7
['La', 'Ta', 'Nb', 'H', 'O']
Partial occupancy detected at [0.       0.       0.218607]: Ta0.5 Nb0.5
Structure is perfectly ordered.
La1Ti1H1O4
['La', 'Ti', 'H', 'O']
Structure is perfectly ordered.
La1Ti1H8C2N1O4
['La', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
La1Ti1H7C2O5
['La', 'Ti', 'H', 'C', 'O']
Structure is perfectly ordered.
La1Ti1H12C4N1O4
['La', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
La1Ti1H11C4O5
['La', 'Ti', 'H', 'C', 'O']
Structure is perfectly ordered.
La1Ti1H16C6N1O4
['La', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
La1Ti1H15C6O5
['La', 'Ti', 'H', 'C', 'O']
Structure is perfectly ordered.
La1Ti1H6C1N1O4
['La', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
La1Ti1H5C1O5
['La', 'Ti', 'H', 'C', 'O']
Structure is perfectly ordered.
Nd1Nb2H1O7
['Nd', 'Nb', 'H', 'O']
Structure is perfectly ordered.
Nd1Ta2H1O7
['Nd', 'Ta', 'H', 'O']
Structure is perfectly ordered.
Nd1Ti1H1O4
['Nd', 'Ti', 'H', 'O']
Structure is perfectly ordered.
Nd1Ti1H8C2N1O4
['Nd', 'Ti', 'H', 'C', 'N', 'O']

C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Nd1', 'Ta1', 'Ta1', 'Cs1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O3']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Nd1', 'Nd1', 'Nd1', 'Nd1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Li1', 'Li1', 'Li1', 'Li1', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O4', 'O4', 'O4', 'O4']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['La2', 'La3', 'K0', 'K0', 'K1', 'K1', 'Ti4', 'Ti5', 'Ti6', 'O7', 'O8', 'O9', 'O10', 'O11', 'O12', 'O13', 'O14', 'O15', 'O16']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ca1', 'Ca2', 'Ta3', 'Ta3', 'Ta4', 'Ta4', 'Ta5', 'Ta5', 'Cs0', 'O6', 'O7', 'O8', 'O9', 'O10', 'O11', 'O12', 'O13', 'O14', 'O15']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ca1', 'Ca1', 'Ta1', 'Ta1', 'Ta2', 'Ta2', 'Ta2', 'Ta2', 'Cs1', 'O3', 'O3', 'O3', 'O3', 'O2', 'O2', 'O4', 'O4', 'O1', 'O1']`.
  writer = CifWriter(structure)

Structure is perfectly ordered.
Nd1Ti1H7C2O5
['Nd', 'Ti', 'H', 'C', 'O']
Structure is perfectly ordered.
Nd1Ti1H12C4N1O4
['Nd', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
Nd1Ti1H11C4O5
['Nd', 'Ti', 'H', 'C', 'O']
Structure is perfectly ordered.
Nd1Ti1H16C6N1O4
['Nd', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
Nd1Ti1H15C6O5
['Nd', 'Ti', 'H', 'C', 'O']
Structure is perfectly ordered.
Nd1Ti1H6C1N1O4
['Nd', 'Ti', 'H', 'C', 'N', 'O']
Structure is perfectly ordered.
Nd1Ti1H5C1O5
['Nd', 'Ti', 'H', 'C', 'O']
Structure is unordered (disordered).
Nd2Rb1H1Ti3O10
['Nd', 'Rb', 'H', 'Ti', 'O']
Partial occupancy detected at [0.292256 0.292256 0.      ]: Rb0.5 H0.5
Structure is perfectly ordered.
Sr2Nb3H1O10
['Sr', 'Nb', 'H', 'O']
Structure is unordered (disordered).
Sr2Ta1.5Nb1.5H1O10
['Sr', 'Ta', 'Nb', 'H', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.5 Nb0.5
Structure is unordered (disordered).
Sr2Ta1.5Nb1.5H1O10
['Sr', 'Ta', 'Nb', 'H', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.5 Nb0.5
Structure is unordered (disordered).
Sr2Ta2Nb1H1O10
['Sr', 'Ta', 'Nb', 'H', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.66666667 Nb0.33333333
Structure is unordered (disordered).
Sr2Ta2Nb1H1O10
['Sr', 'Ta', 'Nb', 'H', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.66666667 Nb0.33333333
Structure is perfectly ordered.
Sr2Ta3H1O10
['Sr', 'Ta', 'H', 'O']
Structure is unordered (disordered).
Sr2Ta1Nb2H1O10
['Sr', 'Ta', 'Nb', 'H', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.33333333 Nb0.66666667
Structure is unordered (disordered).
Sr2Ta1Nb2H1O10
['Sr', 'Ta', 'Nb', 'H', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.33333333 Nb0.66666667
Structure is perfectly ordered.
K2La2Ti3O10
['K', 'La', 'Ti', 'O']
Structure is perfectly ordered.
K1Nb3O8
['K', 'Nb', 'O']
Structure is perfectly ordered.
K2Nd2Ti3O10
['K', 'Nd', 'Ti', 'O']
Structure is perfectly ordered.
K4Nb6O17
['K', 'Nb', 'O']
Structure is unordered (disordered).
K4Ca8Nb11.88Rh0.12O40
['K', 'Ca', 'Nb', 'Rh', 'O']
Partial occupancy detected at [0.505216 0.932331 0.285881]: Nb0.99 Rh0.01
Structure is unordered (disordered).
K4Ca8Nb11.88Rh0.12O40
['K', 'Ca', 'Nb', 'Rh', 'O']
Partial occupancy detected at [0.  0.  0.5]: Nb0.99 Rh0.01
Structure is perfectly ordered.
K1Ca2Nb3O10
['K', 'Ca', 'Nb', 'O']
Structure is perfectly ordered.
K1La1Nb2O7
['K', 'La', 'Nb', 'O']
Structure is perfectly ordered.
K1Nb1O3
['K', 'Nb', 'O']
Structure is perfectly ordered.
K1Nd1Ta2O7
['K', 'Nd', 'Ta', 'O']
Structure is perfectly ordered.
K1Sr2Nb3O10
['K', 'Sr', 'Nb', 'O']
Structure is perfectly ordered.
K1Ta1O3
['K', 'Ta', 'O']
Structure is perfectly ordered.
La2Ti2O7
['La', 'Ti', 'O']

C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['K0', 'K1', 'K2', 'K3', 'Ca4', 'Ca5', 'Ca6', 'Ca7', 'Ca8', 'Ca9', 'Ca10', 'Ca11', 'Nb12', 'Nb12', 'Nb13', 'Nb13', 'Nb14', 'Nb14', 'Nb15', 'Nb15', 'Nb16', 'Nb16', 'Nb17', 'Nb17', 'Nb18', 'Nb18', 'Nb19', 'Nb19', 'Nb20', 'Nb20', 'Nb21', 'Nb21', 'Nb22', 'Nb22', 'Nb23', 'Nb23', 'O24', 'O25', 'O26', 'O27', 'O28', 'O29', 'O30', 'O31', 'O32', 'O33', 'O34', 'O35', 'O36', 'O37', 'O38', 'O39', 'O40', 'O41', 'O42', 'O43', 'O44', 'O45', 'O46', 'O47', 'O48', 'O49', 'O50', 'O51', 'O52', 'O53', 'O54', 'O55', 'O56', 'O57', 'O58', 'O59', 'O60', 'O61', 'O62', 'O63']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['K1', 'K1', 'K1', 'K1', 'Ca2', 'Ca2', 'Ca2', 'Ca2', 'Ca1', 'Ca1', 'Ca1', 'Ca1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'Nb2', 'O6', 'O6', 'O6', 'O6', 'O5', 'O5', 'O5', 'O5', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O7', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['K1', 'K1', 'K1', 'K1', 'Nd1', 'Nd1', 'Nd2', 'Nd2', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O2', 'O2', 'O2', 'O2', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1']`.
  writer = CifWriter(structure)

Structure is perfectly ordered.
Li2La2Ti3O10
['Li', 'La', 'Ti', 'O']
Structure is perfectly ordered.
Li2Nd2Ti3O10
['Li', 'Nd', 'Ti', 'O']
Structure is perfectly ordered.
Li1Nd1Nb2O7
['Li', 'Nd', 'Nb', 'O']
Structure is perfectly ordered.
Li1Nd1Ta2O7
['Li', 'Nd', 'Ta', 'O']
Structure is unordered (disordered).
K3.6Na4.4Ta8O24
['K', 'Na', 'Ta', 'O']
Partial occupancy detected at [0.011738 0.995705 0.476632]: K0.45 Na0.55
Structure is unordered (disordered).
K1.8Na2.2Ta4O12
['K', 'Na', 'Ta', 'O']
Partial occupancy detected at [0.0023 0.518  0.25  ]: K0.45 Na0.55
Structure is unordered (disordered).
K3.44Na4.56Ta8O24
['K', 'Na', 'Ta', 'O']
Partial occupancy detected at [0.011738 0.995705 0.476632]: K0.43 Na0.57
Structure is unordered (disordered).
K1.72Na2.28Ta4O12
['K', 'Na', 'Ta', 'O']
Partial occupancy detected at [0.0023 0.518  0.25  ]: K0.43 Na0.57
Structure is unordered (disordered).
K3.36Na4.64Ta8O24
['K', 'Na', 'Ta', 'O']
Partial occupancy detected at [0.011738 0.995705 0.476632]: K0.42 Na0.58
Structure is unordered (disordered).
K1.68Na2.32Ta4O12
['K', 'Na', 'Ta', 'O']
Partial occupancy detected at [0.0023 0.518  0.25  ]: K0.42 Na0.58
Structure is unordered (disordered).
K3.12Na4.88Ta8O24
['K', 'Na', 'Ta', 'O']
Partial occupancy detected at [0.011738 0.995705 0.476632]: K0.39 Na0.61
Structure is unordered (disordered).
K1.56Na2.44Ta4O12
['K', 'Na', 'Ta', 'O']
Partial occupancy detected at [0.0023 0.518  0.25  ]: K0.39 Na0.61
Structure is unordered (disordered).
K2.96Na5.04Ta8O24
['K', 'Na', 'Ta', 'O']
Partial occupancy detected at [0.011738 0.995705 0.476632]: K0.37 Na0.63
Structure is unordered (disordered).
K1.48Na2.52Ta4O12
['K', 'Na', 'Ta', 'O']
Partial occupancy detected at [0.0023 0.518  0.25  ]: K0.37 Na0.63

C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Li1', 'Li1', 'Li1', 'Li1', 'Nd1', 'Nd1', 'Nd1', 'Nd1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O3', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O4', 'O4', 'O4', 'O4']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Na0', 'Na0', 'Na1', 'Na1', 'Na2', 'Na2', 'Na3', 'Na3', 'Na4', 'Na4', 'Na5', 'Na5', 'Na6', 'Na6', 'Na7', 'Na7', 'Ta8', 'Ta9', 'Ta10', 'Ta11', 'Ta12', 'Ta13', 'Ta14', 'Ta15', 'O16', 'O17', 'O18', 'O19', 'O20', 'O21', 'O22', 'O23', 'O24', 'O25', 'O26', 'O27', 'O28', 'O29', 'O30', 'O31', 'O32', 'O33', 'O34', 'O35', 'O36', 'O37', 'O38', 'O39']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Na1', 'Na1', 'Na1', 'Na1', 'Na1', 'Na1', 'Na1', 'Na1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)

Structure is unordered (disordered).
K2.8Na5.2Ta8O24
['K', 'Na', 'Ta', 'O']
Partial occupancy detected at [0.011738 0.995705 0.476632]: K0.35 Na0.65
Structure is unordered (disordered).
K1.4Na2.6Ta4O12
['K', 'Na', 'Ta', 'O']
Partial occupancy detected at [0.0023 0.518  0.25  ]: K0.35 Na0.65
Structure is unordered (disordered).
K3.2Na4.8Ta8O24
['K', 'Na', 'Ta', 'O']
Partial occupancy detected at [0.011738 0.995705 0.476632]: K0.4 Na0.6
Structure is unordered (disordered).
K1.6Na2.4Ta4O12
['K', 'Na', 'Ta', 'O']
Partial occupancy detected at [0.0023 0.518  0.25  ]: K0.4 Na0.6
Structure is perfectly ordered.
Na2La2Ti3O10
['Na', 'La', 'Ti', 'O']
Structure is perfectly ordered.
Na2Nd2Ti3O10
['Na', 'Nd', 'Ti', 'O']
Structure is unordered (disordered).
Na8Ta7.84Bi0.16O24
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0.995775 0.002259 0.998624]: Ta0.98 Bi0.02
Structure is unordered (disordered).
Na4Ta3.92Bi0.08O12
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.98 Bi0.02
Structure is unordered (disordered).
Na8Ta7.68Bi0.32O24
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0.995775 0.002259 0.998624]: Ta0.96 Bi0.04
Structure is unordered (disordered).
Na4Ta3.84Bi0.16O12
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.96 Bi0.04
Structure is unordered (disordered).
Na8Ta7.52Bi0.48O24
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0.995775 0.002259 0.998624]: Ta0.94 Bi0.06
Structure is unordered (disordered).
Na4Ta3.76Bi0.24O12
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.94 Bi0.06
Structure is unordered (disordered).
Na8Ta7.4Bi0.6O24
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0.995775 0.002259 0.998624]: Ta0.925 Bi0.075
Structure is unordered (disordered).
Na4Ta3.7Bi0.3O12
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.925 Bi0.075
Structure is unordered (disordered).
Na8Ta7.44Bi0.56O24
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0.995775 0.002259 0.998624]: Ta0.93 Bi0.07

C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Na0', 'Na1', 'Na2', 'Na3', 'Na4', 'Na5', 'Na6', 'Na7', 'Ta8', 'Ta8', 'Ta9', 'Ta9', 'Ta10', 'Ta10', 'Ta11', 'Ta11', 'Ta12', 'Ta12', 'Ta13', 'Ta13', 'Ta14', 'Ta14', 'Ta15', 'Ta15', 'O16', 'O17', 'O18', 'O19', 'O20', 'O21', 'O22', 'O23', 'O24', 'O25', 'O26', 'O27', 'O28', 'O29', 'O30', 'O31', 'O32', 'O33', 'O34', 'O35', 'O36', 'O37', 'O38', 'O39']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Na1', 'Na1', 'Na1', 'Na1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)

Structure is unordered (disordered).
Na4Ta3.72Bi0.28O12
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.93 Bi0.07
Structure is unordered (disordered).
Na8Ta7.36Bi0.64O24
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0.995775 0.002259 0.998624]: Ta0.92 Bi0.08
Structure is unordered (disordered).
Na4Ta3.68Bi0.32O12
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.92 Bi0.08
Structure is unordered (disordered).
Na8Ta7.28Bi0.72O24
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0.995775 0.002259 0.998624]: Ta0.91 Bi0.09
Structure is unordered (disordered).
Na4Ta3.64Bi0.36O12
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.91 Bi0.09
Structure is unordered (disordered).
Na8Ta7.2Bi0.8O24
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0.995775 0.002259 0.998624]: Ta0.9 Bi0.1
Structure is unordered (disordered).
Na4Ta3.6Bi0.4O12
['Na', 'Ta', 'Bi', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.9 Bi0.1
Structure is perfectly ordered.
Na1Nb1O3
['Na', 'Nb', 'O']
Structure is perfectly ordered.
Na1Nd1Nb2O7
['Na', 'Nd', 'Nb', 'O']
Structure is perfectly ordered.
Na1Nd1Ta2O7
['Na', 'Nd', 'Ta', 'O']
Structure is unordered (disordered).
Na8Ta1.6Nb6.4O24
['Na', 'Ta', 'Nb', 'O']
Partial occupancy detected at [0.995775 0.002259 0.998624]: Ta0.2 Nb0.8
Structure is unordered (disordered).
Na4Ta0.8Nb3.2O12
['Na', 'Ta', 'Nb', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.2 Nb0.8
Structure is unordered (disordered).
Na8Ta2.4Nb5.6O24
['Na', 'Ta', 'Nb', 'O']
Partial occupancy detected at [0.995775 0.002259 0.998624]: Ta0.3 Nb0.7
Structure is unordered (disordered).
Na4Ta1.2Nb2.8O12
['Na', 'Ta', 'Nb', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.3 Nb0.7

C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Na1', 'Na1', 'Na1', 'Na1', 'Nd1', 'Nd1', 'Nd1', 'Nd1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'Ta1', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O5', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O4', 'O1', 'O1', 'O1', 'O1', 'O3', 'O3', 'O3', 'O3', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)

Structure is unordered (disordered).
Na2Ta1Nb1O6
['Na', 'Ta', 'Nb', 'O']
Partial occupancy detected at [0.995775 0.002259 0.998624]: Ta0.5 Nb0.5
Structure is unordered (disordered).
Na2Ta1Nb1O6
['Na', 'Ta', 'Nb', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.5 Nb0.5
Structure is unordered (disordered).
Na8Ta5.6Nb2.4O24
['Na', 'Ta', 'Nb', 'O']
Partial occupancy detected at [0.995775 0.002259 0.998624]: Ta0.7 Nb0.3
Structure is unordered (disordered).
Na4Ta2.8Nb1.2O12
['Na', 'Ta', 'Nb', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.7 Nb0.3
Structure is unordered (disordered).
Na8Ta6.4Nb1.6O24
['Na', 'Ta', 'Nb', 'O']
Partial occupancy detected at [0.995775 0.002259 0.998624]: Ta0.8 Nb0.2
Structure is unordered (disordered).
Na4Ta3.2Nb0.8O12
['Na', 'Ta', 'Nb', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.8 Nb0.2
Structure is unordered (disordered).
Na8Ta7.2Nb0.8O24
['Na', 'Ta', 'Nb', 'O']
Partial occupancy detected at [0.995775 0.002259 0.998624]: Ta0.9 Nb0.1
Structure is unordered (disordered).
Na4Ta3.6Nb0.4O12
['Na', 'Ta', 'Nb', 'O']
Partial occupancy detected at [0. 0. 0.]: Ta0.9 Nb0.1
Structure is perfectly ordered.
Na1Ta1O3
['Na', 'Ta', 'O']
Structure is unordered (disordered).
Nb2O5
['Nb', 'O']
Partial occupancy detected at [0.     0.7715 0.5   ]: Nb0.5
Structure is perfectly ordered.
Nd2Ti2O7
['Nd', 'Ti', 'O']
Structure is perfectly ordered.
Rb1Ca2Nb3O10
['Rb', 'Ca', 'Nb', 'O']

C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Nb1', 'Nb1', 'Nb2', 'Nb2', 'Nb3', 'Nb3', 'Nb4', 'Nb4', 'Nb5', 'Nb5', 'Nb6', 'Nb6', 'Nb7', 'Nb7', 'Nb8', 'Nb8', 'Nb9', 'Nb9', 'Nb10', 'Nb10', 'Nb11', 'Nb11', 'Nb12', 'Nb12', 'Nb13', 'Nb13', 'Nb15', 'Nb14', 'Nb14', 'O1', 'O1', 'O2', 'O2', 'O3', 'O3', 'O4', 'O4', 'O5', 'O5', 'O6', 'O6', 'O7', 'O7', 'O8', 'O8', 'O9', 'O9', 'O10', 'O10', 'O11', 'O11', 'O12', 'O12', 'O13', 'O13', 'O14', 'O14', 'O15', 'O15', 'O16', 'O16', 'O17', 'O17', 'O18', 'O18', 'O19', 'O19', 'O20', 'O20', 'O21', 'O21', 'O22', 'O22', 'O23', 'O23', 'O24', 'O24', 'O25', 'O25', 'O26', 'O26', 'O27', 'O27', 'O28', 'O28', 'O29', 'O29', 'O30', 'O30', 'O31', 'O31', 'O32', 'O32', 'O33', 'O33', 'O34', 'O34', 'O35', 'O36']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Rb1', 'Pr1', 'Ta1', 'Ta1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O3']`.
  writer = CifWriter(structure)

Structure is perfectly ordered.
Rb1La1Nb2O7
['Rb', 'La', 'Nb', 'O']
Structure is perfectly ordered.
Rb1La1Ta2O7
['Rb', 'La', 'Ta', 'O']
Structure is perfectly ordered.
Rb1Nd1Nb2O7
['Rb', 'Nd', 'Nb', 'O']
Structure is perfectly ordered.
Rb1Nd1Ta2O7
['Rb', 'Nd', 'Ta', 'O']
Structure is perfectly ordered.
Rb1Pr1Ta2O7
['Rb', 'Pr', 'Ta', 'O']
Structure is perfectly ordered.
Rb1Sm1Ta2O7
['Rb', 'Sm', 'Ta', 'O']
Structure is perfectly ordered.
Sr1Nb2Bi2O9
['Sr', 'Nb', 'Bi', 'O']
Structure is perfectly ordered.
Sr1Ta2Bi2O9
['Sr', 'Ta', 'Bi', 'O']
Structure is perfectly ordered.
Sr1Sn1O3
['Sr', 'Sn', 'O']
Structure is perfectly ordered.
Sr1Ti1O3
['Sr', 'Ti', 'O']
Structure is perfectly ordered.
Ti1O2
['Ti', 'O']
Structure is unordered (disordered).
Ti8.5Zn41.5S50
['Ti', 'Zn', 'S']
Partial occupancy detected at [0.44687949 0.90280256 0.83674984]: Ti0.17 Zn0.83
Structure is unordered (disordered).
Ti0.34Zn1.66S2
['Ti', 'Zn', 'S']
Partial occupancy detected at [0.33333333 0.66666667 0.        ]: Ti0.17 Zn0.83

C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Zn0', 'Zn0', 'Zn1', 'Zn1', 'Zn2', 'Zn2', 'Zn3', 'Zn3', 'Zn4', 'Zn4', 'Zn5', 'Zn5', 'Zn6', 'Zn6', 'Zn7', 'Zn7', 'Zn8', 'Zn8', 'Zn9', 'Zn9', 'Zn10', 'Zn10', 'Zn11', 'Zn11', 'Zn12', 'Zn12', 'Zn13', 'Zn13', 'Zn14', 'Zn14', 'Zn15', 'Zn15', 'Zn16', 'Zn16', 'Zn17', 'Zn17', 'Zn18', 'Zn18', 'Zn19', 'Zn19', 'Zn20', 'Zn20', 'Zn21', 'Zn21', 'Zn22', 'Zn22', 'Zn23', 'Zn23', 'Zn24', 'Zn24', 'Zn25', 'Zn25', 'Zn26', 'Zn26', 'Zn27', 'Zn27', 'Zn28', 'Zn28', 'Zn29', 'Zn29', 'Zn30', 'Zn30', 'Zn31', 'Zn31', 'Zn32', 'Zn32', 'Zn33', 'Zn33', 'Zn34', 'Zn34', 'Zn35', 'Zn35', 'Zn36', 'Zn36', 'Zn37', 'Zn37', 'Zn38', 'Zn38', 'Zn39', 'Zn39', 'Zn40', 'Zn40', 'Zn41', 'Zn41', 'Zn42', 'Zn42', 'Zn43', 'Zn43', 'Zn44', 'Zn44', 'Zn45', 'Zn45', 'Zn46', 'Zn46', 'Zn47', 'Zn47', 'Zn48', 'Zn48', 'Zn49', 'Zn49', 'S50', 'S51', 'S52', 'S53', 'S54', 'S55', 'S56', 'S57', 'S58', 'S59', 'S60', 'S61', 'S62', 'S63', 'S64', 'S65', 'S66', 'S67', 'S68', 'S69', 'S70', 'S71', 'S72', 'S73', 'S74', 'S75', 'S76', 'S77', 'S78', 'S79', 'S80', 'S81', 'S82', 'S83', 'S84', 'S85', 'S86', 'S87', 'S88', 'S89', 'S90', 'S91', 'S92', 'S93', 'S94', 'S95', 'S96', 'S97', 'S98', 'S99']`.
  writer = CifWriter(structure)
C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Zn1', 'Zn1', 'Zn1', 'Zn1', 'S1', 'S1']`.
  writer = CifWriter(structure)

Structure is unordered (disordered).
Ti7.5Zn42.5S50
['Ti', 'Zn', 'S']
Partial occupancy detected at [0.44687949 0.90280256 0.83674984]: Ti0.15 Zn0.85
Structure is unordered (disordered).
Ti0.3Zn1.7S2
['Ti', 'Zn', 'S']
Partial occupancy detected at [0.33333333 0.66666667 0.        ]: Ti0.15 Zn0.85
Structure is unordered (disordered).
Ti1Zn9S10
['Ti', 'Zn', 'S']
Partial occupancy detected at [0.44687949 0.90280256 0.83674984]: Ti0.1 Zn0.9
Structure is unordered (disordered).
Ti0.2Zn1.8S2
['Ti', 'Zn', 'S']
Partial occupancy detected at [0.33333333 0.66666667 0.        ]: Ti0.1 Zn0.9
Structure is perfectly ordered.
Zn1Ga2O4
['Zn', 'Ga', 'O']
Structure is perfectly ordered.
Zr1O2
['Zr', 'O']

C:\Users\Nikita\AppData\Local\Temp\ipykernel_13060\3543756238.py:17: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Zr1', 'Zr1', 'Zr1', 'Zr1', 'Zr1', 'Zr1', 'Zr1', 'Zr1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O1', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2', 'O2']`.
  writer = CifWriter(structure)

In [24]:
print(df.shape[0])

100

In [25]:
df

,Perovskite,Rate_standardized,MP_CIF_modified,COD_CIF_modified,Springer_CIF_modified,material_id,formation_energy_per_atom,dft_band_gap,pretty_formula,e_above_hull,elements,cif,spacegroup_number,azure_bulk_modulus,larsen_score_2d,Si_100_mismatch,azure_band_gap,dft_bulk_modulus,dft_poisson_ratio,dft_mag_density
0,Ag2La2Ti3O10,0.006886,mp-6000,1509663,None,None,None,None,La2Ti3Ag2O10,None,"[La, Ti, Ag, O]",# generated using pymatgen\ndata_La2Ti3(AgO5)2...,139,None,None,None,None,None,None,None
1,AgCa2Nb3O10,0.060778,M_MP98,M_COD45,None,None,None,None,Ca2Nb3Ag1O10,None,"[Ca, Nb, Ag, O]",# generated using pymatgen\ndata_Ca2Nb3AgO10\n...,123,None,None,None,None,None,None,None
2,AgLaNb2O7,0.006228,mp-1222828,1509430,None,None,None,None,La1Nb2Ag1O7,None,"[La, Nb, Ag, O]",# generated using pymatgen\ndata_LaNb2AgO7\n_s...,119,None,None,None,None,None,None,None
3,AgSr2Nb3O10,0.037605,M_MP99,M_COD46,None,None,None,None,Sr2Nb3Ag1O10,None,"[Sr, Nb, Ag, O]",# generated using pymatgen\ndata_Sr2Nb3AgO10\n...,123,None,None,None,None,None,None,None
4,Ba5Nb4O15,0.284337,N_MP44,-1,N_Springer14,None,None,None,Ba5Nb4O15,None,"[Ba, Nb, O]",# generated using pymatgen\ndata_Ba5Nb4O15\n_s...,164,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,SrSnO3,3.456790,mp-12867,1521093,None,None,None,None,Sr1Sn1O3,None,"[Sr, Sn, O]",# generated using pymatgen\ndata_SrSnO3\n_symm...,140,None,None,None,None,None,None,None
96,SrTiO3,0.297297,mp-4651,1512124,None,None,None,None,Sr1Ti1O3,None,"[Sr, Ti, O]",# generated using pymatgen\ndata_SrTiO3\n_symm...,140,None,None,None,None,None,None,None
97,TiO2,4.057404,mp-1245098,1010942,None,None,None,None,Ti1O2,None,"[Ti, O]",# generated using pymatgen\ndata_TiO2\n_symmet...,1,None,None,None,None,None,None,None
98,ZnGa2O4,0.008660,mp-5794,4001767,None,None,None,None,Zn1Ga2O4,None,"[Zn, Ga, O]",# generated using pymatgen\ndata_Zn(GaO2)2\n_s...,227,None,None,None,None,None,None,None
99,ZrO2,60.960000,mp-775909,None,sd_0560284,None,None,None,Zr1O2,None,"[Zr, O]",# generated using pymatgen\ndata_ZrO2\n_symmet...,61,None,None,None,None,None,None,None

In [26]:
df.to_csv("checkpoint_material_info.csv")

In [300]:
#df = df.groupby('Perovskite')['Rate_standardized'].mean().reset_index()
#df["Log_rate_standardized"] = np.log(df['Rate_standardized'])
#df["Log_rate"]=df["Log_rate_standardized"]

In [27]:
df

,Perovskite,Rate_standardized,MP_CIF_modified,COD_CIF_modified,Springer_CIF_modified,material_id,formation_energy_per_atom,dft_band_gap,pretty_formula,e_above_hull,elements,cif,spacegroup_number,azure_bulk_modulus,larsen_score_2d,Si_100_mismatch,azure_band_gap,dft_bulk_modulus,dft_poisson_ratio,dft_mag_density
0,Ag2La2Ti3O10,0.006886,mp-6000,1509663,None,None,None,None,La2Ti3Ag2O10,None,"[La, Ti, Ag, O]",# generated using pymatgen\ndata_La2Ti3(AgO5)2...,139,None,None,None,None,None,None,None
1,AgCa2Nb3O10,0.060778,M_MP98,M_COD45,None,None,None,None,Ca2Nb3Ag1O10,None,"[Ca, Nb, Ag, O]",# generated using pymatgen\ndata_Ca2Nb3AgO10\n...,123,None,None,None,None,None,None,None
2,AgLaNb2O7,0.006228,mp-1222828,1509430,None,None,None,None,La1Nb2Ag1O7,None,"[La, Nb, Ag, O]",# generated using pymatgen\ndata_LaNb2AgO7\n_s...,119,None,None,None,None,None,None,None
3,AgSr2Nb3O10,0.037605,M_MP99,M_COD46,None,None,None,None,Sr2Nb3Ag1O10,None,"[Sr, Nb, Ag, O]",# generated using pymatgen\ndata_Sr2Nb3AgO10\n...,123,None,None,None,None,None,None,None
4,Ba5Nb4O15,0.284337,N_MP44,-1,N_Springer14,None,None,None,Ba5Nb4O15,None,"[Ba, Nb, O]",# generated using pymatgen\ndata_Ba5Nb4O15\n_s...,164,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,SrSnO3,3.456790,mp-12867,1521093,None,None,None,None,Sr1Sn1O3,None,"[Sr, Sn, O]",# generated using pymatgen\ndata_SrSnO3\n_symm...,140,None,None,None,None,None,None,None
96,SrTiO3,0.297297,mp-4651,1512124,None,None,None,None,Sr1Ti1O3,None,"[Sr, Ti, O]",# generated using pymatgen\ndata_SrTiO3\n_symm...,140,None,None,None,None,None,None,None
97,TiO2,4.057404,mp-1245098,1010942,None,None,None,None,Ti1O2,None,"[Ti, O]",# generated using pymatgen\ndata_TiO2\n_symmet...,1,None,None,None,None,None,None,None
98,ZnGa2O4,0.008660,mp-5794,4001767,None,None,None,None,Zn1Ga2O4,None,"[Zn, Ga, O]",# generated using pymatgen\ndata_Zn(GaO2)2\n_s...,227,None,None,None,None,None,None,None
99,ZrO2,60.960000,mp-775909,None,sd_0560284,None,None,None,Zr1O2,None,"[Zr, O]",# generated using pymatgen\ndata_ZrO2\n_symmet...,61,None,None,None,None,None,None,None

In [302]:
#idx = df.groupby('Perovskite')['Alcohol_nonzero'].idxmin()  #keeps the row with the lowest value in the Alcohol_nonzero column
#idx

In [28]:
#df = df.loc[idx].copy()
#df.to_csv("checkpoint_material_info_grouped.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Perovskite                 100 non-null    object
 1   Rate_standardized          100 non-null    float64
 2   MP_CIF_modified            95 non-null     object
 3   COD_CIF_modified           92 non-null     object
 4   Springer_CIF_modified      24 non-null     object
 5   material_id                0 non-null      object
 6   formation_energy_per_atom  0 non-null      object
 7   dft_band_gap               0 non-null      object
 8   pretty_formula             100 non-null    object
 9   e_above_hull               0 non-null      object
 10  elements                   100 non-null    object
 11  cif                        100 non-null    object
 12  spacegroup_number          100 non-null    int64
 13  azure_bulk_modulus         0 non-null      object
 14  larsen_score_2d            0 non-null      object
 15  Si_100_mismatch            0 non-null      object
 16  azure_band_gap             0 non-null      object
 17  dft_bulk_modulus           0 non-null      object
 18  dft_poisson_ratio          0 non-null      object
 19  dft_mag_density            0 non-null      object
dtypes: float64(1), int64(1), object(18)
memory usage: 15.8+ KB

# Output dataset formation

In [29]:
print(df.shape[0])
df=df.dropna(subset=['cif'])
print(df.shape[0])

100
100

In [30]:
df['Log_rate']=np.log(df['Rate_standardized'])

In [31]:
output_columns.append('Log_rate')
df = df[output_columns]

In [32]:
df.shape

(100, 16)

In [33]:
df = df.sample(frac=1).reset_index(drop=True)

In [34]:
df.to_csv("mattergen_dataset_for_fine_tuning.csv", index=False)

In [ ]:
ss/0

NameError: name 'ss' is not defined

In [ ]:
name = "train"

In [ ]:
df_ = pd.read_csv(f"Data/Mattergen_dataset/processed/{name}.csv")
df_

,Unnamed: 0,material_id,formation_energy_per_atom,dft_band_gap,pretty_formula,e_above_hull,elements,cif,spacegroup_number,azure_bulk_modulus,larsen_score_2d,Si_100_mismatch,azure_band_gap,dft_bulk_modulus,dft_poisson_ratio,dft_mag_density,Log_rate
0,0,0,NaN,NaN,La1Ti1H12C4N1O4,NaN,"['La', 'Ti', 'H', 'C', 'N', 'O']",# generated using pymatgen\ndata_LaTiH12C4NO4\...,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.596764
1,1,1,NaN,NaN,Nd2Ti3H16C4N2O10,NaN,"['Nd', 'Ti', 'H', 'C', 'N', 'O']",# generated using pymatgen\ndata_Nd2Ti3H16C4(N...,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.854861
2,2,2,NaN,NaN,La1Ti1H1O4,NaN,"['La', 'Ti', 'H', 'O']",# generated using pymatgen\ndata_LaTiHO4\n_sym...,129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.924004
3,3,3,NaN,NaN,La1Nb2H1O7,NaN,"['La', 'Nb', 'H', 'O']",# generated using pymatgen\ndata_LaNb2HO7\n_sy...,123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.613204
4,4,4,NaN,NaN,Nd1Ti1H7C2O5,NaN,"['Nd', 'Ti', 'H', 'C', 'O']",# generated using pymatgen\ndata_NdTiH7C2O5\n_...,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.326302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,61,61,NaN,NaN,Ca2Nb3H1O10,NaN,"['Ca', 'Nb', 'H', 'O']",# generated using pymatgen\ndata_Ca2Nb3HO10\n_...,123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.028544
61,62,62,NaN,NaN,Rb1Sr2Nb3O10,NaN,"['Rb', 'Sr', 'Nb', 'O']",# generated using pymatgen\ndata_RbSr2Nb3O10\n...,123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.851554
62,63,63,NaN,NaN,Nd1Ti1H8C2N1O4,NaN,"['Nd', 'Ti', 'H', 'C', 'N', 'O']",# generated using pymatgen\ndata_NdTiH8C2NO4\n...,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.951608
63,64,64,NaN,NaN,Rb1La1Nb2O7,NaN,"['Rb', 'La', 'Nb', 'O']",# generated using pymatgen\ndata_RbLaNb2O7\n_s...,74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.798880
64,65,65,NaN,NaN,La2Ti3H10C2O12,NaN,"['La', 'Ti', 'H', 'C', 'O']",# generated using pymatgen\ndata_La2Ti3H10(CO6...,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.642122

In [ ]:
df_ = df_.head(95)
df_

,Unnamed: 0,material_id,formation_energy_per_atom,dft_band_gap,pretty_formula,e_above_hull,elements,cif,spacegroup_number,azure_bulk_modulus,larsen_score_2d,Si_100_mismatch,azure_band_gap,dft_bulk_modulus,dft_poisson_ratio,dft_mag_density,Log_rate
0,0.0,0.0,NaN,NaN,Rb1Sr2Nb3O10,NaN,"['Rb', 'Sr', 'Nb', 'O']",# generated using pymatgen\ndata_RbSr2Nb3O10\n...,123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.851554
1,1.0,1.0,NaN,NaN,Nd1Ti1H9C3O5,NaN,"['Nd', 'Ti', 'H', 'C', 'O']",# generated using pymatgen\ndata_NdTiH9C3O5\n_...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.109061
2,2.0,2.0,NaN,NaN,Ca2Nb3H1O10,NaN,"['Ca', 'Nb', 'H', 'O']",# generated using pymatgen\ndata_Ca2Nb3HO10\n_...,123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.028544
3,3.0,3.0,NaN,NaN,Ca2Nb3H12C2N2O10,NaN,"['Ca', 'Nb', 'H', 'C', 'N', 'O']",# generated using pymatgen\ndata_Ca2Nb3H12C2(N...,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.654088
4,4.0,4.0,NaN,NaN,La2Ti2O7,NaN,"['La', 'Ti', 'O']",# generated using pymatgen\ndata_La2Ti2O7\n_sy...,227.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-7.927406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,90.0,90.0,NaN,NaN,Nd1Ti1H16C6N1O4,NaN,"['Nd', 'Ti', 'H', 'C', 'N', 'O']",# generated using pymatgen\ndata_NdTiH16C6NO4\...,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.644755
91,91.0,91.0,NaN,NaN,La2Ti3H22C8O12,NaN,"['La', 'Ti', 'H', 'C', 'O']",# generated using pymatgen\ndata_La2Ti3H22(C2O...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.473433
92,92.0,92.0,NaN,NaN,K1La1Nb2O7,NaN,"['K', 'La', 'Nb', 'O']",# generated using pymatgen\ndata_KLaNb2O7\n_sy...,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.525257
93,93.0,93.0,NaN,NaN,K2La2Ti3O10,NaN,"['K', 'La', 'Ti', 'O']",# generated using pymatgen\ndata_K2La2Ti3O10\n...,139.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.095464
94,94.0,94.0,NaN,NaN,La2Ti3H12C2N2O10,NaN,"['La', 'Ti', 'H', 'C', 'N', 'O']",# generated using pymatgen\ndata_La2Ti3H12C2(N...,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.960424

In [ ]:
df.to_csv(f"Data/Mattergen_dataset/processed/{name}.csv")