In [207]:
from pymatgen.core import Lattice, Structure
import pandas as pd
import numpy as np
import plotly as pt
import seaborn as sns
#!pip install pymatgen
#!pip install mp_api
import requests
import json
import matplotlib.pyplot as plt
import re

In [208]:
from matminer.featurizers.composition import ElementProperty
from matminer.featurizers.composition import ValenceOrbital
from pymatgen.core.composition import Composition

In [ ]:
from mp_api.client import MPRester
API_KEY = ""
mpr = MPRester(API_KEY)

# Initialization

In [377]:
import joblib

title="Log_rate"  #'Bandgap  #Log_rate
scaler = joblib.load(f"{title}_scaler.joblib")
selector = joblib.load(f"{title}_selector.joblib")
cat_boost_model = joblib.load(f"{title}_regression_model.joblib")

print("Pipeline reloaded!")

Pipeline reloaded!

In [378]:
#Bandgap

avg_calc_temp = 1267.106509
avg_calc_time = 22
avg_surf_area = 9.371599670116556	
min_wl = 200

#****************************
#Log_rate
if(title=="Log_rate"):
    avg_calc_temp = 1296.237241
    avg_calc_time = 19.567693	
    avg_surf_area = 10.37065568513124	
    min_wl = 200

ionic_radii={"H+":0.02}

In [379]:
candidate_cif_folder = "generated_cifs"

from pathlib import Path
#from pymatgen.core import Structure

# Define the directory path
folder_path = Path(candidate_cif_folder)

data_rows = []
# Iterate over all files ending in .cif
for file_path in folder_path.glob("*.cif"):
    #print(f"Processing: {file_path.name}")
    
    # Example: Integration with your pymatgen code
    structure = Structure.from_file(file_path)
    formula = structure.composition.formula
    #print(f"Formula: {structure.composition.formula}")

    row_data = {
            "Formula": formula,
            "Composition": structure.composition,
            "Path": file_path
        }
    data_rows.append(row_data)

df_candidates = pd.DataFrame(data_rows)

if(title=='Log_rate'):
    df_candidates = pd.read_excel(f"{candidate_cif_folder}/candidates_after_inference_Bandgap.xlsx")
df_candidates

,Unnamed: 0,Formula,Composition,Path,avg s valence electrons,avg p valence electrons,avg d valence electrons,avg f valence electrons,frac s valence electrons,frac p valence electrons,frac d valence electrons,frac f valence electrons,Bandgap_predicted
0,0,Sr3 Ca1 Zn1 O5,Sr3 Ca1 Zn1 O5,generated_cifs\gen_10_Sr3CaZnO5.cif,2.000000,2.000000,1.000000,0.0,0.400000,0.400000,0.200000,0.000000,2.610747
1,1,Ca3 Nb1 O3,Ca3 Nb1 O3,generated_cifs\gen_11_Ca3NbO3.cif,1.857143,1.714286,0.571429,0.0,0.448276,0.413793,0.137931,0.000000,2.125691
2,2,Sr7 Ca1 O2,Sr7 Ca1 O2,generated_cifs\gen_12_Sr7CaO2.cif,2.000000,0.800000,0.000000,0.0,0.714286,0.285714,0.000000,0.000000,2.915892
3,3,Ca6 P2 O2,Ca6 P2 O2,generated_cifs\gen_13_Ca3PO.cif,2.000000,1.400000,0.000000,0.0,0.588235,0.411765,0.000000,0.000000,2.840694
4,4,Ca2 O2,Ca2 O2,generated_cifs\gen_14_CaO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.424377
5,5,Ca1 Hg1 O2,Ca1 Hg1 O2,generated_cifs\gen_15_CaHgO2.cif,2.000000,2.000000,2.500000,3.5,0.200000,0.200000,0.250000,0.350000,2.675027
6,6,Ca4 O2,Ca4 O2,generated_cifs\gen_16_Ca2O.cif,2.000000,1.333333,0.000000,0.0,0.600000,0.400000,0.000000,0.000000,2.768946
7,7,Ca5 O3,Ca5 O3,generated_cifs\gen_17_Ca5O3.cif,2.000000,1.500000,0.000000,0.0,0.571429,0.428571,0.000000,0.000000,2.911306
8,8,Sr6 Ca1 Nb2 Zn1 O6,Sr6 Ca1 Nb2 Zn1 O6,generated_cifs\gen_18_Sr6CaNb2ZnO6.cif,1.875000,1.500000,1.125000,0.0,0.416667,0.333333,0.250000,0.000000,2.009304
9,9,Sr5 Nb3 O7,Sr5 Nb3 O7,generated_cifs\gen_19_Sr5Nb3O7.cif,1.800000,1.866667,0.800000,0.0,0.402985,0.417910,0.179104,0.000000,2.297273
10,10,Sr6 Ca1 Pb1 O2,Sr6 Ca1 Pb1 O2,generated_cifs\gen_1_Sr6CaPbO2.cif,2.000000,1.000000,1.000000,1.4,0.370370,0.185185,0.185185,0.259259,2.437983
11,11,Sr2 Ca1 Nb2 Br1 O6,Sr2 Ca1 Nb2 Br1 O6,generated_cifs\gen_20_Sr2CaNb2BrO6.cif,1.833333,2.416667,1.500000,0.0,0.318841,0.420290,0.260870,0.000000,2.551909
12,12,Sr1 Ca1 O2,Sr1 Ca1 O2,generated_cifs\gen_21_SrCaO2.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.242396
13,13,Ca4 O2,Ca4 O2,generated_cifs\gen_22_Ca2O.cif,2.000000,1.333333,0.000000,0.0,0.600000,0.400000,0.000000,0.000000,2.772827
14,14,Ca3 O1,Ca3 O1,generated_cifs\gen_23_Ca3O.cif,2.000000,1.000000,0.000000,0.0,0.666667,0.333333,0.000000,0.000000,2.908506
15,15,Sr1 Ca6 Nb2 O7,Sr1 Ca6 Nb2 O7,generated_cifs\gen_24_SrCa6Nb2O7.cif,1.875000,1.750000,0.500000,0.0,0.454545,0.424242,0.121212,0.000000,2.293506
16,16,Sr4 Ca2 O6,Sr4 Ca2 O6,generated_cifs\gen_25_Sr2CaO3.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.231635
17,17,Ca5 Fe1 O6,Ca5 Fe1 O6,generated_cifs\gen_26_Ca5FeO6.cif,2.000000,2.000000,0.500000,0.0,0.444444,0.444444,0.111111,0.000000,2.884021
18,18,Ca3 Bi1 O1,Ca3 Bi1 O1,generated_cifs\gen_27_Ca3BiO.cif,2.000000,1.400000,2.000000,2.8,0.243902,0.170732,0.243902,0.341463,2.409360
19,19,Sr2 O2,Sr2 O2,generated_cifs\gen_28_SrO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.127574
20,20,Ca4 O4,Ca4 O4,generated_cifs\gen_29_CaO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.424377
21,21,Ca2 O2,Ca2 O2,generated_cifs\gen_2_CaO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.424377
22,22,Sr2 Ca1 Nb1 O6,Sr2 Ca1 Nb1 O6,generated_cifs\gen_30_Sr2CaNbO6.cif,1.900000,2.400000,0.400000,0.0,0.404255,0.510638,0.085106,0.000000,3.187078
23,23,Sr1 Nb2 O5,Sr1 Nb2 O5,generated_cifs\gen_31_SrNb2O5.cif,1.750000,2.500000,1.000000,0.0,0.333333,0.476190,0.190476,0.000000,2.857224
24,24,Sr3 Ca3 O5 F1,Sr3 Ca3 O5 F1,generated_cifs\gen_32_Sr3Ca3O5F.cif,2.000000,2.083333,0.000000,0.0,0.489796,0.510204,0.000000,0.000000,3.315961
25,25,Sr12 Ca4 Zn1 O3,Sr12 Ca4 Zn1 O3,generated_cifs\gen_3_Sr12Ca4ZnO3.cif,2.000000,0.600000,0.500000,0.0,0.645161,0.193548,0.161290,0.000000,2.397198
26,26,Ca3 O2 F1,Ca3 O2 F1,generated_cifs\gen_4_Ca3O2F.cif,2.000000,2.166667,0.000000,0.0,0.480000,0.520000,0.000000,0.000000,3.294944
27,27,La1 Nb2 H2 O7,La1 Nb2 H2 O7,generated_cifs\gen_5_LaNb2H2O7.cif,1.666667,2.333333,0.750000,0.0,0.350877,0.491228,0.157895,0.000000,2.724639
28,28,Ca4 O4,Ca4 O4,generated_cifs\gen_6_CaO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.424377
29,29,Ca2 O2,Ca2 O2,generated_cifs\gen_7_CaO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.424377
30,30,Ca2 O2,Ca2 O2,generated_cifs\gen_8_CaO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.424377
31,31,Ca2 O2,Ca2 O2,generated_cifs\gen_9_CaO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.428173

In [380]:
print(df_candidates['Formula'].to_string(index=False))

    Sr3 Ca1 Zn1 O5
        Ca3 Nb1 O3
        Sr7 Ca1 O2
         Ca6 P2 O2
            Ca2 O2
        Ca1 Hg1 O2
            Ca4 O2
            Ca5 O3
Sr6 Ca1 Nb2 Zn1 O6
        Sr5 Nb3 O7
    Sr6 Ca1 Pb1 O2
Sr2 Ca1 Nb2 Br1 O6
        Sr1 Ca1 O2
            Ca4 O2
            Ca3 O1
    Sr1 Ca6 Nb2 O7
        Sr4 Ca2 O6
        Ca5 Fe1 O6
        Ca3 Bi1 O1
            Sr2 O2
            Ca4 O4
            Ca2 O2
    Sr2 Ca1 Nb1 O6
        Sr1 Nb2 O5
     Sr3 Ca3 O5 F1
   Sr12 Ca4 Zn1 O3
         Ca3 O2 F1
     La1 Nb2 H2 O7
            Ca4 O4
            Ca2 O2
            Ca2 O2
            Ca2 O2

In [381]:
vo_feat = ValenceOrbital()

In [382]:
if(title=='Bandgap'):
    df_candidates = vo_feat.featurize_dataframe(df_candidates, col_id='Composition')

In [383]:
#electron = ElementProperty()
#df_candidates = electron.featurize_dataframe(df_candidates, col_id='Composition')

In [384]:
df_candidates.columns

Index(['Unnamed: 0', 'Formula', 'Composition', 'Path',
       'avg s valence electrons', 'avg p valence electrons',
       'avg d valence electrons', 'avg f valence electrons',
       'frac s valence electrons', 'frac p valence electrons',
       'frac d valence electrons', 'frac f valence electrons',
       'Bandgap_predicted'],
      dtype='object')

In [385]:
from pymatgen.core.periodic_table import Element

#calculate malliken electronegativity of an element
def get_mulliken_en(element_symbol):
    el = Element(element_symbol)
    IE = el.ionization_energies[0]  # First ionization energy in eV
    EA = el.electron_affinity       # Electron affinity in eV

    if IE is None or EA is None:
        return None

    return (IE + EA) / 2

def calc_average_electronegativity(formula):
  # Example: For Fe2O3
  comp = Composition(formula)
  # Weighted mean electronegativity
  total_atoms = comp.num_atoms
  mean_en = sum(
    comp[el] / total_atoms * get_mulliken_en(el)
    for el in comp.elements)
  return mean_en

In [386]:
calc_average_electronegativity("Ti O2")

6.177000159666666

In [387]:
def split_formula(formula):
  output={}
  elements_with_indexes = formula.split()
  for el in elements_with_indexes:
    #match = re.match(r"([A-Za-z]+)(\d+)$", el)
    match = re.match(r"([A-Za-z]+)(\d+(?:\.\d+)?)$", el)
    if match:
      output[match.group(1)]=float(match.group(2))
    else:
      output[ el]=float(1)
  return output

def get_valence_electrons_number(hill_fomula):
  split = split_formula(hill_fomula)
  print(split)
  v = split.get("O")
  if v == None:
    return 0
  else:
    return 2*v

In [388]:
get_valence_electrons_number("Ti O2")

{'Ti': 1.0, 'O': 2.0}

4.0

In [389]:
elements_oxidation_states = {
"Pu":4,
"H":1,
"Li":1,
"Be":2,
"B":3,
"C":4,
"N":-3,
"O":-2,
"F":-1,
"Na":1,
"Mg":2,
"Al":3,
"Si":4,
"P":5,
"S":-2,
"Cl":-1,
"K":1,
"Ca":2,
"Sc":3,
"Ti":4,
"V":5,
"Cr":6,
"Mn":2,
"Fe":2,
"Co":2,
"Ni":2,
"Cu":2,
"Zn":2,
"Ga":3,
"Ge":4,
"As":5,
"Se":6,
"Br":-1,
"Rb":1,
"Sr":2,
"Y":3,
"Zr":4,
"Nb":5,
"Mo":6,
"Tc":7,
"Ru":4,
"Rh":3,
"Pd":2,
"Ag":1,
"Cd":2,
"In":3,
"Sn":4,
"Sb":5,
"Te":6,
"I":-1,
"Cs":1,
"Ba":2,
"La":3,
"Ce":4,
"Pr":3,
"Nd":3,
"Pm":3,
"Sm":3,
"Eu":3,
"Gd":3,
"Tb":3,
"Dy":3,
"Ho":3,
"Er":3,
"Tm":3,
"Yb":3,
"Lu":3,
"Hf":4,
"Ta":5,
"W":6,
"Re":7,
"Os":8,
"Ir":4,
"Pt":4,
"Au":3,
"Hg":2,
"Tl":1,
"Pb":2,
"Bi":3,
"Po":6,
"At":7,
"Th":4,
"Pa":5,
"U":6,
"Np":7,
"Xe":0,
}

In [390]:
from pymatgen.core import Structure
from pymatgen.analysis.local_env import ValenceIonicRadiusEvaluator
from pymatgen.core.periodic_table import Species

unresolved_compunds = []

def get_packing_fraction_from_formula_and_cell_volume(hill_formula, V, Z):
    if V==0 or np.isnan(V) or Z==0 or np.isnan(Z):
        return np.nan
    print("---------------------------------------------")
    print("Enter!")
    print(hill_formula)
    print(V)
    print(Z)
    comp = Composition(hill_formula)

    #oxi_guesses = comp.oxi_state_guesses()
    #if(len(oxi_guesses)==0):
    #   oxi_guesses = difficult_compunds_oxidation_states.get(hill_formula)
    #  if(oxi_guesses==None):
    #    unresolved_compunds.append(hill_formula)
    #    return np.nan
    #else:
    #  oxi_guesses = oxi_guesses[0]

    V_ions_formula=0
    for el, amt in comp.items():
        symbol = el.symbol
        #el_oxidation_state = oxi_guesses[symbol]
        el_oxidation_state=3
        if symbol in elements_oxidation_states:
          el_oxidation_state = elements_oxidation_states[symbol]
        print("Element:", symbol)
        print("Element ox state:", el_oxidation_state)
        specie = Species(symbol,el_oxidation_state)
        r = specie.ionic_radius
        if(r==np.nan or r==None):
          ion_formula = symbol
          if(el_oxidation_state!=0 and el_oxidation_state!=1 and el_oxidation_state!=-1):
             ion_formula =  ion_formula+str(el_oxidation_state)
          if(el_oxidation_state>0):
            ion_formula =  ion_formula+str("+")
          if(el_oxidation_state<0):
            ion_formula =  ion_formula+str("-")
          print("Local ionic radii table request for ",ion_formula)
          r= ionic_radii.get(ion_formula)
          if(r==None):
            r=0
        print("r: ", r)
        V_ion = (4/3) * np.pi * r**3
        V_ions_formula += (V_ion*amt)
        print(el," ",amt)

    packing_fraction= Z*V_ions_formula/V
    return packing_fraction
    print("Output!")

In [391]:
get_packing_fraction_from_formula_and_cell_volume("Ti O2", 1, 1)

---------------------------------------------
Enter!
Ti O2
1
1
Element: Ti
Element ox state: 4
r:  0.745 ang
Ti   1.0
Element: O
Element ox state: -2
r:  1.26 ang
O   2.0

18.490348835521182

In [392]:
def count_oxigen(formula):
  if formula is None:
    return 0
  print(formula)
  comp = Composition(formula)

  # Get number of oxygen atoms
  oxygen_count = comp.get_el_amt_dict().get("O", 0)
  print(oxygen_count)
  return oxygen_count

In [393]:
#from matminer.featurizers.composition import ElementProperty
#ep_feat = ElementProperty.from_preset(preset_name="magpie")

#comp = Composition("Nd3Lu2Tl1O4")
#feature_values = ep_feat.featurize(comp)

#feature_names = ep_feat.feature_labels()
#composition_features = dict(zip(feature_names, feature_values))

#print(f"Computed {len(composition_features)} features for single composition.")
#print("Example feature (Mulliken EN):", composition_features.get("MagpieData minimum Electronegativity"))
#print(feature_names)

comp = Composition("Nd3Lu2Tl1O4")
feature_names = vo_feat.feature_labels()
print(feature_names)
feature_values = vo_feat.featurize(comp)
print(feature_values)

['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(2.0), np.float64(1.7), np.float64(1.2), np.float64(5.4), np.float64(0.1941747572815534), np.float64(0.16504854368932037), np.float64(0.11650485436893203), np.float64(0.5242718446601942)]

In [394]:
def predict_candidate_from_cif(cif_path, bandgap, load_cif_from_Data = False,d_A= 0):
    #if(bandgap==None or np.isnan(bandgap) or bandgap<=0):
    #    return None
    print("Predicting for: ", cif_path)
    cif_path = str(cif_path)
    #print("Predicting for: ", cif_path)
    #try:
    candidate_feature_dict={}
    structure = None

    if(cif_path == 'M_MP491'):
        c=0
    
    try:
        if cif_path.startswith("mp-"):
            structure = mpr.get_structure_by_material_id(cif_path)
            print("loading cif from web")
        elif(load_cif_from_Data):
            structure = Structure.from_file(f"Data/CIF/{cif_path}.cif")
            print("loading cif locally from DATA")
        else:
            print("loading cif locally")
            structure = Structure.from_file(cif_path)
            print("loadied cif locally")
        if structure is None:
            print("Could not read structure from CIF file.")
            return None
    except:
        return np.nan
    print("Structure is loaded")
    composition = structure.composition
    formula = composition.formula
    print(formula) 

    candidate_feature_dict['CalcT(K)'] = avg_calc_temp
    candidate_feature_dict['Calc time (h)'] = avg_calc_time
    candidate_feature_dict['Promoter, w%'] = 0
    candidate_feature_dict['Surface area, m2/g'] = avg_surf_area
    candidate_feature_dict['Alcohol, %'] = 1
    candidate_feature_dict['Power, W'] = 1
    candidate_feature_dict['Wave length min, nm'] = min_wl
    candidate_feature_dict['Promotion method_PD'] = True
    candidate_feature_dict['Promoter_Pt'] = True
    candidate_feature_dict['Promoter_Rh'] = False
    candidate_feature_dict['Combined feature'] = 1*1*1*1
    if(np.isnan(d_A)):
        print("d,A = NaN")
        candidate_feature_dict['d,A'] = 0
    else:
        candidate_feature_dict['d,A'] = d_A
    candidate_feature_dict['Temperature, K'] = 298
    candidate_feature_dict['Nitrogen'] = False
    candidate_feature_dict['Prep Method_SSR'] = True

    #avg_d_valence_electrons = df_candidates.loc[df_candidates["Formula"] == formula, "avg d valence electrons"].item()
    #print("avg d elect: ",  avg_d_valence_electrons)
    #candidate_feature_dict['avg d valence electrons'] =  avg_d_valence_electrons

    #candidate_feature_dict['avg s valence electrons'] =  df_candidates.loc[df_candidates["Formula"] == formula, "avg s valence electrons"].item()
    #candidate_feature_dict['avg p valence electrons'] =  df_candidates.loc[df_candidates["Formula"] == formula, "avg p valence electrons"].item()
    #candidate_feature_dict['avg f valence electrons'] =  df_candidates.loc[df_candidates["Formula"] == formula, "avg f valence electrons"].item()

    #candidate_feature_dict['frac s valence electrons'] =  df_candidates.loc[df_candidates["Formula"] == formula, "frac s valence electrons"].item()
    #candidate_feature_dict['frac p valence electrons'] =  df_candidates.loc[df_candidates["Formula"] == formula, "frac p valence electrons"].item()
    #candidate_feature_dict['frac f valence electrons'] =  df_candidates.loc[df_candidates["Formula"] == formula, "frac f valence electrons"].item()

    feature_names = vo_feat.feature_labels()
    print(feature_names)
    feature_values = vo_feat.featurize(composition)
    print(feature_values)
    candidate_vo_feature_dict={}
    candidate_vo_feature_dict.update(zip(feature_names, feature_values))

    for f in feature_names:
        if f in candidate_vo_feature_dict:
            candidate_feature_dict[f]=candidate_vo_feature_dict[f]
        else:
            print(" error adding feature ", f, " to candidate feature dict")
            raise ValueError(" error adding feature ", f, " to candidate feature dict")

    #candidate_feature_dict['Bandgap, eV'] = avg_bandgap
    candidate_feature_dict['Bandgap, eV'] = bandgap

    #try:
    electronegativity = calc_average_electronegativity(formula)
    #print('electronegativity: ',electronegativity)
    candidate_feature_dict['Average Mulliken electronegativity']=electronegativity

    valence_electrons = get_valence_electrons_number(formula)
    #print('valence_electrons: ',valence_electrons)
    candidate_feature_dict['Valence electrons']=valence_electrons

    oxygen_count = count_oxigen(formula)
    V = structure.volume
    Z = structure.composition.num_atoms / structure.composition.reduced_composition.num_atoms
    oxygen_conc = Z*oxygen_count/V
    candidate_feature_dict['Oxygen_concentration avg']=oxygen_conc

    packing_fraction = get_packing_fraction_from_formula_and_cell_volume(formula, V, Z)
    #print('packing_fraction: ',packing_fraction)
    candidate_feature_dict['Packing fraction avg']=packing_fraction
    candidate_feature_dict['Valence Electrons Density avg'] = valence_electrons/V

    print("candidate_feature_dict: ", candidate_feature_dict)
    print("Scaling...")
    X_before_scaler = np.zeros(len(scaler.feature_names_in_))
    #X_before_scaler = np.full(len(scaler.feature_names_in_), np.nan)
    #filling vectors
    for i in range(len(scaler.feature_names_in_)):
        f= scaler.feature_names_in_[i]
        if f in candidate_feature_dict:
            X_before_scaler[i]=candidate_feature_dict[f]
    #for i in range(len(scaler.feature_names_out_)):
    #    f= scaler.feature_names_out_[i] 
    #    if f not in candidate_feature_dict:
    #        print(f," not in candidate dictionary but is required by selector")
    print("len(scaler.feature_names_in_): ", len(scaler.feature_names_in_))
    print("scaler.feature_names_in_: ", scaler.feature_names_in_)
    print("X_before_scaler: ", X_before_scaler)
    X_after_scaler = scaler.transform(X_before_scaler.reshape(1, -1))
    print("X_after_scaler: ", X_after_scaler)
    X_after_selector = selector.transform(X_after_scaler)

    selected_features = selector.get_feature_names_out(scaler.feature_names_in_)
    print(f"The selector selected {len(selected_features)} features:")
    print(selected_features)
    for f in selected_features:
        if f not in candidate_feature_dict:
            print(f," is not in candidate dictionary but is required by selector")
            raise ValueError(f," is not in candidate dictionary but is required by selector")

    print("X_after_selector: ", X_after_selector)
    X_after_selector=X_after_selector[0]
    vec = X_after_selector
    print(vec)
    prediction = cat_boost_model.predict([vec])[0]
    print("Prediction: ", prediction)
    return prediction
    #except(Exception) as e:
    #    print("Error during prediction: ", e)
    #    return None

In [395]:
predict_candidate_from_cif("M_MP491", 4,True,30)

Predicting for:  M_MP491
loading cif locally from DATA
Structure is loaded
Nd2 Ti3 H2 O10
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(1.8823529411764706), np.float64(2.3529411764705883), np.float64(0.35294117647058826), np.float64(0.47058823529411764), np.float64(0.37209302325581395), np.float64(0.4651162790697675), np.float64(0.06976744186046513), np.float64(0.09302325581395349)]
{'Nd': 2.0, 'Ti': 3.0, 'H': 2.0, 'O': 10.0}
Nd2 Ti3 H2 O10
10.0
---------------------------------------------
Enter!
Nd2 Ti3 H2 O10
229.90248606119223
1.0
Element: Nd
Element ox state: 3
r:  1.123 ang
Nd   2.0
Element: Ti
Element ox state: 4
r:  0.745 ang
Ti   3.0
Element: H
Element ox state: 1
Local ionic radii table request for  H+
r:  0.02
H   2.0
Element: O
Element ox state: -2
r:  1.26 ang
O   10.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 30, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(1.8823529411764706), 'avg p valence electrons': np.float64(2.3529411764705883), 'avg d valence electrons': np.float64(0.35294117647058826), 'avg f valence electrons': np.float64(0.47058823529411764), 'frac s valence electrons': np.float64(0.37209302325581395), 'frac p valence electrons': np.float64(0.4651162790697675), 'frac d valence electrons': np.float64(0.06976744186046513), 'frac f valence electrons': np.float64(0.09302325581395349), 'Bandgap, eV': 4, 'Average Mulliken electronegativity': 6.219203557923647, 'Valence electrons': 20.0, 'Oxygen_concentration avg': 0.043496702325082036, 'Packing fraction avg': 0.4386749670240664, 'Valence Electrons Density avg': 0.08699340465016407}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [4.00000000e+00 3.00000000e+01 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 1.88235294e+00 2.35294118e+00 3.52941176e-01 4.70588235e-01
 3.72093023e-01 4.65116279e-01 6.97674419e-02 9.30232558e-02
 6.21920356e+00 2.00000000e+01 8.69934047e-02 4.34967023e-02
 4.38674967e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 7.06666667e-01  8.62068966e-01  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   7.98319328e-01  5.41176471e-01  7.95717912e-02  9.41176471e-02
   5.39751217e-01  8.63201094e-01  1.85858314e-01  2.25913621e-01
   5.23030056e-01  4.21052632e-01  6.07557835e-01  6.07557835e-01
   5.55977232e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[7.06666667e-01 8.62068966e-01 5.88026601e-01 9.78384650e-02
  0.00000000e+00 4.89444451e-02 1.11111111e-02 0.00000000e+00
  2.22222222e-01 7.98319328e-01 5.41176471e-01 7.95717912e-02
  9.41176471e-02 5.39751217e-01 5.23030056e-01 4.21052632e-01
  5.55977232e-01 1.00000000e+00 0.00000000e+00 1.80360541e-05]]
[7.06666667e-01 8.62068966e-01 5.88026601e-01 9.78384650e-02
 0.00000000e+00 4.89444451e-02 1.11111111e-02 0.00000000e+00
 2.22222222e-01 7.98319328e-01 5.41176471e-01 7.95717912e-02
 9.41176471e-02 5.39751217e-01 5.23030056e-01 4.21052632e-01
 5.55977232e-01 1.00000000e+00 0.00000000e+00 1.80360541e-05]
Prediction:  8.629001720005386

C:\Users\Nikita\AppData\Local\Temp\ipykernel_8248\3708692272.py:36: UserWarning: No ionic radius for H+!
  r = specie.ionic_radius
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(

np.float64(8.629001720005386)

In [396]:
predict_candidate_from_cif("M_MP491", 4, True, np.nan)

Predicting for:  M_MP491
loading cif locally from DATA
Structure is loaded
Nd2 Ti3 H2 O10
d,A = NaN
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(1.8823529411764706), np.float64(2.3529411764705883), np.float64(0.35294117647058826), np.float64(0.47058823529411764), np.float64(0.37209302325581395), np.float64(0.4651162790697675), np.float64(0.06976744186046513), np.float64(0.09302325581395349)]
{'Nd': 2.0, 'Ti': 3.0, 'H': 2.0, 'O': 10.0}
Nd2 Ti3 H2 O10
10.0
---------------------------------------------
Enter!
Nd2 Ti3 H2 O10
229.90248606119223
1.0
Element: Nd
Element ox state: 3
r:  1.123 ang
Nd   2.0
Element: Ti
Element ox state: 4
r:  0.745 ang
Ti   3.0
Element: H
Element ox state: 1
Local ionic radii table request for  H+
r:  0.02
H   2.0
Element: O
Element ox state: -2
r:  1.26 ang
O   10.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(1.8823529411764706), 'avg p valence electrons': np.float64(2.3529411764705883), 'avg d valence electrons': np.float64(0.35294117647058826), 'avg f valence electrons': np.float64(0.47058823529411764), 'frac s valence electrons': np.float64(0.37209302325581395), 'frac p valence electrons': np.float64(0.4651162790697675), 'frac d valence electrons': np.float64(0.06976744186046513), 'frac f valence electrons': np.float64(0.09302325581395349), 'Bandgap, eV': 4, 'Average Mulliken electronegativity': 6.219203557923647, 'Valence electrons': 20.0, 'Oxygen_concentration avg': 0.043496702325082036, 'Packing fraction avg': 0.4386749670240664, 'Valence Electrons Density avg': 0.08699340465016407}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [4.00000000e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 1.88235294e+00 2.35294118e+00 3.52941176e-01 4.70588235e-01
 3.72093023e-01 4.65116279e-01 6.97674419e-02 9.30232558e-02
 6.21920356e+00 2.00000000e+01 8.69934047e-02 4.34967023e-02
 4.38674967e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 7.06666667e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   7.98319328e-01  5.41176471e-01  7.95717912e-02  9.41176471e-02
   5.39751217e-01  8.63201094e-01  1.85858314e-01  2.25913621e-01
   5.23030056e-01  4.21052632e-01  6.07557835e-01  6.07557835e-01
   5.55977232e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[7.06666667e-01 0.00000000e+00 5.88026601e-01 9.78384650e-02
  0.00000000e+00 4.89444451e-02 1.11111111e-02 0.00000000e+00
  2.22222222e-01 7.98319328e-01 5.41176471e-01 7.95717912e-02
  9.41176471e-02 5.39751217e-01 5.23030056e-01 4.21052632e-01
  5.55977232e-01 1.00000000e+00 0.00000000e+00 1.80360541e-05]]
[7.06666667e-01 0.00000000e+00 5.88026601e-01 9.78384650e-02
 0.00000000e+00 4.89444451e-02 1.11111111e-02 0.00000000e+00
 2.22222222e-01 7.98319328e-01 5.41176471e-01 7.95717912e-02
 9.41176471e-02 5.39751217e-01 5.23030056e-01 4.21052632e-01
 5.55977232e-01 1.00000000e+00 0.00000000e+00 1.80360541e-05]
Prediction:  6.704713886121749

C:\Users\Nikita\AppData\Local\Temp\ipykernel_8248\3708692272.py:36: UserWarning: No ionic radius for H+!
  r = specie.ionic_radius
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(

np.float64(6.704713886121749)

# Inference

In [397]:
predict_candidate_from_cif("generated_cifs/gen_32_KLaO2.cif", 4, False)

Predicting for:  generated_cifs/gen_32_KLaO2.cif
loading cif locally

nan

In [398]:
def predict_candidate_bandgap_from_cif(cif):
    return predict_candidate_from_cif(cif,0)

In [399]:
def predict_candidate_log_rate_from_cif(row):
    cif = row['Path']
    bandgap = row['Bandgap_predicted']
    output = 0
    try:
        output = predict_candidate_from_cif(cif,bandgap, False)  #True - read from Data, False - read generated samples
    except:
        output = np.nan
    return output

In [400]:
s/0

NameError: name 's' is not defined

In [401]:
predicted_column = f"{title}_predicted"

if(title=="Log_rate"):
    df_candidates[predicted_column] = df_candidates.apply(predict_candidate_log_rate_from_cif,axis=1)
else:
    df_candidates[predicted_column] = df_candidates["Path"].apply(predict_candidate_bandgap_from_cif)

Predicting for:  generated_cifs\gen_10_Sr3CaZnO5.cif
loading cif locally
loadied cif locally
Structure is loaded
Sr3 Ca1 Zn1 O5
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(2.0), np.float64(2.0), np.float64(1.0), np.float64(0.0), np.float64(0.4), np.float64(0.4), np.float64(0.2), np.float64(0.0)]
{'Sr': 3.0, 'Ca': 1.0, 'Zn': 1.0, 'O': 5.0}
Sr3 Ca1 Zn1 O5
5.0
---------------------------------------------
Enter!
Sr3 Ca1 Zn1 O5
164.90543861304312
1.0
Element: Sr
Element ox state: 2
r:  1.32 ang
Sr   3.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   1.0
Element: Zn
Element ox state: 2
r:  0.88 ang
Zn   1.0
Element: O
Element ox state: -2
r:  1.26 ang
O   5.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(2.0), 'avg p valence electrons': np.float64(2.0), 'avg d valence electrons': np.float64(1.0), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.4), 'frac p valence electrons': np.float64(0.4), 'frac d valence electrons': np.float64(0.2), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 2.61074687212107, 'Average Mulliken electronegativity': 5.37742718575, 'Valence electrons': 10.0, 'Oxygen_concentration avg': 0.03032040690745616, 'Packing fraction avg': 0.4842681246165718, 'Valence Electrons Density avg': 0.06064081381491232}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [2.61074687e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 2.00000000e+00 2.00000000e+00 1.00000000e+00 0.00000000e+00
 4.00000000e-01 4.00000000e-01 2.00000000e-01 0.00000000e+00
 5.37742719e+00 1.00000000e+01 6.06408138e-02 3.03204069e-02
 4.84268125e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 3.36199166e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   1.00000000e+00  4.00000000e-01  2.49530957e-01  0.00000000e+00
   6.04651163e-01  6.07843137e-01  6.66589595e-01  0.00000000e+00
  -1.71726461e-01  1.57894737e-01  3.60698012e-01  3.60698012e-01
   6.33830317e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[ 3.36199166e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
   2.22222222e-01  1.00000000e+00  4.00000000e-01  2.49530957e-01
   0.00000000e+00  6.04651163e-01 -1.71726461e-01  1.57894737e-01
   6.33830317e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]]
[ 3.36199166e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
  0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
  2.22222222e-01  1.00000000e+00  4.00000000e-01  2.49530957e-01
  0.00000000e+00  6.04651163e-01 -1.71726461e-01  1.57894737e-01
  6.33830317e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]
Prediction:  7.910820828950594
Predicting for:  generated_cifs\gen_11_Ca3NbO3.cif
loading cif locally
loadied cif locally
Structure is loaded
Ca3 Nb1 O3
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(1.8571428571428572), np.float64(1.7142857142857142), np.float64(0.5714285714285714), np.float64(0.0), np.float64(0.44827586206896547), np.float64(0.4137931034482758), np.float64(0.1379310344827586), np.float64(0.0)]
{'Ca': 3.0, 'Nb': 1.0, 'O': 3.0}
Ca3 Nb1 O3
3.0
---------------------------------------------
Enter!
Ca3 Nb1 O3
110.13178422684022
1.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   3.0
Element: Nb
Element ox state: 5
r:  0.78 ang
Nb   1.0
Element: O
Element ox state: -2
r:  1.26 ang
O   3.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(1.8571428571428572), 'avg p valence electrons': np.float64(1.7142857142857142), 'avg d valence electrons': np.float64(0.5714285714285714), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.44827586206896547), 'frac p valence electrons': np.float64(0.4137931034482758), 'frac d valence electrons': np.float64(0.1379310344827586), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 2.125691421567002, 'Average Mulliken electronegativity': 5.094777167642857, 'Valence electrons': 6.0, 'Oxygen_concentration avg': 0.027240092595075472, 'Packing fraction avg': 0.4153469069800403, 'Valence Electrons Density avg': 0.054480185190150944}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [2.12569142e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 1.85714286e+00 1.71428571e+00 5.71428571e-01 0.00000000e+00
 4.48275862e-01 4.13793103e-01 1.37931034e-01 0.00000000e+00
 5.09477717e+00 6.00000000e+00 5.44801852e-02 2.72400926e-02
 4.15346907e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 2.06851046e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   7.55102041e-01  2.85714286e-01  1.36960600e-01  0.00000000e+00
   7.16920609e-01  6.61933739e-01  4.37472593e-01  0.00000000e+00
  -4.05010441e-01  5.26315789e-02  3.02987872e-01  3.02987872e-01
   5.16143152e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[ 2.06851046e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
   2.22222222e-01  7.55102041e-01  2.85714286e-01  1.36960600e-01
   0.00000000e+00  7.16920609e-01 -4.05010441e-01  5.26315789e-02
   5.16143152e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]]
[ 2.06851046e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
  0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
  2.22222222e-01  7.55102041e-01  2.85714286e-01  1.36960600e-01
  0.00000000e+00  7.16920609e-01 -4.05010441e-01  5.26315789e-02
  5.16143152e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]
Prediction:  6.6589487668655645
Predicting for:  generated_cifs\gen_12_Sr7CaO2.cif
loading cif locally
loadied cif locally
Structure is loaded
Sr7 Ca1 O2
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(2.0), np.float64(0.8), np.float64(0.0), np.float64(0.0), np.float64(0.7142857142857143), np.float64(0.28571428571428575), np.float64(0.0), np.float64(0.0)]
{'Sr': 7.0, 'Ca': 1.0, 'O': 2.0}
Sr7 Ca1 O2
2.0
---------------------------------------------
Enter!
Sr7 Ca1 O2
330.90414356311794
1.0
Element: Sr
Element ox state: 2
r:  1.32 ang
Sr   7.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   1.0
Element: O
Element ox state: -2
r:  1.26 ang
O   2.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(2.0), 'avg p valence electrons': np.float64(0.8), 'avg d valence electrons': np.float64(0.0), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.7142857142857143), 'frac p valence electrons': np.float64(0.28571428571428575), 'frac d valence electrons': np.float64(0.0), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 2.915892240100147, 'Average Mulliken electronegativity': 3.8262288289, 'Valence electrons': 4.0, 'Oxygen_concentration avg': 0.006044046407108566, 'Packing fraction avg': 0.27319927402284355, 'Valence Electrons Density avg': 0.012088092814217131}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [2.91589224e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 2.00000000e+00 8.00000000e-01 0.00000000e+00 0.00000000e+00
 7.14285714e-01 2.85714286e-01 0.00000000e+00 0.00000000e+00
 3.82622883e+00 4.00000000e+00 1.20880928e-02 6.04404641e-03
 2.73199274e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 4.17571264e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   1.00000000e+00 -8.00000000e-02 -1.31332083e-02  0.00000000e+00
   1.33554817e+00  1.59663866e-01 -7.16763006e-02  0.00000000e+00
  -1.45200137e+00  0.00000000e+00 -9.41231563e-02 -9.41231563e-02
   2.73417436e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[ 4.17571264e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
   2.22222222e-01  1.00000000e+00 -8.00000000e-02 -1.31332083e-02
   0.00000000e+00  1.33554817e+00 -1.45200137e+00  0.00000000e+00
   2.73417436e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]]
[ 4.17571264e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
  0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
  2.22222222e-01  1.00000000e+00 -8.00000000e-02 -1.31332083e-02
  0.00000000e+00  1.33554817e+00 -1.45200137e+00  0.00000000e+00
  2.73417436e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]
Prediction:  6.725016354335058
Predicting for:  generated_cifs\gen_13_Ca3PO.cif
loading cif locally
loadied cif locally
Structure is loaded
Ca6 P2 O2
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(2.0), np.float64(1.4), np.float64(0.0), np.float64(0.0), np.float64(0.5882352941176471), np.float64(0.4117647058823529), np.float64(0.0), np.float64(0.0)]
{'Ca': 6.0, 'P': 2.0, 'O': 2.0}
Ca6 P2 O2
2.0
---------------------------------------------
Enter!
Ca6 P2 O2
216.22386079708164
2.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   6.0
Element: P
Element ox state: 5
r:  0.52 ang
P   2.0
Element: O
Element ox state: -2
r:  1.26 ang
O   2.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(2.0), 'avg p valence electrons': np.float64(1.4), 'avg d valence electrons': np.float64(0.0), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.5882352941176471), 'frac p valence electrons': np.float64(0.4117647058823529), 'frac d valence electrons': np.float64(0.0), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 2.84069405720629, 'Average Mulliken electronegativity': 4.4725582499000005, 'Valence electrons': 4.0, 'Oxygen_concentration avg': 0.018499345933674992, 'Packing fraction avg': 0.5103185872566169, 'Valence Electrons Density avg': 0.018499345933674992}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'

e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(

Prediction:  6.296880087332151
Predicting for:  generated_cifs\gen_17_Ca5O3.cif
loading cif locally
loadied cif locally
Structure is loaded
Ca5 O3
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(2.0), np.float64(1.5), np.float64(0.0), np.float64(0.0), np.float64(0.5714285714285714), np.float64(0.42857142857142855), np.float64(0.0), np.float64(0.0)]
{'Ca': 5.0, 'O': 3.0}
Ca5 O3
3.0
---------------------------------------------
Enter!
Ca5 O3
139.70997274919577
1.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   5.0
Element: O
Element ox state: -2
r:  1.26 ang
O   3.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(2.0), 'avg p valence electrons': np.float64(1.5), 'avg d valence electrons': np.float64(0.0), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.5714285714285714), 'frac p valence electrons': np.float64(0.42857142857142855), 'frac d valence electrons': np.float64(0.0), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 2.911305914257703, 'Average Mulliken electronegativity': 4.745377267937499, 'Valence electrons': 6.0, 'Oxygen_concentration avg': 0.021473055508968806, 'Packing fraction avg': 0.4020246375732895, 'Valence Electrons Density avg': 0.04294611101793761}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [2.91130591e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 2.00000000e+00 1.50000000e+00 0.00000000e+00 0.00000000e+00
 5.71428571e-01 4.28571429e-01 0.00000000e+00 0.00000000e+00
 4.74537727e+00 6.00000000e+00 4.29461110e-02 2.14730555e-02
 4.02024638e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 4.16348244e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   1.00000000e+00  2.00000000e-01 -1.31332083e-02  0.00000000e+00
   1.00332226e+00  7.19887955e-01 -7.16763006e-02  0.00000000e+00
  -6.93386149e-01  5.26315789e-02  1.94941588e-01  1.94941588e-01
   4.93394568e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[ 4.16348244e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
   2.22222222e-01  1.00000000e+00  2.00000000e-01 -1.31332083e-02
   0.00000000e+00  1.00332226e+00 -6.93386149e-01  5.26315789e-02
   4.93394568e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]]
[ 4.16348244e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
  0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
  2.22222222e-01  1.00000000e+00  2.00000000e-01 -1.31332083e-02
  0.00000000e+00  1.00332226e+00 -6.93386149e-01  5.26315789e-02
  4.93394568e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]
Prediction:  6.379107902740451
Predicting for:  generated_cifs\gen_18_Sr6CaNb2ZnO6.cif
loading cif locally
loadied cif locally
Structure is loaded
Sr6 Ca1 Nb2 Zn1 O6
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(1.875), np.float64(1.5), np.float64(1.125), np.float64(0.0), np.float64(0.4166666666666667), np.float64(0.3333333333333333), np.float64(0.25), np.float64(0.0)]
{'Sr': 6.0, 'Ca': 1.0, 'Nb': 2.0, 'Zn': 1.0, 'O': 6.0}
Sr6 Ca1 Nb2 Zn1 O6
6.0
---------------------------------------------
Enter!
Sr6 Ca1 Nb2 Zn1 O6
296.41317001311216
1.0
Element: Sr
Element ox state: 2
r:  1.32 ang
Sr   6.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   1.0
Element: Nb
Element ox state: 5
r:  0.78 ang
Nb   2.0
Element: Zn
Element ox state: 2
r:  0.88 ang
Zn   1.0
Element: O
Element ox state: -2
r:  1.26 ang
O   6.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(1.875), 'avg p valence electrons': np.float64(1.5), 'avg d valence electrons': np.float64(1.125), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.4166666666666667), 'frac p valence electrons': np.float64(0.3333333333333333), 'frac d valence electrons': np.float64(0.25), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 2.009304130954291, 'Average Mulliken electronegativity': 4.850657063875, 'Valence electrons': 12.0, 'Oxygen_concentration avg': 0.020242015561368558, 'Packing fraction avg': 0.4086034730279822, 'Valence Electrons Density avg': 0.040484031122737116}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [2.00930413e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 1.87500000e+00 1.50000000e+00 1.12500000e+00 0.00000000e+00
 4.16666667e-01 3.33333333e-01 2.50000000e-01 0.00000000e+00
 4.85065706e+00 1.20000000e+01 4.04840311e-02 2.02420156e-02
 4.08603473e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 1.75814435e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   7.85714286e-01  2.00000000e-01  2.82363977e-01  0.00000000e+00
   6.43410853e-01  3.46405229e-01  8.51156069e-01  0.00000000e+00
  -6.06493921e-01  2.10526316e-01  1.71877874e-01  1.71877874e-01
   5.04628329e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[ 1.75814435e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
   2.22222222e-01  7.85714286e-01  2.00000000e-01  2.82363977e-01
   0.00000000e+00  6.43410853e-01 -6.06493921e-01  2.10526316e-01
   5.04628329e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]]
[ 1.75814435e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
  0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
  2.22222222e-01  7.85714286e-01  2.00000000e-01  2.82363977e-01
  0.00000000e+00  6.43410853e-01 -6.06493921e-01  2.10526316e-01
  5.04628329e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]
Prediction:  7.545411642894256
Predicting for:  generated_cifs\gen_19_Sr5Nb3O7.cif
loading cif locally
loadied cif locally
Structure is loaded
Sr5 Nb3 O7
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(1.8), np.float64(1.8666666666666667), np.float64(0.8), np.float64(0.0), np.float64(0.40298507462686567), np.float64(0.417910447761194), np.float64(0.17910447761194032), np.float64(0.0)]
{'Sr': 5.0, 'Nb': 3.0, 'O': 7.0}
Sr5 Nb3 O7
7.0
---------------------------------------------
Enter!
Sr5 Nb3 O7
199.09103511664483
1.0
Element: Sr
Element ox state: 2
r:  1.32 ang
Sr   5.0
Element: Nb
Element ox state: 5
r:  0.78 ang
Nb   3.0
Element: O
Element ox state: -2
r:  1.26 ang
O   7.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(1.8), 'avg p valence electrons': np.float64(1.8666666666666667), 'avg d valence electrons': np.float64(0.8), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.40298507462686567), 'frac p valence electrons': np.float64(0.417910447761194), 'frac d valence electrons': np.float64(0.17910447761194032), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 2.297272560922167, 'Average Mulliken electronegativity': 5.2439204701, 'Valence electrons': 14.0, 'Oxygen_concentration avg': 0.03515979509523767, 'Packing fraction avg': 0.5665142137271205, 'Valence Electrons Density avg': 0.07031959019047535}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [2.29727256e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 1.80000000e+00 1.86666667e+00 8.00000000e-01 0.00000000e+00
 4.02985075e-01 4.17910448e-01 1.79104478e-01 0.00000000e+00
 5.24392047e+00 1.40000000e+01 7.03195902e-02 3.51597951e-02
 5.66514214e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 2.52606016e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   6.57142857e-01  3.46666667e-01  1.96998124e-01  0.00000000e+00
   6.11593197e-01  6.78080187e-01  5.89457338e-01  0.00000000e+00
  -2.81915656e-01  2.63157895e-01  4.51364658e-01  4.51364658e-01
   7.74270510e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[ 2.52606016e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
   2.22222222e-01  6.57142857e-01  3.46666667e-01  1.96998124e-01
   0.00000000e+00  6.11593197e-01 -2.81915656e-01  2.63157895e-01
   7.74270510e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]]
[ 2.52606016e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
  0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
  2.22222222e-01  6.57142857e-01  3.46666667e-01  1.96998124e-01
  0.00000000e+00  6.11593197e-01 -2.81915656e-01  2.63157895e-01
  7.74270510e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]
Prediction:  7.298882914464244
Predicting for:  generated_cifs\gen_1_Sr6CaPbO2.cif
loading cif locally
loadied cif locally
Structure is loaded
Sr6 Ca1 Pb1 O2
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(2.0), np.float64(1.0), np.float64(1.0), np.float64(1.4), np.float64(0.37037037037037035), np.float64(0.18518518518518517), np.float64(0.18518518518518517), np.float64(0.25925925925925924)]
{'Sr': 6.0, 'Ca': 1.0, 'Pb': 1.0, 'O': 2.0}
Sr6 Ca1 Pb1 O2
2.0
---------------------------------------------
Enter!
Sr6 Ca1 Pb1 O2
290.96680453501193
1.0
Element: Sr
Element ox state: 2
r:  1.32 ang
Sr   6.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   1.0
Element: Pb
Element ox state: 2
r:  1.33 ang
Pb   1.0
Element: O
Element ox state: -2
r:  1.26 ang
O   2.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(2.0), 'avg p valence electrons': np.float64(1.0), 'avg d valence electrons': np.float64(1.0), 'avg f valence electrons': np.float64(1.4), 'frac s valence electrons': np.float64(0.37037037037037035), 'frac p valence electrons': np.float64(0.18518518518518517), 'frac d valence electrons': np.float64(0.18518518518518517), 'frac f valence electrons': np.float64(0.25925925925925924), 'Bandgap, eV': 2.437983387875518, 'Average Mulliken electronegativity': 3.9275522114, 'Valence electrons': 4.0, 'Oxygen_concentration avg': 0.006873636335238169, 'Packing fraction avg': 0.3114561172320461, 'Valence Electrons Density avg': 0.013747272670476337}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'

e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(

Prediction:  6.252391869399084
Predicting for:  generated_cifs\gen_23_Ca3O.cif
loading cif locally
loadied cif locally
Structure is loaded
Ca3 O1
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(2.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.6666666666666666), np.float64(0.3333333333333333), np.float64(0.0), np.float64(0.0)]
{'Ca': 3.0, 'O': 1.0}
Ca3 O1
1.0
---------------------------------------------
Enter!
Ca3 O1
101.8648477147743
1.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   3.0
Element: O
Element ox state: -2
r:  1.26 ang
O   1.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(2.0), 'avg p valence electrons': np.float64(1.0), 'avg d valence electrons': np.float64(0.0), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.6666666666666666), 'frac p valence electrons': np.float64(0.3333333333333333), 'frac d valence electrons': np.float64(0.0), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 2.908506200391535, 'Average Mulliken electronegativity': 4.186535923625, 'Valence electrons': 2.0, 'Oxygen_concentration avg': 0.009816929219783851, 'Packing fraction avg': 0.26502554105575277, 'Valence Electrons Density avg': 0.019633858439567702}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [2.90850620e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 2.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 6.66666667e-01 3.33333333e-01 0.00000000e+00 0.00000000e+00
 4.18653592e+00 2.00000000e+00 1.96338584e-02 9.81692922e-03
 2.65025541e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 4.15601653e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   1.00000000e+00  0.00000000e+00 -1.31332083e-02  0.00000000e+00
   1.22480620e+00  3.46405229e-01 -7.16763006e-02  0.00000000e+00
  -1.15462345e+00 -5.26315789e-02 -2.34376445e-02 -2.34376445e-02
   2.59460290e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[ 4.15601653e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
   2.22222222e-01  1.00000000e+00  0.00000000e+00 -1.31332083e-02
   0.00000000e+00  1.22480620e+00 -1.15462345e+00 -5.26315789e-02
   2.59460290e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]]
[ 4.15601653e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
  0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
  2.22222222e-01  1.00000000e+00  0.00000000e+00 -1.31332083e-02
  0.00000000e+00  1.22480620e+00 -1.15462345e+00 -5.26315789e-02
  2.59460290e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]
Prediction:  6.725016354335058
Predicting for:  generated_cifs\gen_24_SrCa6Nb2O7.cif
loading cif locally
loadied cif locally
Structure is loaded
Sr1 Ca6 Nb2 O7
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(1.875), np.float64(1.75), np.float64(0.5), np.float64(0.0), np.float64(0.45454545454545453), np.float64(0.42424242424242425), np.float64(0.12121212121212122), np.float64(0.0)]
{'Sr': 1.0, 'Ca': 6.0, 'Nb': 2.0, 'O': 7.0}
Sr1 Ca6 Nb2 O7
7.0
---------------------------------------------
Enter!
Sr1 Ca6 Nb2 O7
262.5627413881452
1.0
Element: Sr
Element ox state: 2
r:  1.32 ang
Sr   1.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   6.0
Element: Nb
Element ox state: 5
r:  0.78 ang
Nb   2.0
Element: O
Element ox state: -2
r:  1.26 ang
O   7.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(1.875), 'avg p valence electrons': np.float64(1.75), 'avg d valence electrons': np.float64(0.5), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.45454545454545453), 'frac p valence electrons': np.float64(0.42424242424242425), 'frac d valence electrons': np.float64(0.12121212121212122), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 2.293506036446614, 'Average Mulliken electronegativity': 5.108745691343749, 'Valence electrons': 14.0, 'Oxygen_concentration avg': 0.0266602944613986, 'Packing fraction avg': 0.41703948596485213, 'Valence Electrons Density avg': 0.0533205889227972}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [2.29350604e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 1.87500000e+00 1.75000000e+00 5.00000000e-01 0.00000000e+00
 4.54545455e-01 4.24242424e-01 1.21212121e-01 0.00000000e+00
 5.10874569e+00 1.40000000e+01 5.33205889e-02 2.66602945e-02
 4.17039486e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 2.51601610e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   7.85714286e-01  3.00000000e-01  1.18198874e-01  0.00000000e+00
   7.31501057e-01  7.02911468e-01  3.75757576e-01  0.00000000e+00
  -3.93481580e-01  2.63157895e-01  2.92125269e-01  2.92125269e-01
   5.19033334e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[ 2.51601610e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
   2.22222222e-01  7.85714286e-01  3.00000000e-01  1.18198874e-01
   0.00000000e+00  7.31501057e-01 -3.93481580e-01  2.63157895e-01
   5.19033334e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]]
[ 2.51601610e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
  0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
  2.22222222e-01  7.85714286e-01  3.00000000e-01  1.18198874e-01
  0.00000000e+00  7.31501057e-01 -3.93481580e-01  2.63157895e-01
  5.19033334e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]
Prediction:  6.761089782583307
Predicting for:  generated_cifs\gen_25_Sr2CaO3.cif
loading cif locally
loadied cif locally
Structure is loaded
Sr4 Ca2 O6
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(2.0), np.float64(2.0), np.float64(0.0), np.float64(0.0), np.float64(0.5), np.float64(0.5), np.float64(0.0), np.float64(0.0)]
{'Sr': 4.0, 'Ca': 2.0, 'O': 6.0}
Sr4 Ca2 O6
6.0
---------------------------------------------
Enter!
Sr4 Ca2 O6
197.92203498763456
2.0
Element: Sr
Element ox state: 2
r:  1.32 ang
Sr   4.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   2.0
Element: O
Element ox state: -2
r:  1.26 ang
O   6.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(2.0), 'avg p valence electrons': np.float64(2.0), 'avg d valence electrons': np.float64(0.0), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.5), 'frac p valence electrons': np.float64(0.5), 'frac d valence electrons': np.float64(0.0), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 3.231634587936726, 'Average Mulliken electronegativity': 5.2390897755833326, 'Valence electrons': 12.0, 'Oxygen_concentration avg': 0.06062993441205127, 'Packing fraction avg': 1.0228575113798866, 'Valence Electrons Density avg': 0.06062993441205127}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [3.23163459e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 2.00000000e+00 2.00000000e+00 0.00000000e+00 0.00000000e+00
 5.00000000e-01 5.00000000e-01 0.00000000e+00 0.00000000e+00
 5.23908978e+00 1.20000000e+01 6.06299344e-02 6.06299344e-02
 1.02285751e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 5.01769223e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   1.00000000e+00  4.00000000e-01 -1.31332083e-02  0.00000000e+00
   8.37209302e-01  1.00000000e+00 -7.16763006e-02  0.00000000e+00
  -2.85902649e-01  2.10526316e-01  3.60596098e-01  9.28551447e-01
   1.55350441e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[ 5.01769223e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
   2.22222222e-01  1.00000000e+00  4.00000000e-01 -1.31332083e-02
   0.00000000e+00  8.37209302e-01 -2.85902649e-01  2.10526316e-01
   1.55350441e+00  1.00000000e+00  0.00000000e+00  1.80360541e-05]]
[ 5.01769223e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
  0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
  2.22222222e-01  1.00000000e+00  4.00000000e-01 -1.31332083e-02
  0.00000000e+00  8.37209302e-01 -2.85902649e-01  2.10526316e-01
  1.55350441e+00  1.00000000e+00  0.00000000e+00  1.80360541e-05]
Prediction:  6.2936195276600655
Predicting for:  generated_cifs\gen_26_Ca5FeO6.cif
loading cif locally
loadied cif locally
Structure is loaded
Ca5 Fe1 O6
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(2.0), np.float64(2.0), np.float64(0.5), np.float64(0.0), np.float64(0.4444444444444444), np.float64(0.4444444444444444), np.float64(0.1111111111111111), np.float64(0.0)]
{'Ca': 5.0, 'Fe': 1.0, 'O': 6.0}
Ca5 Fe1 O6
6.0
---------------------------------------------
Enter!
Ca5 Fe1 O6
160.06356529943406
1.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   5.0
Element: Fe
Element ox state: 2
r:  0.92 ang
Fe   1.0
Element: O
Element ox state: -2
r:  1.26 ang
O   6.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(2.0), 'avg p valence electrons': np.float64(2.0), 'avg d valence electrons': np.float64(0.5), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.4444444444444444), 'frac p valence electrons': np.float64(0.4444444444444444), 'frac d valence electrons': np.float64(0.1111111111111111), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 2.88402057008019, 'Average Mulliken electronegativity': 5.38413519475, 'Valence electrons': 12.0, 'Oxygen_concentration avg': 0.0374851077993651, 'Packing fraction avg': 0.5283280917348318, 'Valence Electrons Density avg': 0.0749702155987302}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'

e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(

loadied cif locally
Structure is loaded
Sr2 Ca1 Nb1 O6
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(1.9), np.float64(2.4), np.float64(0.4), np.float64(0.0), np.float64(0.40425531914893614), np.float64(0.5106382978723404), np.float64(0.0851063829787234), np.float64(0.0)]
{'Sr': 2.0, 'Ca': 1.0, 'Nb': 1.0, 'O': 6.0}
Sr2 Ca1 Nb1 O6
6.0
---------------------------------------------
Enter!
Sr2 Ca1 Nb1 O6
146.9537559077694
1.0
Element: Sr
Element ox state: 2
r:  1.32 ang
Sr   2.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   1.0
Element: Nb
Element ox state: 5
r:  0.78 ang
Nb   1.0
Element: O
Element ox state: -2
r:  1.26 ang
O   6.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(1.9), 'avg p valence electrons': np.float64(2.4), 'avg d valence electrons': np.float64(0.4), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.40425531914893614), 'frac p valence electrons': np.float64(0.5106382978723404), 'frac d valence electrons': np.float64(0.0851063829787234), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 3.18707815243007, 'Average Mulliken electronegativity': 5.7891419122, 'Valence electrons': 12.0, 'Oxygen_concentration avg': 0.04082917080231484, 'Packing fraction avg': 0.5289880106282803, 'Valence Electrons Density avg': 0.08165834160462968}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [3.18707815e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 1.90000000e+00 2.40000000e+00 4.00000000e-01 0.00000000e+00
 4.04255319e-01 5.10638298e-01 8.51063830e-02 0.00000000e+00
 5.78914191e+00 1.20000000e+01 8.16583416e-02 4.08291708e-02
 5.28988011e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 4.89887507e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   8.28571429e-01  5.60000000e-01  9.19324578e-02  0.00000000e+00
   6.14547254e-01  1.04171882e+00  2.42479400e-01  0.00000000e+00
   1.68080522e-01  2.10526316e-01  5.57581242e-01  5.57581242e-01
   7.10192239e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[4.89887507e-01 0.00000000e+00 5.88026601e-01 9.78384650e-02
  0.00000000e+00 4.89444451e-02 1.11111111e-02 0.00000000e+00
  2.22222222e-01 8.28571429e-01 5.60000000e-01 9.19324578e-02
  0.00000000e+00 6.14547254e-01 1.68080522e-01 2.10526316e-01
  7.10192239e-01 1.00000000e+00 0.00000000e+00 1.80360541e-05]]
[4.89887507e-01 0.00000000e+00 5.88026601e-01 9.78384650e-02
 0.00000000e+00 4.89444451e-02 1.11111111e-02 0.00000000e+00
 2.22222222e-01 8.28571429e-01 5.60000000e-01 9.19324578e-02
 0.00000000e+00 6.14547254e-01 1.68080522e-01 2.10526316e-01
 7.10192239e-01 1.00000000e+00 0.00000000e+00 1.80360541e-05]
Prediction:  5.7636054281867155
Predicting for:  generated_cifs\gen_31_SrNb2O5.cif
loading cif locally
loadied cif locally
Structure is loaded
Sr1 Nb2 O5
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(1.75), np.float64(2.5), np.float64(1.0), np.float64(0.0), np.float64(0.3333333333333333), np.float64(0.47619047619047616), np.float64(0.19047619047619047), np.float64(0.0)]
{'Sr': 1.0, 'Nb': 2.0, 'O': 5.0}
Sr1 Nb2 O5
5.0
---------------------------------------------
Enter!
Sr1 Nb2 O5
119.36179382797437
1.0
Element: Sr
Element ox state: 2
r:  1.32 ang
Sr   1.0
Element: Nb
Element ox state: 5
r:  0.78 ang
Nb   2.0
Element: O
Element ox state: -2
r:  1.26 ang
O   5.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(1.75), 'avg p valence electrons': np.float64(2.5), 'avg d valence electrons': np.float64(1.0), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.3333333333333333), 'frac p valence electrons': np.float64(0.47619047619047616), 'frac d valence electrons': np.float64(0.19047619047619047), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 2.857224001291833, 'Average Mulliken electronegativity': 6.0309554590625, 'Valence electrons': 10.0, 'Oxygen_concentration avg': 0.041889450884141866, 'Packing fraction avg': 0.465018630850084, 'Valence Electrons Density avg': 0.08377890176828373}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [2.85722400e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 1.75000000e+00 2.50000000e+00 1.00000000e+00 0.00000000e+00
 3.33333333e-01 4.76190476e-01 1.90476190e-01 0.00000000e+00
 6.03095546e+00 1.00000000e+01 8.37789018e-02 4.18894509e-02
 4.65018631e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 4.01926400e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   5.71428571e-01  6.00000000e-01  2.49530957e-01  0.00000000e+00
   4.49612403e-01  9.06629318e-01  6.31434077e-01  0.00000000e+00
   3.67660295e-01  1.57894737e-01  5.77445744e-01  5.77445744e-01
   6.00960638e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[4.01926400e-01 0.00000000e+00 5.88026601e-01 9.78384650e-02
  0.00000000e+00 4.89444451e-02 1.11111111e-02 0.00000000e+00
  2.22222222e-01 5.71428571e-01 6.00000000e-01 2.49530957e-01
  0.00000000e+00 4.49612403e-01 3.67660295e-01 1.57894737e-01
  6.00960638e-01 1.00000000e+00 0.00000000e+00 1.80360541e-05]]
[4.01926400e-01 0.00000000e+00 5.88026601e-01 9.78384650e-02
 0.00000000e+00 4.89444451e-02 1.11111111e-02 0.00000000e+00
 2.22222222e-01 5.71428571e-01 6.00000000e-01 2.49530957e-01
 0.00000000e+00 4.49612403e-01 3.67660295e-01 1.57894737e-01
 6.00960638e-01 1.00000000e+00 0.00000000e+00 1.80360541e-05]
Prediction:  5.405166242596612
Predicting for:  generated_cifs\gen_32_Sr3Ca3O5F.cif
loading cif locally
loadied cif locally
Structure is loaded
Sr3 Ca3 O5 F1
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(2.0), np.float64(2.0833333333333335), np.float64(0.0), np.float64(0.0), np.float64(0.489795918367347), np.float64(0.5102040816326532), np.float64(0.0), np.float64(0.0)]
{'Sr': 3.0, 'Ca': 3.0, 'O': 5.0, 'F': 1.0}
Sr3 Ca3 O5 F1
5.0
---------------------------------------------
Enter!
Sr3 Ca3 O5 F1
154.119932654399
1.0
Element: Sr
Element ox state: 2
r:  1.32 ang
Sr   3.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   3.0
Element: O
Element ox state: -2
r:  1.26 ang
O   5.0
Element: F
Element ox state: -1
r:  1.19 ang
F   1.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(2.0), 'avg p valence electrons': np.float64(2.0833333333333335), 'avg d valence electrons': np.float64(0.0), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.489795918367347), 'frac p valence electrons': np.float64(0.5102040816326532), 'frac d valence electrons': np.float64(0.0), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 3.31596099521937, 'Average Mulliken electronegativity': 5.494740394958333, 'Valence electrons': 10.0, 'Oxygen_concentration avg': 0.03244226696628579, 'Packing fraction avg': 0.6259698800747527, 'Valence Electrons Density avg': 0.06488453393257158}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [3.31596100e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 2.00000000e+00 2.08333333e+00 0.00000000e+00 0.00000000e+00
 4.89795918e-01 5.10204082e-01 0.00000000e+00 0.00000000e+00
 5.49474039e+00 1.00000000e+01 6.48845339e-02 3.24422670e-02
 6.25969880e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 5.24256265e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   1.00000000e+00  4.33333333e-01 -1.31332083e-02  0.00000000e+00
   8.13478880e-01  1.04001601e+00 -7.16763006e-02  0.00000000e+00
  -7.49025076e-02  1.57894737e-01  4.00451370e-01  4.00451370e-01
   8.75794671e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[ 5.24256265e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
   2.22222222e-01  1.00000000e+00  4.33333333e-01 -1.31332083e-02
   0.00000000e+00  8.13478880e-01 -7.49025076e-02  1.57894737e-01
   8.75794671e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]]
[ 5.24256265e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
  0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
  2.22222222e-01  1.00000000e+00  4.33333333e-01 -1.31332083e-02
  0.00000000e+00  8.13478880e-01 -7.49025076e-02  1.57894737e-01
  8.75794671e-01  1.00000000e+00  0.00000000e+00  1.80360541e-05]
Prediction:  5.652432645592319
Predicting for:  generated_cifs\gen_3_Sr12Ca4ZnO3.cif
loading cif locally
loadied cif locally
Structure is loaded
Sr12 Ca4 Zn1 O3
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(2.0), np.float64(0.6), np.float64(0.5), np.float64(0.0), np.float64(0.6451612903225806), np.float64(0.1935483870967742), np.float64(0.16129032258064516), np.float64(0.0)]
{'Sr': 12.0, 'Ca': 4.0, 'Zn': 1.0, 'O': 3.0}
Sr12 Ca4 Zn1 O3
3.0
---------------------------------------------
Enter!
Sr12 Ca4 Zn1 O3
727.6209797565942
1.0
Element: Sr
Element ox state: 2
r:  1.32 ang
Sr   12.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   4.0
Element: Zn
Element ox state: 2
r:  0.88 ang
Zn   1.0
Element: O
Element ox state: -2
r:  1.26 ang
O   3.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(2.0), 'avg p valence electrons': np.float64(0.6), 'avg d valence electrons': np.float64(0.5), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.6451612903225806), 'frac p valence electrons': np.float64(0.1935483870967742), 'frac d valence electrons': np.float64(0.16129032258064516), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 2.397198411199111, 'Average Mulliken electronegativity': 3.688143205425, 'Valence electrons': 6.0, 'Oxygen_concentration avg': 0.004123025700830628, 'Packing fraction avg': 0.23147287289070925, 'Valence Electrons Density avg': 0.008246051401661255}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'

e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
C:\Users\Nikita\AppData\Local\Temp\ipykernel_8248\3708692272.py:36: UserWarning: No ionic radius for H+!
  r = specie.ionic_radius
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(

Prediction:  5.95936775364743
Predicting for:  generated_cifs\gen_7_CaO.cif
loading cif locally
loadied cif locally
Structure is loaded
Ca2 O2
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(2.0), np.float64(2.0), np.float64(0.0), np.float64(0.0), np.float64(0.5), np.float64(0.5), np.float64(0.0), np.float64(0.0)]
{'Ca': 2.0, 'O': 2.0}
Ca2 O2
2.0
---------------------------------------------
Enter!
Ca2 O2
57.9747180750398
2.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   2.0
Element: O
Element ox state: -2
r:  1.26 ang
O   2.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(2.0), 'avg p valence electrons': np.float64(2.0), 'avg d valence electrons': np.float64(0.0), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.5), 'frac p valence electrons': np.float64(0.5), 'frac d valence electrons': np.float64(0.0), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 3.424376640469056, 'Average Mulliken electronegativity': 5.30421861225, 'Valence electrons': 4.0, 'Oxygen_concentration avg': 0.06899559209279094, 'Packing fraction avg': 1.0063029454302226, 'Valence Electrons Density avg': 0.06899559209279094}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [3.42437664e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 2.00000000e+00 2.00000000e+00 0.00000000e+00 0.00000000e+00
 5.00000000e-01 5.00000000e-01 0.00000000e+00 0.00000000e+00
 5.30421861e+00 4.00000000e+00 6.89955921e-02 6.89955921e-02
 1.00630295e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 5.53167104e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   1.00000000e+00  4.00000000e-01 -1.31332083e-02  0.00000000e+00
   8.37209302e-01  1.00000000e+00 -7.16763006e-02  0.00000000e+00
  -2.32148843e-01  0.00000000e+00  4.38962009e-01  1.08528327e+00
   1.52523648e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[ 5.53167104e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
   2.22222222e-01  1.00000000e+00  4.00000000e-01 -1.31332083e-02
   0.00000000e+00  8.37209302e-01 -2.32148843e-01  0.00000000e+00
   1.52523648e+00  1.00000000e+00  0.00000000e+00  1.80360541e-05]]
[ 5.53167104e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
  0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
  2.22222222e-01  1.00000000e+00  4.00000000e-01 -1.31332083e-02
  0.00000000e+00  8.37209302e-01 -2.32148843e-01  0.00000000e+00
  1.52523648e+00  1.00000000e+00  0.00000000e+00  1.80360541e-05]
Prediction:  6.056471212054024
Predicting for:  generated_cifs\gen_8_CaO.cif
loading cif locally
loadied cif locally
Structure is loaded
Ca2 O2
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(2.0), np.float64(2.0), np.float64(0.0), np.float64(0.0), np.float64(0.5), np.float64(0.5), np.float64(0.0), np.float64(0.0)]
{'Ca': 2.0, 'O': 2.0}
Ca2 O2
2.0
---------------------------------------------
Enter!
Ca2 O2
58.2275766999429
2.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   2.0
Element: O
Element ox state: -2
r:  1.26 ang
O   2.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(2.0), 'avg p valence electrons': np.float64(2.0), 'avg d valence electrons': np.float64(0.0), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.5), 'frac p valence electrons': np.float64(0.5), 'frac d valence electrons': np.float64(0.0), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 3.424376640469056, 'Average Mulliken electronegativity': 5.30421861225, 'Valence electrons': 4.0, 'Oxygen_concentration avg': 0.068695972367401, 'Packing fraction avg': 1.0019329820307725, 'Valence Electrons Density avg': 0.068695972367401}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [3.42437664e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 2.00000000e+00 2.00000000e+00 0.00000000e+00 0.00000000e+00
 5.00000000e-01 5.00000000e-01 0.00000000e+00 0.00000000e+00
 5.30421861e+00 4.00000000e+00 6.86959724e-02 6.86959724e-02
 1.00193298e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 5.53167104e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   1.00000000e+00  4.00000000e-01 -1.31332083e-02  0.00000000e+00
   8.37209302e-01  1.00000000e+00 -7.16763006e-02  0.00000000e+00
  -2.32148843e-01  0.00000000e+00  4.36155299e-01  1.07966985e+00
   1.51777450e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[ 5.53167104e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
   2.22222222e-01  1.00000000e+00  4.00000000e-01 -1.31332083e-02
   0.00000000e+00  8.37209302e-01 -2.32148843e-01  0.00000000e+00
   1.51777450e+00  1.00000000e+00  0.00000000e+00  1.80360541e-05]]
[ 5.53167104e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
  0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
  2.22222222e-01  1.00000000e+00  4.00000000e-01 -1.31332083e-02
  0.00000000e+00  8.37209302e-01 -2.32148843e-01  0.00000000e+00
  1.51777450e+00  1.00000000e+00  0.00000000e+00  1.80360541e-05]
Prediction:  6.056471212054024
Predicting for:  generated_cifs\gen_9_CaO.cif
loading cif locally
loadied cif locally
Structure is loaded
Ca2 O2
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(2.0), np.float64(2.0), np.float64(0.0), np.float64(0.0), np.float64(0.5), np.float64(0.5), np.float64(0.0), np.float64(0.0)]
{'Ca': 2.0, 'O': 2.0}
Ca2 O2
2.0
---------------------------------------------
Enter!
Ca2 O2
68.65638928136794
2.0
Element: Ca
Element ox state: 2
r:  1.14 ang
Ca   2.0
Element: O
Element ox state: -2
r:  1.26 ang
O   2.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(2.0), 'avg p valence electrons': np.float64(2.0), 'avg d valence electrons': np.float64(0.0), 'avg f valence electrons': np.float64(0.0), 'frac s valence electrons': np.float64(0.5), 'frac p valence electrons': np.float64(0.5), 'frac d valence electrons': np.float64(0.0), 'frac f valence electrons': np.float64(0.0), 'Bandgap, eV': 3.42817321893345, 'Average Mulliken electronegativity': 5.30421861225, 'Valence electrons': 4.0, 'Oxygen_concentration avg': 0.05826114716879709, 'Packing fraction avg': 0.8497407185267132, 'Valence Electrons Density avg': 0.05826114716879709}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [3.42817322e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 2.00000000e+00 2.00000000e+00 0.00000000e+00 0.00000000e+00
 5.00000000e-01 5.00000000e-01 0.00000000e+00 0.00000000e+00
 5.30421861e+00 4.00000000e+00 5.82611472e-02 5.82611472e-02
 8.49740719e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 5.54179525e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   1.00000000e+00  4.00000000e-01 -1.31332083e-02  0.00000000e+00
   8.37209302e-01  1.00000000e+00 -7.16763006e-02  0.00000000e+00
  -2.32148843e-01  0.00000000e+00  3.38406310e-01  8.84171871e-01
   1.25789697e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[ 5.54179525e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
   2.22222222e-01  1.00000000e+00  4.00000000e-01 -1.31332083e-02
   0.00000000e+00  8.37209302e-01 -2.32148843e-01  0.00000000e+00
   1.25789697e+00  1.00000000e+00  0.00000000e+00  1.80360541e-05]]
[ 5.54179525e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
  0.00000000e+00  4.89444451e-02  1.11111111e-02  0.00000000e+00
  2.22222222e-01  1.00000000e+00  4.00000000e-01 -1.31332083e-02
  0.00000000e+00  8.37209302e-01 -2.32148843e-01  0.00000000e+00
  1.25789697e+00  1.00000000e+00  0.00000000e+00  1.80360541e-05]
Prediction:  6.056471212054024

e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(

In [402]:
df_candidates.to_excel(f"{candidate_cif_folder}/candidates_after_inference_{title}.xlsx")

In [403]:
df_candidates

,Unnamed: 0,Formula,Composition,Path,avg s valence electrons,avg p valence electrons,avg d valence electrons,avg f valence electrons,frac s valence electrons,frac p valence electrons,frac d valence electrons,frac f valence electrons,Bandgap_predicted,Log_rate_predicted
0,0,Sr3 Ca1 Zn1 O5,Sr3 Ca1 Zn1 O5,generated_cifs\gen_10_Sr3CaZnO5.cif,2.000000,2.000000,1.000000,0.0,0.400000,0.400000,0.200000,0.000000,2.610747,7.910821
1,1,Ca3 Nb1 O3,Ca3 Nb1 O3,generated_cifs\gen_11_Ca3NbO3.cif,1.857143,1.714286,0.571429,0.0,0.448276,0.413793,0.137931,0.000000,2.125691,6.658949
2,2,Sr7 Ca1 O2,Sr7 Ca1 O2,generated_cifs\gen_12_Sr7CaO2.cif,2.000000,0.800000,0.000000,0.0,0.714286,0.285714,0.000000,0.000000,2.915892,6.725016
3,3,Ca6 P2 O2,Ca6 P2 O2,generated_cifs\gen_13_Ca3PO.cif,2.000000,1.400000,0.000000,0.0,0.588235,0.411765,0.000000,0.000000,2.840694,7.377565
4,4,Ca2 O2,Ca2 O2,generated_cifs\gen_14_CaO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.424377,6.056471
5,5,Ca1 Hg1 O2,Ca1 Hg1 O2,generated_cifs\gen_15_CaHgO2.cif,2.000000,2.000000,2.500000,3.5,0.200000,0.200000,0.250000,0.350000,2.675027,4.516947
6,6,Ca4 O2,Ca4 O2,generated_cifs\gen_16_Ca2O.cif,2.000000,1.333333,0.000000,0.0,0.600000,0.400000,0.000000,0.000000,2.768946,6.296880
7,7,Ca5 O3,Ca5 O3,generated_cifs\gen_17_Ca5O3.cif,2.000000,1.500000,0.000000,0.0,0.571429,0.428571,0.000000,0.000000,2.911306,6.379108
8,8,Sr6 Ca1 Nb2 Zn1 O6,Sr6 Ca1 Nb2 Zn1 O6,generated_cifs\gen_18_Sr6CaNb2ZnO6.cif,1.875000,1.500000,1.125000,0.0,0.416667,0.333333,0.250000,0.000000,2.009304,7.545412
9,9,Sr5 Nb3 O7,Sr5 Nb3 O7,generated_cifs\gen_19_Sr5Nb3O7.cif,1.800000,1.866667,0.800000,0.0,0.402985,0.417910,0.179104,0.000000,2.297273,7.298883
10,10,Sr6 Ca1 Pb1 O2,Sr6 Ca1 Pb1 O2,generated_cifs\gen_1_Sr6CaPbO2.cif,2.000000,1.000000,1.000000,1.4,0.370370,0.185185,0.185185,0.259259,2.437983,7.300479
11,11,Sr2 Ca1 Nb2 Br1 O6,Sr2 Ca1 Nb2 Br1 O6,generated_cifs\gen_20_Sr2CaNb2BrO6.cif,1.833333,2.416667,1.500000,0.0,0.318841,0.420290,0.260870,0.000000,2.551909,5.974378
12,12,Sr1 Ca1 O2,Sr1 Ca1 O2,generated_cifs\gen_21_SrCaO2.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.242396,7.570619
13,13,Ca4 O2,Ca4 O2,generated_cifs\gen_22_Ca2O.cif,2.000000,1.333333,0.000000,0.0,0.600000,0.400000,0.000000,0.000000,2.772827,6.252392
14,14,Ca3 O1,Ca3 O1,generated_cifs\gen_23_Ca3O.cif,2.000000,1.000000,0.000000,0.0,0.666667,0.333333,0.000000,0.000000,2.908506,6.725016
15,15,Sr1 Ca6 Nb2 O7,Sr1 Ca6 Nb2 O7,generated_cifs\gen_24_SrCa6Nb2O7.cif,1.875000,1.750000,0.500000,0.0,0.454545,0.424242,0.121212,0.000000,2.293506,6.761090
16,16,Sr4 Ca2 O6,Sr4 Ca2 O6,generated_cifs\gen_25_Sr2CaO3.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.231635,6.293620
17,17,Ca5 Fe1 O6,Ca5 Fe1 O6,generated_cifs\gen_26_Ca5FeO6.cif,2.000000,2.000000,0.500000,0.0,0.444444,0.444444,0.111111,0.000000,2.884021,7.688535
18,18,Ca3 Bi1 O1,Ca3 Bi1 O1,generated_cifs\gen_27_Ca3BiO.cif,2.000000,1.400000,2.000000,2.8,0.243902,0.170732,0.243902,0.341463,2.409360,7.456643
19,19,Sr2 O2,Sr2 O2,generated_cifs\gen_28_SrO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.127574,6.555966
20,20,Ca4 O4,Ca4 O4,generated_cifs\gen_29_CaO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.424377,5.959368
21,21,Ca2 O2,Ca2 O2,generated_cifs\gen_2_CaO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.424377,6.056471
22,22,Sr2 Ca1 Nb1 O6,Sr2 Ca1 Nb1 O6,generated_cifs\gen_30_Sr2CaNbO6.cif,1.900000,2.400000,0.400000,0.0,0.404255,0.510638,0.085106,0.000000,3.187078,5.763605
23,23,Sr1 Nb2 O5,Sr1 Nb2 O5,generated_cifs\gen_31_SrNb2O5.cif,1.750000,2.500000,1.000000,0.0,0.333333,0.476190,0.190476,0.000000,2.857224,5.405166
24,24,Sr3 Ca3 O5 F1,Sr3 Ca3 O5 F1,generated_cifs\gen_32_Sr3Ca3O5F.cif,2.000000,2.083333,0.000000,0.0,0.489796,0.510204,0.000000,0.000000,3.315961,5.652433
25,25,Sr12 Ca4 Zn1 O3,Sr12 Ca4 Zn1 O3,generated_cifs\gen_3_Sr12Ca4ZnO3.cif,2.000000,0.600000,0.500000,0.0,0.645161,0.193548,0.161290,0.000000,2.397198,7.715453
26,26,Ca3 O2 F1,Ca3 O2 F1,generated_cifs\gen_4_Ca3O2F.cif,2.000000,2.166667,0.000000,0.0,0.480000,0.520000,0.000000,0.000000,3.294944,5.442613
27,27,La1 Nb2 H2 O7,La1 Nb2 H2 O7,generated_cifs\gen_5_LaNb2H2O7.cif,1.666667,2.333333,0.750000,0.0,0.350877,0.491228,0.157895,0.000000,2.724639,6.604271
28,28,Ca4 O4,Ca4 O4,generated_cifs\gen_6_CaO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.424377,5.959368
29,29,Ca2 O2,Ca2 O2,generated_cifs\gen_7_CaO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.424377,6.056471
30,30,Ca2 O2,Ca2 O2,generated_cifs\gen_8_CaO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.424377,6.056471
31,31,Ca2 O2,Ca2 O2,generated_cifs\gen_9_CaO.cif,2.000000,2.000000,0.000000,0.0,0.500000,0.500000,0.000000,0.000000,3.428173,6.056471

In [404]:
import plotly.express as px

In [405]:
fig = px.histogram(
    df_candidates, 
    x=predicted_column, 
    nbins=20, 
    title="Value Distribution",
    width=500,
    height=500
)

fig.show()

In [407]:
clean_data = df_candidates[predicted_column].dropna()

# 2. Replicate Plotly's 20-bin histogram math exactly
counts, bin_edges = np.histogram(clean_data, bins=20,range=[0, 15] )

# 3. Calculate bin centers to match your exact column format
bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2

# 4. Construct your exact desired DataFrame layout
df_hist = pd.DataFrame({
    'Bin_Center': bin_centers,
    'Count': counts
})

print(df_hist)
if(title=="Log_rate"):
    df_hist.to_excel("Log_rate_hist.xlsx")

    Bin_Center  Count
0        0.375      0
1        1.125      0
2        1.875      0
3        2.625      0
4        3.375      0
5        4.125      0
6        4.875      1
7        5.625      7
8        6.375     14
9        7.125      5
10       7.875      5
11       8.625      0
12       9.375      0
13      10.125      0
14      10.875      0
15      11.625      0
16      12.375      0
17      13.125      0
18      13.875      0
19      14.625      0

In [ ]:
s/0

NameError: name 's' is not defined

# Create mattergen dataset

In [ ]:
import logging
import contextlib
import sys
from tqdm.auto import tqdm

In [ ]:
tqdm.pandas()

In [ ]:
def ID_to_formula(ID):
  formula = None
  try:
    structure = mpr.get_structure_by_material_id(ID)
    formula = structure.composition.formula
    return formula
  except:
    return None

In [ ]:
def is_oxide(MP_ID):
    #entry = None
    #try:
    #    entry = mpr.materials.summary.search(material_ids=[MP_ID],fields=["band_gap"])[0]
    #except:
    #    return False
    
    formula = ID_to_formula(MP_ID)
    if formula is None:
        return False
    comp=Composition(formula)
    return "O" in comp

In [ ]:
print(is_oxide("mp-626680"))
print(is_oxide("mp-1225695"))
print(is_oxide("mp-"))

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

True

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

False
False

In [ ]:
predict_candidate_from_cif("M_MP491",4,True)

Predicting for:  M_MP491
loading cif locally from DATA
Nd2 Ti3 H2 O10
['avg s valence electrons', 'avg p valence electrons', 'avg d valence electrons', 'avg f valence electrons', 'frac s valence electrons', 'frac p valence electrons', 'frac d valence electrons', 'frac f valence electrons']
[np.float64(1.8823529411764706), np.float64(2.3529411764705883), np.float64(0.35294117647058826), np.float64(0.47058823529411764), np.float64(0.37209302325581395), np.float64(0.4651162790697675), np.float64(0.06976744186046513), np.float64(0.09302325581395349)]
{'Nd': 2.0, 'Ti': 3.0, 'H': 2.0, 'O': 10.0}
Nd2 Ti3 H2 O10
10.0
---------------------------------------------
Enter!
Nd2 Ti3 H2 O10
229.90248606119223
1.0
Element: Nd
Element ox state: 3
r:  1.123 ang
Nd   2.0
Element: Ti
Element ox state: 4
r:  0.745 ang
Ti   3.0
Element: H
Element ox state: 1
Local ionic radii table request for  H+
r:  0.02
H   2.0
Element: O
Element ox state: -2
r:  1.26 ang
O   10.0
candidate_feature_dict:  {'CalcT(K)': 1296.237241, 'Calc time (h)': 19.567693, 'Promoter, w%': 0, 'Surface area, m2/g': 10.37065568513124, 'Alcohol, %': 1, 'Power, W': 1, 'Wave length min, nm': 200, 'Promotion method_PD': True, 'Promoter_Pt': True, 'Promoter_Rh': False, 'Combined feature': 1, 'd,A': 0, 'Temperature, K': 298, 'Nitrogen': False, 'Prep Method_SSR': True, 'avg s valence electrons': np.float64(1.8823529411764706), 'avg p valence electrons': np.float64(2.3529411764705883), 'avg d valence electrons': np.float64(0.35294117647058826), 'avg f valence electrons': np.float64(0.47058823529411764), 'frac s valence electrons': np.float64(0.37209302325581395), 'frac p valence electrons': np.float64(0.4651162790697675), 'frac d valence electrons': np.float64(0.06976744186046513), 'frac f valence electrons': np.float64(0.09302325581395349), 'Bandgap, eV': 4, 'Average Mulliken electronegativity': 6.219203557923647, 'Valence electrons': 20.0, 'Oxygen_concentration avg': 0.043496702325082036, 'Packing fraction avg': 0.4386749670240664, 'Valence Electrons Density avg': 0.08699340465016407}
Scaling...
len(scaler.feature_names_in_):  52
scaler.feature_names_in_:  ['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Nitrogen' 'Promoter, w%'
 'Surface area, m2/g' 'CatW, g/L' 'Alcohol, %' 'Power, W'
 'Wave length min, nm' 'Temperature, K' 'avg s valence electrons'
 'avg p valence electrons' 'avg d valence electrons'
 'avg f valence electrons' 'frac s valence electrons'
 'frac p valence electrons' 'frac d valence electrons'
 'frac f valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Valence Electrons Density avg'
 'Oxygen_concentration avg' 'Packing fraction avg' 'Prep Method_MSS'
 'Prep Method_PC' 'Prep Method_PTP' 'Prep Method_SG' 'Prep Method_SSR'
 'Prep Method_co-pre' 'Prep Method_perchased' 'Prep Method_purchased'
 'Promotion method_PD' 'Promotion method_impregnation' 'Promoter_CuO'
 'Promoter_Fe2O3' 'Promoter_Ni' 'Promoter_NiO' 'Promoter_No promoter'
 'Promoter_Pt' 'Promoter_Rh' 'Promoter_Ru' 'Promoter_RuO2' 'Promoter_ZnO'
 'Light type_LED' 'Light type_W lamp ' 'Light type_Xe lamp'
 'Light type_visible' 'Cell material_pyrex' 'Cell material_quartz'
 'Combined feature']
X_before_scaler:  [4.00000000e+00 0.00000000e+00 1.29623724e+03 1.95676930e+01
 0.00000000e+00 0.00000000e+00 1.03706557e+01 0.00000000e+00
 1.00000000e+00 1.00000000e+00 2.00000000e+02 2.98000000e+02
 1.88235294e+00 2.35294118e+00 3.52941176e-01 4.70588235e-01
 3.72093023e-01 4.65116279e-01 6.97674419e-02 9.30232558e-02
 6.21920356e+00 2.00000000e+01 8.69934047e-02 4.34967023e-02
 4.38674967e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]
X_after_scaler:  [[ 7.06666667e-01  0.00000000e+00  5.88026601e-01  9.78384650e-02
   0.00000000e+00  0.00000000e+00  4.89444451e-02 -3.34112595e-03
   1.11111111e-02 -1.10000000e-01  0.00000000e+00  2.22222222e-01
   7.98319328e-01  5.41176471e-01  7.95717912e-02  9.41176471e-02
   5.39751217e-01  8.63201094e-01  1.85858314e-01  2.25913621e-01
   5.23030056e-01  4.21052632e-01  6.07557835e-01  6.07557835e-01
   5.55977232e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.80360541e-05]]
The selector selected 20 features:
['Bandgap, eV' 'd,A' 'CalcT(K)' 'Calc time (h)' 'Promoter, w%'
 'Surface area, m2/g' 'Alcohol, %' 'Wave length min, nm' 'Temperature, K'
 'avg s valence electrons' 'avg p valence electrons'
 'avg d valence electrons' 'avg f valence electrons'
 'frac s valence electrons' 'Average Mulliken electronegativity'
 'Valence electrons' 'Packing fraction avg' 'Promoter_Pt' 'Promoter_Rh'
 'Combined feature']
X_after_selector:  [[7.06666667e-01 0.00000000e+00 5.88026601e-01 9.78384650e-02
  0.00000000e+00 4.89444451e-02 1.11111111e-02 0.00000000e+00
  2.22222222e-01 7.98319328e-01 5.41176471e-01 7.95717912e-02
  9.41176471e-02 5.39751217e-01 5.23030056e-01 4.21052632e-01
  5.55977232e-01 1.00000000e+00 0.00000000e+00 1.80360541e-05]]
[7.06666667e-01 0.00000000e+00 5.88026601e-01 9.78384650e-02
 0.00000000e+00 4.89444451e-02 1.11111111e-02 0.00000000e+00
 2.22222222e-01 7.98319328e-01 5.41176471e-01 7.95717912e-02
 9.41176471e-02 5.39751217e-01 5.23030056e-01 4.21052632e-01
 5.55977232e-01 1.00000000e+00 0.00000000e+00 1.80360541e-05]
Prediction:  6.704713886121749

C:\Users\Nikita\AppData\Local\Temp\ipykernel_8248\3708692272.py:36: UserWarning: No ionic radius for H+!
  r = specie.ionic_radius
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
e:\Programming practice\Python\Perovskite\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RFE was fitted with feature names
  warnings.warn(

np.float64(6.704713886121749)

In [ ]:
import os
from pymatgen.io.cif import CifWriter
def get_cif_string_from_id(MP_ID):
  
  file_path="Data/CIF/" + str(MP_ID)+".cif"
  
  #print("Path: ",file_path)
  if os.path.exists(file_path):
    try:
      structure = Structure.from_file(file_path)
    except:
      print('ERROR: Invalid structure for ',MP_ID)
      return None
  else:
    return None

  if(structure == None):
    return None
  writer = CifWriter(structure)
  cif_string = str(writer)
  if not structure.is_ordered:
    return ""
  #print("CIF string: ",cif_string)
  return cif_string

In [ ]:
get_cif_string_from_id("M_MP140")

C:\Users\Nikita\AppData\Local\Temp\ipykernel_8248\1552821960.py:19: UserWarning: Site labels are not unique, which is not compliant with the CIF spec (https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iatom_site_label.html):`['Ti0', 'Ti0', 'Ti1', 'Ti1', 'Ti2', 'Ti2', 'Bi3', 'Bi4', 'Bi5', 'Bi6', 'O7', 'O8', 'O9', 'O10', 'O11', 'O12', 'O13', 'O14', 'O15', 'O16', 'O17', 'O18']`.
  writer = CifWriter(structure)

''

In [ ]:
names = ["test_reduced","val_reduced","train_reduced"]
names = ["train_reduced"]
for name in names:
    df_mattergen = pd.read_excel(f"CIF_files_processing_output/soft 0_5/dataset_1.xlsx")
    print(df_mattergen.shape)
    df_mattergen.dropna(subset=["Bandgap, eV"], inplace=True)
    #df_mattergen = df_mattergen[df_mattergen["Rate, umol/(g*h)"] != 0]
    print(df_mattergen.shape)
    df_mattergen = df_mattergen.groupby('Perovskite', as_index=False).agg('first')
    df_mattergen["Log_rate"] = df_mattergen.progress_apply(lambda row: predict_candidate_from_cif(row["MP_CIF_modified"], row["Bandgap, eV"], True, row["d,A"]), axis=1)
    df_mattergen["cif"] = df_mattergen.progress_apply(lambda row: get_cif_string_from_id(row["MP_CIF_modified"]), axis=1)
    
    
    df_mattergen.to_csv(f"Data/Mattergen_dataset/with_activity/{name}_from_my_dataset.csv", index=False)

In [ ]:
s/0

In [ ]:
s/0

In [ ]:
names = ["test_reduced","val_reduced","train_reduced"]
names = ["train_reduced"]
for name in names:
    df_mattergen = pd.read_csv(f"Data/Mattergen_dataset/init/{name}.csv")
    print(df_mattergen.shape)
    df_mattergen.dropna(subset=["dft_band_gap"], inplace=True)
    df_mattergen = df_mattergen[df_mattergen["dft_band_gap"] != 0]
    print(df_mattergen.shape)
    #df_mattergen["Log_rate"]=df_mattergen["material_id"].progress_apply(lambda x: predict_activity_for_MP_ID(x))
    #df_mattergen.to_csv(f"Data/Mattergen_dataset/with_activity/{name}.csv", index=False)

    df_mattergen["Log_rate"] = df_mattergen.progress_apply(lambda row: predict_candidate_from_cif(row["material_id"], row["dft_band_gap"]), axis=1)
    
    
    df_mattergen.to_csv(f"Data/Mattergen_dataset/with_activity/{name}.csv", index=False)